"""
This type stub file was generated by pyright.
"""

from collections.abc import Collection
from typing import Any, Generic
from typing_extensions import Self, TypeVar, override
from caterpillar.abc import _ArchLike, _ContainsStruct, _ContextLambda, _ContextLike, _EndianLike, _GreedyType, _IT, _LengthT, _OT, _OptionLike, _PrefixedType, _StructLike, _SwitchOptionsT
from caterpillar import registry
from caterpillar.shared import PackMixin, UnpackMixin

_T = TypeVar("_T")
def singleton(cls: type[_T]) -> _T:
    """Simple wrapper to enable singleton structs."""
    ...

INVALID_DEFAULT: object = ...
DEFAULT_OPTION: object = ...
class Field(Generic[_IT, _OT], PackMixin[_IT], UnpackMixin[_OT]):
    """Represents a field in a data structure.

    :param struct: The structure or callable used to define the field's type.
    :param order: Byte order for the field (default: SysNative).
    :param offset: Field offset or callable (default: -1, meaning no explicit offset).
    :param flags: Optional set of flags associated with the field.
    :param amount: The number of elements if this field is a sequence (default: 0).
    :param options: A dictionary representing a switch-case mapping.
    :param condition: A boolean or callable determining whether the field is active.
    :param arch: Architecture specification (default: system_arch).
    :param default: The default value (default: INVALID_DEFAULT).
    :param bits: Bit size if the field is bit-packed.
    """
    def __init__(self, struct: _StructLike[_IT, _OT] | _ContextLambda[_OT] | _ContainsStruct[_IT, _OT], order: _EndianLike | None = ..., offset: _ContextLambda[int] | int = ..., flags: set[_OptionLike] | None = ..., amount: _LengthT = ..., options: _SwitchOptionsT | None = ..., condition: _ContextLambda[bool] | bool = ..., arch: _ArchLike | None = ..., default: object = ..., bits: _ContextLambda[int] | int | None = ...) -> None:
        ...

    @property
    def struct(self) -> _StructLike[_IT, _OT] | _ContextLambda[_OT]:
        """
        The internal structure for this field.
        """
        ...

    @struct.setter
    def struct(self, value: _StructLike[_IT, _OT] | _ContextLambda[_OT] | _ContainsStruct[_IT, _OT]) -> None:
        ...

    @property
    def condition(self) -> _ContextLambda[bool] | bool:
        """
        The field's condition expression or value.
        """
        ...

    @condition.setter
    def condition(self, value: _ContextLambda[bool] | bool) -> None:
        ...

    @property
    def flags(self) -> set[_OptionLike]:
        """The set of flags associated with this field."""
        ...

    @flags.setter
    def flags(self, value: set[_OptionLike]) -> None:
        ...

    def add_flag(self, flag: _OptionLike) -> None:
        """
        Adds a flag to this field.

        :param flag: The flag to add.

        .. versionadded:: 2.6.0
        """
        ...

    def has_flag(self, flag: _OptionLike[Any]) -> bool:
        """Checks whether this field stores the given flag.

        :param flag: the flag to lookup
        :type flag: Flag
        :return: true if this flag has been found
        :rtype: bool
        """
        ...

    def remove_flag(self, flag: _OptionLike) -> None:
        """
        Removes a flag from this field.

        :param flag: The flag to remove.

        .. versionadded:: 2.6.0
        """
        ...

    @property
    def offset(self) -> _ContextLambda[int] | int:
        """The field's offset."""
        ...

    @offset.setter
    def offset(self, value: _ContextLambda[int] | int) -> None:
        ...

    @property
    def amount(self) -> _LengthT | None:
        """The repetition count for this field."""
        ...

    @amount.setter
    def amount(self, value: _LengthT | None) -> None:
        ...

    @property
    def options(self) -> _SwitchOptionsT | None:
        """The switch-case options dictionary."""
        ...

    @options.setter
    def options(self, value: _SwitchOptionsT | None) -> None:
        ...

    @property
    def order(self) -> _EndianLike:
        ...

    @order.setter
    def order(self, value: _EndianLike | None) -> None:
        ...

    def has_order(self) -> bool:
        ...

    @property
    def arch(self) -> _ArchLike:
        ...

    @arch.setter
    def arch(self, value: _ArchLike | None) -> None:
        ...

    def has_arch(self) -> bool:
        ...

    def __or__(self, flag: _OptionLike) -> Self:
        """
        Adds a flag using the '|' operator.

        :param flag: The flag to add.
        :return: The updated Field instance.
        """
        ...

    def __xor__(self, flag: _OptionLike) -> Self:
        """
        Removes a flag using the '^' operator.

        :param flag: The flag to remove.
        :return: The updated Field instance.
        """
        ...

    def __matmul__(self, offset: _ContextLambda[int] | int) -> Self:
        """
        Sets the field's offset using the '@' operator.

        :param offset: The offset value (int or callable).
        :return: The updated Field instance.
        """
        ...

    def __getitem__(self, dim: _LengthT) -> Field[Collection[_IT], Collection[_OT]]:
        """
        Sets the number of elements using the indexing operator (e.g.,
        field[3]).

        :param dim: Repetition count or dynamic type.
        :return: The updated Field instance.
        """
        ...

    def __rshift__(self, switch: _SwitchOptionsT) -> Self:
        """
        Defines switch-case mappings using the '>>' operator.

        :param switch: A dictionary of options.
        :return: The updated Field instance.
        """
        ...

    def __floordiv__(self, condition: _ContextLambda[bool] | bool) -> Self:
        """
        Sets the field's condition using the '//' operator.

        :param condition: A boolean or callable.
        :return: The updated Field instance.
        """
        ...

    def __rsub__(self, bits: _ContextLambda[int] | int) -> Self:
        """
        Sets the number of bits for bit-packed fields using the reverse '-'
        operator.

        :param bits: Bit width (int or callable).
        :return: The updated Field instance.
        """
        ...

    def __set_byteorder__(self, order: _EndianLike) -> Self:
        """
        Explicitly sets the byte order for this field.

        :param order: A ByteOrder instance.
        :return: The updated Field instance.
        """
        ...

    def __type__(self) -> type:
        """
        Returns the resolved type of the field, typically from the struct.

        :return: The field type.
        """
        ...

    __ixor__ = ...
    __ior__ = ...
    __ifloordiv__ = ...
    __irshift__ = ...
    __imatmul__ = ...
    __isub__ = ...
    def is_seq(self) -> bool:
        """Returns whether this field is sequential.

        :return: whether this field is sequental
        :rtype: bool
        """
        ...

    def is_enabled(self, context: _ContextLike) -> bool:
        """Evaluates the condition of this field.

        :param context: the context on which to operate
        :type context: _ContextLike
        :return: ``True``, if this field is enabled
        :rtype: bool
        """
        ...

    def has_condition(self) -> bool:
        """Returns whether this field is linked to a condition"""
        ...

    def length(self, context: _ContextLike) -> _GreedyType | _PrefixedType | int:
        """Calculates the sequence length of this field.

        :param context: the context on which to operate
        :type context: _ContextLike
        :raises DynamicSizeError: if this field has a dynamic size
        :return: the number of elements
        :rtype: Union[int, _GreedyType]
        """
        ...

    def get_struct(self, value: object, context: _ContextLike) -> _StructLike[_IT, _OT]:
        """Returns the struct from stored options.

        :param value: the unpacked or packed value
        :type value: Any
        :param context: the current context
        :type context: _ContextLike
        :return: the struct that packs or unpacks the data
        :rtype: _StructLike
        """
        ...

    def get_offset(self, context: _ContextLike) -> int:
        """Returns the offset position of this field"""
        ...

    def get_type(self) -> type:
        """Returns the annotation type for this field

        :return: the annotation type
        :rtype: type
        """
        ...

    def get_name(self) -> str:
        """Returns the name of this field.

        .. versionchanged:: 2.8.0
            now always returns a string
        """
        ...

    def __unpack__(self, context: _ContextLike) -> _OT:
        """Reads packed data from the given stream.

        This method returns nothing if this field is disabled and applies switch if
        additional options are configured.

        :param context: the current context
        :type context: _ContextLike
        :return: the parsed data
        """
        ...

    def __pack__(self, obj: _IT, context: _ContextLike) -> None:
        """Writes the given object to the provided stream.

        There are several options associated with this function. First, disabled
        fields will never pack any data. Next, if an offset position is specified,
        this method will first jump to that position and then parse all data.

        If this field contains a sequential type, it will automatically iterate over
        all elements in ``obj``. The final stream position will be reset if the user
        flag ``KEEP_POSITION`` is not found.

        :param obj: the value to write
        :type obj
        :param context: the current context with a qualified path
        :type context: _ContextLike
        :raises TypeError: if the value is not iterable but this field is marked
                           to be sequential
        """
        ...

    def __size__(self, context: _ContextLike) -> int:
        """Calculates the size of this field.

        There are several situations to bear in mind when executing this function:

         1. If this field is disabled, it will return zero as its size.
         2. Next, dynamic fields do not store a size and DynamicSizeError will be thrown.
         3. Sequential fields will multiply the struct's size with the amount of elements.

         :param context: the operation context
         :type context: _ContextLike
         :raises DynamicSizeError: if this field has a dynamic size
         :return: the calculated size
         :rtype: int
        """
        ...

    @override
    def __str__(self) -> str:
        ...

    @override
    def __repr__(self) -> str:
        ...



class _CallableTypeConverter(registry.TypeConverter):
    @override
    def matches(self, annotation: object) -> bool:
        ...

    @override
    def convert(self, annotation: _ContextLambda[_OT], kwargs: Any) -> Field[None, _OT]:
        ...
