"""
This type stub file was generated by pyright.
"""

import datetime
from typing import Any, Callable, Generic
from typing_extensions import Buffer, Final, Self, SupportsFloat, SupportsIndex, TypeVar, override
from types import NoneType
from functools import cached_property
from uuid import UUID
from collections.abc import Collection
from caterpillar.abc import _ContextLambda, _ContextLike, _GreedyType, _IT, _LengthT, _OT, _StructLike
from caterpillar.options import Flag
from caterpillar import registry
from ._base import Field, singleton
from ._mixin import ByteOrderMixin, FieldStruct

ENUM_STRICT: Flag[None] = ...
class PyStructFormattedField(FieldStruct[_IT, _IT]):
    """
    A field class representing a binary format using format characters (e.g., 'i', 'I', etc.).

    This class allows you to define fields for binary struct formats using format characters,
    which are often used in Python's `struct` module. Each field is associated with a format character
    (like 'x' for padding or 'i' for a signed integer), and it determines how data is packed and unpacked.

    Example usage:

    >>> field = PyStructFormattedField('i', int)
    >>> field.__repr__()
    "<int32>"

    :param ch: The format character (e.g., 'i', 'I', 'f') that defines how the field is packed and unpacked.
    :param type_: The Python type that corresponds to the format character.
    """
    __slots__: tuple[str, ...] = ...
    def __init__(self, ch: str, type_: type) -> None:
        ...

    def __fmt__(self) -> str:
        """
        Get the format character for this field.

        :return: The format character (e.g., 'i', 'x').
        :rtype: str
        """
        ...

    @override
    def __repr__(self) -> str:
        """
        String representation of the FormatField.

        :return: A string representation.
        """
        ...

    def __type__(self) -> type:
        """
        Get the Python type associated with the format specifier.

        :return: The Python type (e.g., `int`, `float`, etc.).
        :rtype: type
        """
        ...

    def __size__(self, context: _ContextLike) -> int:
        """
        Calculate the size of the field in bytes.

        The size is calculated by dividing the bit size by 8 (since 1 byte = 8 bits).

        :param context: The context for the current field (can be used for calculating dynamic sizes).
        :return: The size of the field in bytes.
        :rtype: int
        """
        ...

    @override
    def pack_single(self, obj: _IT, context: _ContextLike) -> None:
        """
        Pack a single value into the stream using the defined format character.

        :param obj: The value to pack (can be of the type defined by the format character).
        :param context: The context that provides the stream and field-specific information.
        """
        ...

    @override
    def pack_seq(self, seq: Collection[_IT], context: _ContextLike) -> None:
        """
        Pack a sequence of values into the stream.

        If the context specifies a fixed amount, it will pack the sequence accordingly.

        :param seq: The sequence of values to pack.
        :param context: The context providing packing information.
        """
        ...

    @override
    def unpack_single(self, context: _ContextLike) -> Any:
        """
        Unpack a single value from the stream.

        :param context: The context that provides the stream and field-specific information.
        :return: The unpacked value, converted to the field's corresponding Python type.
        """
        ...

    @override
    def unpack_seq(self, context: _ContextLike) -> Collection[_IT]:
        """
        Unpack a sequence of values from the stream.

        :param context: The context that provides the stream and field-specific information.
        :return: A list of unpacked values.
        """
        ...



char: Final[PyStructFormattedField[str]] = ...
boolean: Final[PyStructFormattedField[bool]] = ...
int8: Final[PyStructFormattedField[int]] = ...
uint8: Final[PyStructFormattedField[int]] = ...
int16: Final[PyStructFormattedField[int]] = ...
uint16: Final[PyStructFormattedField[int]] = ...
int32: Final[PyStructFormattedField[int]] = ...
uint32: Final[PyStructFormattedField[int]] = ...
int64: Final[PyStructFormattedField[int]] = ...
uint64: Final[PyStructFormattedField[int]] = ...
pssize: Final[PyStructFormattedField[int]] = ...
psize: Final[PyStructFormattedField[int]] = ...
float16: Final[PyStructFormattedField[float]] = ...
float32: Final[PyStructFormattedField[float]] = ...
float64: Final[PyStructFormattedField[float]] = ...
double: Final[PyStructFormattedField[float]] = ...
void_ptr: Final[PyStructFormattedField[int]] = ...
class Padding(ByteOrderMixin[None, None]):
    """
    A field that consumes or produces a fixed byte pattern.

    The :class:`Padding` type is a special field used to consume or
    generate a predetermined byte sequence during packing or unpacking.
    It can be used both as a standalone field and as part of a larger
    field specification where a *length* is applied.

    >>> pack(None, padding) == b"\\x00"
    b"\\x00"

    :param fill: The byte pattern to consume or produce.  It may be
        either a single integer in the range ``0``-``255`` (which will
        be converted to a one-byte ``bytes`` instance) or a :class:`Buffer`
        object from which a :class:`bytes` sequence is constructed.
        Defaults to ``0x00``.
    :type fill: Buffer | int, optional
    :param strict: When ``True`` the unpacking process verifies that
        the data read from the stream matches the expected pattern
        exactly.  If the data length is not an exact multiple of the
        ``fill`` length, or if any byte differs, a :class:`ValidationError`
        will be raised.  Defaults to ``False``.
    :type strict: bool, optional
    """
    __slots__: tuple[str, ...] = ...
    def __init__(self, fill: Buffer | int = ..., strict: bool = ...) -> None:
        ...

    def __size__(self, context: _ContextLike) -> int:
        """
        Return the size of the padding pattern in bytes.

        :param context: A context object that may be used by the field
            to determine its size.  The padding field ignores the context
            and simply returns the length of its ``fill`` attribute.
        :type context: _ContextLike
        :return: The length of the padding pattern.
        :rtype: int
        """
        ...

    def __type__(self) -> type:
        """
        Return the underlying Python type represented by the field.

        :return: ``NoneType`` - the padding field has no direct value.
        :rtype: type
        """
        ...

    def __unpack__(self, context: _ContextLike) -> None:
        """
        Consume the padding from the stream and validate it.

        The method reads a block of data from the stream.  If a parent
        field specifies a length, that many bytes are read; otherwise
        the entire stream is consumed.  When ``strict`` is enabled,
        the read data is validated against the expected padding pattern.

        :param context: Context containing the stream and optional field
            descriptor.  The stream is accessed via ``context[CTX_STREAM]``,
            and the optional parent field via ``context.get(CTX_FIELD)``.
        :type context: _ContextLike
        :raises ValidationError: If ``strict`` is ``True`` and the
            length of the data is not a multiple of the padding length
            or the data does not match the pattern.
        :raises TypeError: If the field length is provided but is not an
            integer.
        """
        ...

    def __pack__(self, obj: None, context: _ContextLike) -> None:
        """
        Write the padding pattern to the stream.

        The amount of padding written depends on the optional parent
        field.  If the field length is ``Ellipsis`` (``...``) or omitted,
        a single padding block is written.  Otherwise the padding is
        repeated ``amount`` times.

        :param obj: The value to pack; padding has no direct value so
            this argument is ignored.
        :type obj: None
        :param context: Context containing the stream and optional field
            descriptor.  The stream is accessed via ``context[CTX_STREAM]``,
            and the optional parent field via ``context.get(CTX_FIELD)``.
        :type context: _ContextLike
        :raises TypeError: If the field length is provided but is not an
            integer.
        """
        ...

    def __getitem__(self, dim: _LengthT) -> Field[None, None]:
        """
        Return a :class:`Field` instance with this padding as its
        ``field`` and ``dim`` as its length.

        This allows the padding to be used in nested field
        definitions such as ``padding[5]`` or ``Padding(...)[10]``.

        :param dim: The length (or ``...`` for greedy) that the
            resulting field should consume or produce.
        :type dim: _LengthT
        :return: A new :class:`Field` instance wrapping this padding.
        :rtype: Field[None, None]
        """
        ...



padding: Final[Padding] = ...
_IT_transformed = TypeVar("_IT_transformed", default=Any)
_OT_transformed = TypeVar("_OT_transformed", default=Any)
class Transformer(Generic[_IT, _IT_transformed, _OT, _OT_transformed], FieldStruct[_IT, _OT]):
    """
    A class that acts as a transformer for encoding and decoding data using a wrapped _StructLike object.
    """
    __slots__: tuple[str, ...] = ...
    def __init__(self, struct: _StructLike[_IT_transformed, _OT_transformed]) -> None:
        ...

    def __type__(self) -> type | str | None:
        """
        Get the type of the data encoded/decoded by the transformer.

        :return: The type of the data.
        """
        ...

    def __size__(self, context: _ContextLike) -> int:
        """
        Get the size of the data encoded/decoded by the transformer.

        :param context: The current context.
        :return: The size of the data.
        """
        ...

    def encode(self, obj: _IT, context: _ContextLike) -> _IT_transformed:
        """
        Encode data using the wrapped _StructLike object.

        :param obj: The original data to be encoded.
        :param context: The current context.
        :return: The encoded data.
        """
        ...

    def decode(self, parsed: _OT_transformed, context: _ContextLike) -> _OT:
        """
        Decode data using the wrapped _StructLike object.

        :param parsed: The parsed data to be decoded.
        :param context: The current context.
        :return: The decoded data.
        """
        ...

    @override
    def pack_single(self, obj: _IT, context: _ContextLike) -> None:
        """
        Pack a single value into the stream using encoding.

        :param obj: The original data to be encoded and packed.
        :param context: The current context.
        """
        ...

    @override
    def unpack_single(self, context: _ContextLike) -> _OT:
        """
        Unpack a single value from the stream and decode it.

        :param context: The current context.
        :return: The decoded data.
        """
        ...



class Const(Transformer[NoneType, _IT, _IT, _IT]):
    """
    A specialized Transformer that enforces a constant value during
    encoding and decoding.

    This class ensures that the encoded value is always the same
    constant, and when decoding, it checks if the value matches the
    expected constant. If the value doesn't match, a `ValidationError`
    is raised.

    Example usage:

    >>> # Define a constant value to enforce during encoding/decoding
    >>> const_value = 42
    >>> struct = SomeStruct() # must parse 'const_value`
    >>> field = Const(const_value, struct)
    >>> pack(None, field)
    b"\\x2a"
    >>> unpack(field, b"\\x2a")
    42

    :param value: The constant value to be enforced during encoding and decoding.
    :param struct: The _StructLike object to be wrapped.
    """
    __slots__: tuple[str, ...] = ...
    def __init__(self, value: _IT, struct: _StructLike[_IT, _IT]) -> None:
        ...

    @override
    def encode(self, obj: None, context: _ContextLike) -> _IT:
        """
        Encode data using the constant value. This method will always return
        the constant value, regardless of the input. Therefore, :code:`None`
        can be passed as the `obj` parameter.

        :param obj: The original data to be encoded (ignored in this transformer).
        :param context: The current context (optional, not used in this implementation).
        :return: The constant value.

        Example:
            >>> constant_value = 42
            >>> transformer = Const(constant_value, SomeStruct())
            >>> transformer.encode(None, context) # context is optional
            42
        """
        ...

    @override
    def decode(self, parsed: _IT, context: _ContextLike) -> _IT:
        """
        Decode data and ensure it matches the constant value. If the
        parsed value doesn't match, a `ValidationError` is raised.

        :param parsed: The parsed data to be decoded (must match the constant value).
        :param context: The current context (optional, not used in this implementation).
        :return: The constant value if parsed matches the expected constant.
        :raises ValidationError: If the parsed value does not match the constant value.

        Example:
        >>> constant_value = 42
        >>> field = Const(constant_value, SomeStruct())
        >>> unpack(field, b"\\x2a")
        42
        >>> unpack(field, b"\\x24")
        Traceback (most recent call last):
        ...
        ValidationError: Expected 42, got 36
        """
        ...



_EnumT = TypeVar("_EnumT")
class Enum(Generic[_EnumT, _IT], Transformer[_EnumT, _IT, _EnumT | _IT, _IT]):
    """
    A specialized Transformer for encoding and decoding enumeration values.

    This class is used for transforming between enumeration values and their corresponding
    encoded representations (typically integers). It provides encoding and decoding methods
    to ensure that enum values are serialized and deserialized correctly. Additionally, it supports
    a default value in case an invalid or unrecognized value is encountered during decoding.

    Example usage:

    >>> from enum import Enum as PyEnum
    >>> class Color(PyEnum):
    ...     RED = 1
    ...     GREEN = 2
    ...     BLUE = 3
    ...
    >>> cp_enum = Enum(Color, uint8)
    >>> pack(Color.RED, cp_enum, as_field=True)
    b"\\x01"
    >>> unpack(cp_enum, b"\\x01", as_field=True)
    Color.RED

    :param model: The enumeration model (an object with `_member_map_` and `_value2member_map_` attributes).
    :param struct: The _StructLike object to be wrapped.
    :param default: The default value to return if decoding encounters an unrecognized value.
                    Default is `INVALID_DEFAULT`.
    :param strict: controls whether the parsed value has to conform to the input enum model.

    .. versionchanged:: 2.8.0
        Add new 'strict' option.
    """
    __slots__: tuple[str, ...] = ...
    def __init__(self, model: type[_EnumT], struct: _StructLike[_IT, _IT], default: _EnumT | _IT | None | object = ..., strict: bool = ...) -> None:
        ...

    @override
    def __type__(self) -> type[_EnumT] | type[_IT]:
        """
        Determine the type for this transformation, which is either the enum type
        or a union of the enum and struct types, depending on the global field flags.

        :return: The type (either the enum model or a union of enum and struct types).
        """
        ...

    @override
    def encode(self, obj: _EnumT, context: _ContextLike) -> _IT:
        """
        Encode an enumeration value into its corresponding encoded representation.

        :param obj: The original enumeration value to encode (e.g., `Color.RED`).
        :param context: The current context.
        :return: The encoded value (usually an integer representing the enum).
        :raises ValidationError: If the input value is not a valid enum type.

        Example:
        >>> cp_enum.encode(Color.GREEN, context)
        2 # (the integer value of Color.GREEN)
        """
        ...

    @override
    def decode(self, parsed: _IT, context: _ContextLike) -> _EnumT:
        """
        Decode an encoded value (typically an integer) back to its corresponding
        enumeration value.

        :param parsed: The parsed value (usually an integer).
        :param context: The current context.
        :return: The corresponding enumeration value.
        :raises InvalidValueError: If the parsed value cannot be mapped to a valid enum.

        Example:
        >>> cp_enum.decode(1, context)
        Color.RED
        >>> unpack(1, cp_enum, as_field=True)
        Color.RED
        """
        ...



class _EnumTypeConverter(registry.TypeConverter):
    @override
    def matches(self, annotation: object) -> bool:
        ...

    @override
    def convert(self, annotation: object, kwargs: dict[str, Any]) -> _StructLike:
        ...



_MemoryIT = TypeVar("_MemoryIT", default=memoryview | bytes | bytearray)
_MemoryOT = TypeVar("_MemoryOT", default=memoryview)
class Memory(Generic[_MemoryIT, _MemoryOT], FieldStruct[_MemoryIT, _MemoryOT]):
    """
    A class representing a memory field that handles packing and unpacking byte-like objects
    of a specified length.

    The `Memory` class is used to manage fields that contain raw byte data. It allows you to
    pack a byte object (either `bytes` or `memoryview`) into a stream and unpack byte data
    from a stream into a `memoryview`. The length of the memory field can be fixed or dynamically
    determined based on the context. If the length is unspecified, the entire available data in
    the stream is read.

    This class can handle the following scenarios for the `length` argument:
    - **Fixed length**: A specific number of bytes (e.g., `10`).
    - **Dynamic length**: A callable that returns the length based on the current context (e.g., `lambda ctx: ctx["length"]`).
    - **Greedy length**: Using `Ellipsis` (`...`), meaning the entire stream is read regardless of the size.

    Examples:

    >>> # Memory with a fixed length of 10 bytes
    >>> memory = Memory(10)
    >>> memory_dynamic = Memory(lambda ctx: ctx._root.length) # dynamic length based on context
    >>> memory_greedy = Memory(...)
    >>> pack(b"1234567890", memory, as_field=True)
    b"1234567890"
    >>> pack(b"1234567890", memory_dynamic, as_field=True, length=10)
    b"1234567890"
    >>> unpack(b"1234567890", memory_greedy, as_field=True)
    b"1234567890"

    :param length: The length of the memory to pack or unpack. It can be:
                   - An integer specifying the number of bytes to handle.
                   - A callable that dynamically returns the number of bytes based on the context.
                   - Ellipsis (`...`), indicating the length is unspecified and the entire stream should be read.
    """
    __slots__: tuple[str, ...] = ...
    def __init__(self, length: _ContextLambda[int] | int | _GreedyType) -> None:
        ...

    def __type__(self) -> type[memoryview]:
        """
        Return the type of the field, which is `memoryview` for this class.

        :return: `memoryview`
        """
        ...

    def __size__(self, context: _ContextLike) -> int:
        """
        Calculate the size of the memory field based on the `length` parameter.

        If the `length` is callable, it will be invoked with the context to get the size.
        If the `length` is `Ellipsis`, the size is unspecified and the entire stream will be read.

        :param context: The current context.
        :return: The size of the field in bytes, or `Ellipsis` if the length is unspecified.
        """
        ...

    @override
    def pack_single(self, obj: _MemoryIT, context: _ContextLike) -> None:
        """
        Pack a single byte object (memoryview or bytes) into the stream.

        This method writes a byte object (`memoryview` or `bytes`) into the stream,
        ensuring that the size of the object matches the expected length defined by
        the `Memory` field. If the expected size is fixed (not `Ellipsis`), a
        validation is performed to ensure that the length of the `obj` matches
        the expected size.

        Examples:

        >>> memory = Memory(10)
        >>> pack(b"1234567890", memory, as_field=True) # Packs exactly 10 bytes into the stream
        b"1234567890"
        >>> pack(b"1", memory, as_field=True)
        Traceback (most recent call last):
        ...
        ValidationError: Memory field expected 10 bytes, but got 1 bytes instead

        :param obj: The byte object to be packed. This can be either a `memoryview` or a `bytes` object.
        :param context: The current context, which provides access to the stream and any additional metadata needed
                        for packing.

        :raises ValidationError: If the length of the `obj` does not match the expected size.
        """
        ...

    @override
    def unpack_single(self, context: _ContextLike) -> _MemoryOT:
        """
        Unpack a single byte object (memoryview) from the stream.

        This method reads bytes from the stream into a `memoryview`. The size
        of the object to be unpacked is determined by the `Memory` field's length.
        If the length is fixed (not `Ellipsis`), it reads exactly that number of
        bytes. If the length is unspecified (i.e., `Ellipsis`), it reads until the
        end of the stream.

        :param context: The current context, which provides access to the stream and
                        any additional metadata needed for unpacking.
        :return: A `memoryview` object representing the unpacked byte data.
        """
        ...



class Bytes(Memory[bytes, bytes]):
    """Byte sequences.

    Same class as :class:`Memory` but with a type of `bytes` instead of `memoryview`.
    """
    __slots__: tuple[()] = ...
    @override
    def __type__(self) -> type:
        """
        Return the type associated with this `Bytes` field, which is `bytes`.

        :return: The type (bytes).
        """
        ...

    @override
    def unpack_single(self, context: _ContextLike) -> bytes:
        """
        Unpack a single byte sequence (bytes) from the stream.

        :param context: The current context, which provides access to the stream and
                        other necessary metadata for unpacking.
        :return: A `bytes` object representing the unpacked data from the stream.

        """
        ...



class String(Memory[str, str]):
    """String sequences.

    Same class as :class:`Memory` but with a type of `str` instead of `memoryview`.

    :param length: The length of the string to pack or unpack. It can be:
                   - An integer specifying the number of bytes (e.g., `10`).
                   - A callable that dynamically returns the number of bytes based on the context (e.g., `lambda ctx: ctx["length"]`).
                   - Ellipsis (`...`), meaning the entire available stream should be read, regardless of size.
    :param encoding: The encoding to use for converting bytes to a string during unpacking. If not specified, defaults to `None`.
                     If specified, the string will be decoded using this encoding (e.g., `utf-8`).
    """
    __slots__: tuple[str, ...] = ...
    def __init__(self, length: int | _ContextLambda[int] | _GreedyType, encoding: str | _ContextLambda[str] | None = ...) -> None:
        ...

    @override
    def __type__(self) -> type:
        """
        Return the type associated with this `String` field.

        :return: `str` - the type associated with the `String` field.
        """
        ...

    @override
    def pack_single(self, obj: str, context: _ContextLike) -> None:
        """Packs a single string into the stream."""
        ...

    @override
    def unpack_single(self, context: _ContextLike) -> str:
        """
        Unpack a single string from the stream.

        :param context: The current context.
        :return: A `str` representing the unpacked string, decoded from bytes using the specified encoding.
        """
        ...



class CString(FieldStruct[str, str]):
    """
    C-style strings (null-terminated or padded).

    This class is designed for handling strings that are padded to a
    fixed length, typically with zero-padding or any custom padding
    character. It is useful for encoding and decoding data that follows
    the C-style string conventions, where strings are often represented
    by a fixed length, and padding (e.g., null bytes) is used to fill
    the remaining space.

    Example usage:

    >>> cstring = CString(10, encoding='utf-8') # encoding is optional
    >>> pack(cstring, "Hello, World!")
    b"Hello, World\\x00"
    >>> unpack(cstring, b"Hello, World\\x00")
    'Hello, World!'

    This class also supports direct getitem access to create a list:

    >>> cstrings = CString[10] # array of ten strings (variable size)

    :param length: The fixed length of the C-string or a callable that determines
                   the length based on the context. If `None` or `Ellipsis`, the
                   string will be unpacked until the padding character is found.
    :param encoding: The encoding to use for converting the byte data to a string.
                    Defaults to `utf-8`. If `None`, the default encoding is used.
    :param pad: The padding character to use (usually `0` for null padding). If a
                string is provided, it must be a single character. If not specified,
                defaults to `0` (null byte).
    """
    __slots__: tuple[str, ...] = ...
    def __init__(self, length: int | _ContextLambda[int] | _GreedyType | None = ..., encoding: str | _ContextLambda[str] | None = ..., pad: int | str | None = ...) -> None:
        """
        Initialize the String field with a fixed length or a length determined by a context lambda.

        :param length: The fixed length or a context lambda to determine the length dynamically.
        :param encoding: The encoding to use for string encoding/decoding (default is UTF-8).
        """
        ...

    def __class_getitem__(cls, dim: _LengthT) -> Field:
        """
        Allows indexing for `CString` class to support field dimensioning.

        :param dim: The dimension or index of the field.
        :return: A new instance of `CString` with the specified dimension.
        """
        ...

    def __size__(self, context: _ContextLike) -> int:
        """
        Returns the size of the `CString` field.

        :param context: The context used to determine the size.
        :return: The length of the field in bytes.
        """
        ...

    def __type__(self) -> type:
        """
        Returns the type associated with the `CString` field.

        :return: The `str` type, as the field stores string data.
        """
        ...

    @override
    def pack_single(self, obj: str, context: _ContextLike) -> None:
        """
        Pack a single string into the stream with padding.

        This method encodes the string into bytes and pads it to the
        fixed length, if applicable. If the length is dynamic or
        unspecified, padding is added until the total length is achieved.

        :param obj: The string to pack into the stream.
        :param context: The current context.
        :raises ValidationError: If the string is too long for the fixed length.
        """
        ...

    @override
    def unpack_single(self, context: _ContextLike) -> str:
        """
        Unpack a single C-style string from the stream.

        This method reads bytes from the stream until a padding
        character is found. If the length is fixed, it will unpack
        exactly that number of bytes. If length is unspecified, it
        unpacks until the padding character is encountered.

        :param context: The current context, which provides access to the
                        stream and other necessary metadata.
        :return: The unpacked string, stripped of padding, decoded with
                 the specified encoding.
        """
        ...



class ConstString(Const[str]):
    """
    A specialized constant field for handling fixed string values.

    This class is used to define a field that always holds a constant
    string value. The value is validated during both encoding and
    decoding to ensure that the expected constant string is preserved.
    The string can optionally be encoded in a specific encoding.

    Additionally, this class provides a type converter that can be used
    to convert a string annotation to a `ConstString` field.

    >>> @struct
    ... class MyStruct:
    ...     value: "const str" # <-- will be converted to ConstString

    Note that the type declaration above won't work if you enable
    annotation evaluation.

    Examples:

    >>> # Define a constant string value to enforce during encoding/decoding
    >>> const_str = ConstString("Hello, World!")
    >>> pack(None, const_str, as_field=True)
    b"Hello, World!"
    >>> unpack(const_str, b"Hello, World!", as_field=True)
    "Hello, World!"

    :param value: The constant string value to be encoded/decoded.
    :param encoding: The encoding to use for the string (default is UTF-8).
                     If `None`, the default system encoding is used.
    """
    __slots__: tuple[()] = ...
    def __init__(self, value: str, encoding: str | _ContextLambda[str] | None = ...) -> None:
        ...



class ConstBytes(Const[bytes]):
    """
    A constant field for handling fixed bytes values.

    This class is used to define a field that always holds a constant
    bytes value. The value is validated during both encoding and
    decoding to ensure that the expected constant byte sequence is
    preserved.

    This class provides a type converter that can be used to convert
    a bytes annotation to a `ConstBytes` field.

    >>> @struct
    ... class MyStruct:
    ...     value: b"const bytes" # <-- will be converted to ConstBytes

    :param value: The constant bytes value to be encoded/decoded.
    """
    __slots__: tuple[()] = ...
    def __init__(self, value: bytes) -> None:
        ...



class Computed(Generic[_IT], FieldStruct[NoneType, _IT]):
    """
    A specialized field for representing computed or dynamically calculated values.

    This class is used to define a field that holds a computed value. The value
    can either be a constant or a function (lambda) that computes the value
    dynamically based on the context during packing or unpacking.

    The computed value is not directly stored; instead, it is evaluated using
    the provided lambda function or constant value during encoding and decoding.

    Examples:

    >>> # Define a computed field with a constant value
    >>> computed = Computed(42)
    >>> unpack(computed, b"\\x00\\x01", as_field=True)
    42
    >>> pack(None, computed, as_field=True)
    b"" # won't affect the stream

    :param value: A constant value or a lambda function that computes the value
                  based on the context.
    """
    __slots__: tuple[str, ...] = ...
    def __init__(self, value: _IT | _ContextLambda[_IT]) -> None:
        ...

    def __type__(self) -> type:
        """
        Return the type of the computed field.

        :return: `Any` if callable, otherwise the type of the constant value.
        """
        ...

    @override
    def __pack__(self, obj: NoneType, context: _ContextLike) -> None:
        """
        No packing is needed for computed fields, as the value is computed dynamically.

        This function exists to satisfy the `FieldStruct` interface, but does not
        perform any packing.

        :param obj: The object to pack.
        :param context: The current context.
        """
        ...

    def __size__(self, context: _ContextLike) -> int:
        """
        Return the size of the computed field.

        Since the field is computed dynamically, the size is fixed as `0`.

        :param context: The current context.
        :return: Always returns `0` for computed fields.
        """
        ...

    @override
    def __unpack__(self, context: _ContextLike) -> _IT:
        """
        Unpack the computed value based on the context.

        If the value is a callable (lambda), it will be invoked with the context
        to calculate the value. Otherwise, the constant value is returned directly.

        :param context: The current context.
        :return: The computed value or the constant value.
        """
        ...

    @override
    def pack_single(self, obj: NoneType, context: _ContextLike) -> None:
        """
        No packing is needed for computed fields.

        :param obj: The object to pack.
        :param context: The current context.
        """
        ...

    @override
    def unpack_single(self, context: _ContextLike) -> _IT:
        """
        No unpacking is needed for computed fields.

        :param context: The current context.
        """
        ...



@singleton
class Pass(FieldStruct[NoneType, NoneType]):
    """
    A specialized field that does nothing during packing and unpacking.

    This class is used to define a field that effectively "passes" through
    the packing and unpacking process without any modifications or
    transformations. It serves as a placeholder that doesn't store or process
    any data. This can be useful in cases where you need a field in a structure
    but don't want it to affect the overall packing or unpacking logic.

    The `Pass` field always returns `None` during unpacking and does not
    perform any operations during packing.

    Example usage:

    >>> @struct
    ... class MyStruct:
    ...     abc: Pass
    ...
    >>> obj = unpack(MyStruct, b"\\x00\\x01")
    MyStruct(abc=None)
    >>> pack(MyStruct(abc=None))
    b""
    """
    __slots__: tuple[()] = ...
    def __bits__(self) -> int:
        """
        Return the size in bits for the Pass field.

        Since the `Pass` field doesn't hold any data, it is considered to have a
        size of `0` bits.

        :return: Always returns `0` for the Pass field.
        """
        ...

    def __type__(self) -> type:
        """
        Return the type associated with this Pass field.

        The `Pass` field doesn't have a type associated with actual data. It
        effectively represents a `None` type when unpacked.

        :return: `NoneType`.
        """
        ...

    @override
    def __pack__(self, obj: None, context: _ContextLike) -> None:
        ...

    def __size__(self, context: _ContextLike) -> int:
        ...

    @override
    def __unpack__(self, context: _ContextLike) -> None:
        ...

    @override
    def pack_single(self, obj: None, context: _ContextLike) -> None:
        ...

    @override
    def unpack_single(self, context: _ContextLike) -> None:
        ...



_PrefixIOT = TypeVar("_PrefixIOT", default=bytes)
class Prefixed(Generic[_PrefixIOT], FieldStruct[_PrefixIOT, _PrefixIOT]):
    """
    A specialized field for handling data with a prefix (typically indicating length or size).

    This class is used when you want to prefix a data structure with a size or other identifying
    information. The prefix is typically packed first, followed by the actual data. The field
    allows for handling both prefixed data with a structure and simple byte sequences, depending
    on the presence of the `struct` argument. However, the returned prefix value must be
    an integer.

    Example usage:

    >>> prefixed = Prefixed(uint32, Bytes(4))
    >>> pack(b"abcd", prefixed, as_field=True)
    b"\\x00\\x00\\x00\\x04abcd"
    >>> unpack(prefixed, b"\\x00\\x00\\x00\\x04abcd", as_field=True)
    b"abcd"

    The prefix is packed and unpacked independently and is used to determine the size of the
    following data.

    **Please note that this class will have a huge impact on the resulting packing and
    unpacking time and will increase it significantly.**

    Starting from v2.4.0, this class uses the `struct` as its second parameter, moving the
    'encoding' parameter to the third parameter.

    :param prefix: The struct that defines the prefix (e.g., a length field).
    :param struct: The struct that defines the data to follow the prefix (e.g., `Bytes` or another field).
    :param encoding: The encoding to use for the prefix.
    """
    __slots__: tuple[str, ...] = ...
    def __init__(self, prefix: _StructLike[int, int], struct: _StructLike[_PrefixIOT, _PrefixIOT] | None = ..., encoding: str | None = ...) -> None:
        ...

    def __type__(self) -> type | str | None:
        """
        Return the type associated with this Prefixed field.

        If the `struct` is provided, it returns the type of the `struct`. Otherwise, it returns
        `bytes` as the default type for a prefixed field.

        :return: The type associated with the Prefixed field (`bytes` or the type of the struct).
        """
        ...

    def __size__(self, context: _ContextLike) -> int:
        """
        Prefixed fields do not have a fixed size.

        The size of a `Prefixed` field is dynamic, as it depends on the prefix and the data length,
        which can vary. Therefore, calling this method will raise an error.

        :raises DynamicSizeError: Always raises an error as the size is not fixed.
        """
        ...

    @override
    def pack_single(self, obj: _PrefixIOT, context: _ContextLike) -> None:
        """
        Pack a single object into the stream, with the prefix indicating the size.

        This method first packs the length of the data (the prefix), and then writes the actual data.

        :param obj: The object to pack (should be a byte sequence).
        :param context: The current context.
        """
        ...

    @override
    def unpack_single(self, context: _ContextLike) -> _PrefixIOT:
        """
        Unpack a single object from the stream, using the prefix to determine the size.

        This method first unpacks the prefix (which indicates the size), then reads the data
        from the stream based on that size. If a `struct` is provided, the data is then passed
        through the specified structure for further unpacking.

        :param context: The current context.
        :return: The unpacked object, which is either raw bytes or the data structure.
        """
        ...



class Int(FieldStruct[int, int]):
    """Generic Integer

    This class handles packing and unpacking integer values with a specified bit size, either
    signed or unsigned. The size of the integer is defined in bits, and the class ensures the
    appropriate byte representation is used for packing and unpacking.

    :param bits: The bit width of the integer (e.g., 8, 16, 32, 64).
    :param signed: Whether the integer is signed (default is True).
    """
    __slots__: tuple[str, ...] = ...
    def __init__(self, bits: int, signed: bool = ...) -> None:
        ...

    @override
    def __repr__(self) -> str:
        ...

    def __type__(self) -> type:
        """
        Return the type associated with this Int field.

        :return: The type of the field, which is `int`.
        """
        ...

    def __size__(self, context: _ContextLike) -> int:
        """
        Return the size of the integer in bytes.

        :param context: The current context.
        :return: The size of the integer in bytes.
        """
        ...

    @override
    def pack_single(self, obj: int, context: _ContextLike) -> None:
        """
        Pack a single integer value into the stream.

        This method converts the integer value into a byte representation using the specified
        byte order. The byte order is determined from the context's field order
        (either little-endian or big-endian).

        :param obj: The integer value to pack.
        :param context: The current context, which provides the byte order (little-endian or big-endian).
        :raises ValueError: If the integer is too large or small for the given bit width.
        """
        ...

    @override
    def unpack_single(self, context: _ContextLike) -> int:
        """
        Unpack a single integer value from the stream.

        This method reads a byte sequence from the stream, interprets it as an integer using the
        specified byte order and signedness, and returns the integer value.

        :param context: The current context, which provides the byte order (little-endian or big-endian).
        :return: The unpacked integer value.
        :raises ValueError: If the data cannot be unpacked as an integer of the specified size.
        """
        ...



class UInt(Int):
    """Generic unsigned integer."""
    __slots__: tuple[()] = ...
    def __init__(self, bits: int) -> None:
        ...



int24: Final[Int] = ...
uint24: Final[UInt] = ...
class Aligned(FieldStruct[_IT, _OT]):
    """
    Alignment of a struct (before or after)

    This class ensures that the associated `struct` is properly aligned according to
    the specified alignment. It allows for padding before or after the field, ensuring
    that the field starts or ends at a memory address that is a multiple of the alignment.

    Example usage:

    >>> @struct
    ... class Format:
    ...     a: Aligned(int16, alignment=4, after=True)
    ...     b: uint8
    ...
    >>> unpack(Format, b"\\x00\\x01\\xFF\\xFF\\x01")
    Traceback (most recent call last):
    ...
    ValueError: Expected 2 bytes of padding (value=0), got 0
    >>> unpack(Format, b"\\x00\\x01\\x00\\x00\\x01")
    Format(a=256, b=1)

    This example shows a `Format` structure where:
    - `a` is an aligned integer (with 4-byte alignment) and padding is applied after the field.
    - `b` is an unsigned byte (`uint8`), which follows `a` after the padding.

    :param struct: The structure that is to be aligned.
    :param alignment: The alignment value in bytes, which must be a power of 2.
                      This can be an integer or a context lambda for dynamic alignment.
    :param after: If `True`, padding is applied after the structure (align after).
    :param before: If `True`, padding is applied before the structure (align before).
    :param filler: The byte value to use for padding. It can be an integer or a string
                   (default is zero-padding). If no filler is provided, `b"\x00"` will
                   be used as the padding byte.
    :raises ValueError: If neither `before` nor `after` is specified, if the filler is not a
                        single byte, or if the padding does not match the expected value.
    :raises DynamicSizeError: If dynamic alignment is used and the size cannot be determined.
    """
    __slots__: tuple[str, ...] = ...
    def __init__(self, struct: _StructLike[_IT, _OT], alignment: int | _ContextLambda[int], after: bool = ..., before: bool = ..., filler: int | str | None = ...) -> None:
        ...

    def __type__(self) -> type | str | None:
        """
        Return the type associated with this aligned field.

        :return: The type of the struct (usually `bytes` or another custom type).
        """
        ...

    def __size__(self, context: _ContextLike) -> int:
        """
        Calculate the size of the aligned field, accounting for padding based on the alignment.

        :param context: The current context.
        :return: The size of the aligned field, including padding if necessary.
        :raises DynamicSizeError: If the alignment is dynamic and cannot be determined.
        """
        ...

    def unpack_alignment(self, context: _ContextLike) -> None:
        """
        Unpack padding for the alignment, verifying that the correct amount of padding is present.

        :param context: The current context.
        :raises ValueError: If the padding does not match the expected value.
        """
        ...

    @override
    def unpack_single(self, context: _ContextLike) -> _OT:
        """
        Unpack a single aligned field from the stream.

        This method ensures that padding is applied before or after the field as needed
        based on the `before` and `after` parameters.

        :param context: The current context.
        :return: The unpacked structure, properly aligned.
        """
        ...

    def pack_alignment(self, context: _ContextLike) -> None:
        """
        Apply padding for the alignment before or after the structure, depending on
        the `before` and `after` settings.

        :param context: The current context.
        """
        ...

    @override
    def pack_single(self, obj: _IT, context: _ContextLike) -> None:
        """
        Pack a single aligned field into the stream, applying padding if necessary.

        :param obj: The structure to pack.
        :param context: The current context.
        """
        ...



def align(alignment: int | _ContextLambda[int]) -> _ContextLambda[int]:
    """
    Create a context lambda to calculate the alignment padding required at the current stream position.

    This function generates a lambda that can be used to compute the amount of padding required
    to ensure that the next structure in the stream is aligned to the specified alignment.

    The alignment value can either be a fixed integer (representing the alignment in bytes)
    or a context lambda that computes the alignment dynamically based on the current context.

    Example usage:

    >>> @struct
    ... class Format:
    ...     a: uint8
    ...     b: padding[align(4)]
    ...
    >>> unpack(Format, b"\\x01\\x00\\x00\\x00")
    Format(a=1, b=None)

    :param alignment: The alignment value in bytes, which must be a power of 2.
                      This can be either an integer or a context lambda.
    :return: A context lambda function that returns the number of bytes to align the next structure.
    """
    ...

class Lazy(FieldStruct[_IT, _OT]):
    """
    A lazy field struct that defers the creation of the underlying struct until it is needed.

    This class allows the definition of a field where the underlying struct is not created until
    the field is actually accessed. This can help with optimization in scenarios where certain
    fields may not always be used.

    The underlying struct is defined by a callable that returns an instance of a struct.
    The `struct_fn` function is invoked to generate the struct when the field is accessed.

    Example usage:

    >>> @struct
    ... class Format:
    ...     a: Lazy(lambda: SecondFormat)  # Lazy instantiation of the struct
    ...     b: uint8
    ...
    >>> @struct
    ... class SecondFormat:
    ...     a: uint8
    ...
    >>> unpack(Format, b"\\x01\\x02\\xFF")
    Format(a=SecondFormat(a=1), b=255)

    :param struct: A callable that returns the underlying struct, which will be lazily created
                   when the field is accessed.
    """
    def __init__(self, struct: Callable[[], _StructLike[_IT, _OT]]) -> None:
        ...

    @cached_property
    def struct(self) -> _StructLike[_IT, _OT]:
        """
        Get the underlying struct by invoking the callable.

        This method ensures that the struct is only created once, and it is cached for subsequent use.

        :return: The underlying struct.
        :rtype: _StructLike
        """
        ...

    def __bits__(self) -> int:
        """
        Get the bit representation of the Lazy struct by delegating to the underlying struct.

        :return: The bit representation of the struct.
        :rtype: str
        """
        ...

    def __type__(self) -> type | str | None:
        """
        Get the type associated with the Lazy struct by delegating to the underlying struct.

        :return: The type associated with the struct.
        :rtype: type
        """
        ...

    def __size__(self, context: _ContextLike) -> int:
        """
        Get the size of the Lazy struct by delegating to the underlying struct.

        :param context: The context for size calculation.
        :return: The size of the struct.
        :rtype: int
        """
        ...

    @override
    def pack_single(self, obj: _IT, context: _ContextLike) -> None:
        """
        Pack a single value using the Lazy struct by delegating to the underlying struct.

        :param obj: The value to pack.
        :param context: The context for packing.
        """
        ...

    @override
    def unpack_single(self, context: _ContextLike) -> _OT:
        """
        Unpack a single value using the Lazy struct by delegating to the underlying struct.

        :param context: The context for unpacking.
        :return: The unpacked value.
        """
        ...



@singleton
class Uuid(FieldStruct[UUID, UUID]):
    """
    A field for handling UUID values.

    This class is responsible for serializing and deserializing UUIDs to and
    from their binary representation. The UUID is represented as a 16-byte
    field (128 bits) and supports both little-endian and big-endian formats.

    Example usage:

    >>> unpack(Uuid, b'e3215476e89b12d3', as_field=True)
    UUID('65333231-3534-3736-6538-396231326433')

    :param value: The UUID value, which is typically a `UUID` object from the
                  `uuid` module.
    :param context: The context for packing and unpacking the UUID. The
                    context includes stream order information for byte
                    order (little-endian or big-endian).
    """
    __slots__: tuple[()] = ...
    def __type__(self) -> type:
        """
        Get the type associated with the UUID field.

        :return: The type `UUID`.
        :rtype: type
        """
        ...

    def __size__(self, context: _ContextLike) -> int:
        """
        Get the size of the UUID field.

        :param context: The context for size calculation.
        :return: The size of the UUID in bytes (16 bytes).
        :rtype: int
        """
        ...

    def __bits__(self) -> int:
        """
        Get the bit representation of the UUID field.

        :return: The bit size of the UUID field (128 bits).
        :rtype: int
        """
        ...

    @override
    def __pack__(self, obj: UUID, context: _ContextLike) -> None:
        """
        Pack a UUID object into the stream.

        Depending on the byte order (little-endian or big-endian) specified
        in the context, the UUID will be packed in the corresponding byte order.

        :param obj: The `UUID` object to pack.
        :param context: The current context, which includes the stream and byte order.
        """
        ...

    @override
    def __unpack__(self, context: _ContextLike) -> UUID:
        """
        Unpack a UUID from the stream.

        Depending on the byte order (little-endian or big-endian) specified
        in the context, the UUID will be unpacked in the corresponding byte order.

        :param context: The current context, which includes the stream and byte order.
        :return: The unpacked `UUID` object.
        :rtype: UUID
        """
        ...



class AsLengthRef:
    """
    A special field for automatically determining the length of a field
    based on a target field.

    This field is used to pack and unpack a length value for a target field.
    When packing, the length of the target field is determined by getting the
    length of the target field's value from the context. When unpacking, the
    unpacked value is used as the length of the target field.

    Example usage:

    >>> @struct
    ... class MyStruct:
    ...     length: AsLengthRef("length", "data", uint16) = 0
    ...     a: uint8
    ...     data: Bytes(this.length)
    ...
    >>> pack(MyStruct(data=b"Hello, world!", a=1))
    b'\\x00\\x0c\\x01Hello, world!'

    :param target: The target field name to determine the length from.
    :param struct: The struct definition of the length field.
    """
    __slots__: tuple[str, ...] = ...
    def __init__(self, name: str, target: str, struct: _StructLike[int, int] | None = ...) -> None:
        ...

    def __mod__(self, other: _StructLike[int, int]) -> Self:
        ...

    def __rmod__(self, other: _StructLike[int, int]) -> Self:
        ...

    def __type__(self) -> type:
        ...

    def __size__(self, context: _ContextLike) -> int:
        ...

    def __bits__(self) -> int:
        ...

    def __pack__(self, obj: None, context: _ContextLike) -> None:
        ...

    def __unpack__(self, context: _ContextLike) -> int:
        ...

    @override
    def __repr__(self) -> str:
        ...



_TimestampT = TypeVar("_TimestampT", bound=SupportsFloat | SupportsIndex)
class Timestamp(Transformer[datetime.datetime, _TimestampT, datetime.datetime, _TimestampT,]):
    """Transformer for serializing and deserializing ``datetime.datetime``
    objects to and from Unix timestamps.

    This transformer converts a ``datetime.datetime`` instance into a Unix
    timestamp during encoding and reconstructs a ``datetime.datetime`` from a
    timestamp during decoding. The timestamp may be represented as either a
    floating-point or integer value depending on the provided configuration.

    >>> field = Timestamp(float64)
    >>> pack(datetime.datetime.now(), field)
    b'...'
    >>> unpack(field, _)
    datetime.datetime(1990, 1, 1, 0, 0, 0, 0)


    :param struct: A struct-like object responsible for encoding/decoding the
        timestamp representation, defaults to ``float64``
    :type struct: _StructLike[_TimestampT, _TimestampT], optional
    :param tz: Timezone information used when reconstructing the datetime
        during decoding, defaults to None
    :type tz: datetime.tzinfo | None, optional
    :param fp: Explicit flag indicating whether the timestamp should be treated
        as floating-point. If None, the type is inferred from ``struct``,
        defaults to None
    :type fp: bool | None, optional
    """
    def __init__(self, struct: _StructLike[_TimestampT, _TimestampT] = ..., tz: datetime.tzinfo | None = ..., fp: bool | None = ...) -> None:
        """Constructor method"""
        ...

    @override
    def encode(self, obj: datetime.datetime, context: _ContextLike) -> _TimestampT:
        """Encode a ``datetime.datetime`` object into a Unix timestamp.

        The resulting timestamp is returned as either a floating-point or
        integer value depending on the ``floating_point`` configuration.

        :param obj: Datetime object to be encoded
        :type obj: datetime.datetime
        :param context: Transformation context used during encoding
        :type context: _ContextLike
        :return: Unix timestamp representation of the datetime
        :rtype: _TimestampT
        """
        ...

    @override
    def decode(self, parsed: _TimestampT, context: _ContextLike) -> datetime.datetime:
        """Decode a Unix timestamp into a ``datetime.datetime`` object.

        The timestamp is converted to a float before constructing the datetime
        instance. The configured timezone is applied if provided.

        :param parsed: Parsed timestamp value
        :type parsed: _TimestampT
        :param context: Transformation context used during decoding
        :type context: _ContextLike
        :return: Reconstructed datetime object
        :rtype: datetime.datetime
        """
        ...
