"""
This type stub file was generated by pyright.
"""

from types import TracebackType
from typing_extensions import Self, override
from caterpillar.context import ConditionContext
from caterpillar.abc import _ContextLambda, _ContextLike, _StructLike

class ConditionalChain:
    """Simplistic conditional chain that represents if-else statements.

    Using this class we can introduce conditional statements into our
    class definition. While this class can't be used in class definitions,
    it may be used outside of them.

    For conditional statements in class definitions, see
    :class:`~caterpillar.fields.conditional.If`,
    :class:`~caterpillar.fields.conditional.ElseIf` or
    :class:`~caterpillar.fields.conditional.Else`.
    """
    __slots__: tuple[str, ...] = ...
    def __init__(self, struct: _StructLike, condition: _ContextLambda[bool] | bool) -> None:
        ...

    def __type__(self) -> type | str | None:
        ...

    @override
    def __repr__(self) -> str:
        ...

    def add(self, struct: _StructLike, func: _ContextLambda[bool] | bool) -> None:
        ...

    def get_struct(self, context: _ContextLike) -> _StructLike | None:
        ...

    def __unpack__(self, context: _ContextLike) -> object:
        ...

    def __pack__(self, obj: object, context: _ContextLike) -> None:
        ...

    def __size__(self, context: _ContextLike) -> int:
        ...



class If(ConditionContext):
    """If-statement implementation for class definitions.

    .. versionchanged:: 2.4.5

        Python 3.14 is **not** supported.

    .. code-block:: python

        @struct
        class Format:
            a: uint32

            with If(lambda _: GLOBAL_CONSTANT == 33):
                b: uint8

    Note that this class will alter the used fields and cover multiple
    field definitions. In addition, the type annotation will be modified
    to display the condition as well.

    .. note::
        This class is **not** a struct, but a simple context manager.
    """
    ...


class ElseIf(ConditionContext):
    """ElseIf-statement implementation for class definitions.

    .. versionchanged:: 2.4.3

        Python 3.14 is **not** supported.

    .. code-block:: python

        @struct
        class Format:
            a: uint32

            with this.a == 32:
                ...

            with ElseIf(this.a == 34):
                ...
    """
    @override
    def __enter__(self) -> Self:
        ...

    @override
    def __exit__(self, exc_type: type, exc_value: Exception, traceback: TracebackType) -> None:
        ...



Else = ...
