"""
This type stub file was generated by pyright.
"""

from collections.abc import Iterable
from typing import Any, Generic
from typing_extensions import Self, TypeVar, override
from caterpillar.fields import Field, FieldMixin
from caterpillar.abc import _ActionLike, _ArchLike, _ContextLike, _EndianLike, _OptionLike

class _Member:
    def __init__(self, name: str | None, field: Field, include: bool = ..., is_action: bool = ...) -> None:
        ...

    @override
    def __repr__(self) -> str:
        ...

    @override
    def __eq__(self, value: object, /) -> bool:
        ...



_SeqModelT = TypeVar("_SeqModelT", default=dict[str, Any])
_SeqOT = TypeVar("_SeqOT", default=dict[str, Any])
_SeqIT = TypeVar("_SeqIT", default=dict[str, Any])
_ExtraOptionT = _EndianLike | _ArchLike | _OptionLike[Any]
_AnnotationT = str | bytes | Field | type | _ActionLike | Any
class Sequence(Generic[_SeqModelT, _SeqIT, _SeqOT], FieldMixin[_SeqIT, _SeqOT]):
    """Default implementation for a sequence of fields.

    The native Python type mapped to this struct class is :code:`dict`. To convert
    a dictionary into a sequence, you can either use the contructor directly or apply
    the type converter for this class:

    >>> to_struct({'a': uint8})
    Sequence(fields=['a'])
    """
    __slots__: tuple[str, ...] = ...
    def __init__(self, model: _SeqModelT, order: _EndianLike | None = ..., arch: _ArchLike | None = ..., options: Iterable[_OptionLike] | None = ..., field_options: Iterable[_OptionLike] | None = ...) -> None:
        ...

    def __add__(self, sequence: Sequence[Any, Any, Any]) -> Self:
        ...

    def __sub__(self, sequence: Sequence) -> Self:
        ...

    __iadd__ = ...
    __isub__ = ...
    def __type__(self) -> type:
        ...

    def has_option(self, option: _OptionLike[Any]) -> bool:
        """
        Check if the struct has a specific option.

        :param option: The option to check.
        :return: True if the struct has the specified option, else False.
        """
        ...

    def add_field(self, name: str, field: Field, included: bool = ...) -> None:
        """
        Add a field to the struct.

        :param name: The name of the field.
        :param field: The field to add.
        :param included: True if the field should be included, else False.
        """
        ...

    def add_action(self, action: _ActionLike) -> None:
        """
        Add an action to the struct.

        :param action: The action to add.
        """
        ...

    def del_field(self, name: str, field: Field) -> None:
        """
        Remomves a field from this struct.

        :param name: The name of the field.
        :param field: The field to remove.
        """
        ...

    def get_members(self) -> dict[str, Field]:
        ...

    def __size__(self, context: _ContextLike) -> int:
        """
        Get the size of the struct.

        :param context: The context of the struct.
        :return: The size of the struct.
        """
        ...

    def unpack_one(self, context: _ContextLike) -> _SeqOT:
        ...

    def __unpack__(self, context: _ContextLike) -> _SeqOT:
        """
        Unpack the struct from the stream.

        :param stream: The stream to unpack from.
        :param context: The context of the struct.
        :return: The unpacked object.
        """
        ...

    def get_value(self, obj: _SeqIT, name: str, field: Field) -> Any | None:
        ...

    def pack_one(self, obj: _SeqIT, context: _ContextLike) -> None:
        ...

    def __pack__(self, obj: _SeqIT, context: _ContextLike) -> None:
        ...

    @override
    def __repr__(self) -> str:
        ...

    @override
    def __str__(self) -> str:
        ...
