"""Beatmap domain models."""

from osu_server.domain.beatmaps.eligibility import (
    BeatmapStatus,
    EligibilityResult,
)
from osu_server.domain.beatmaps.errors import (
    BeatmapSourceError,
    BeatmapSourceErrorCategory,
)
from osu_server.domain.beatmaps.models import (
    Beatmap,
    BeatmapEligibility,
    BeatmapFetchRecord,
    BeatmapFetchState,
    BeatmapFetchTarget,
    BeatmapFileAttachment,
    BeatmapFileProvider,
    BeatmapFileSource,
    BeatmapFileState,
    BeatmapFreshnessDecision,
    BeatmapFreshnessPolicy,
    BeatmapMetadataProvider,
    BeatmapMetadataSource,
    BeatmapRankStatus,
    BeatmapResolveOptions,
    BeatmapResolveResult,
    BeatmapSet,
    BeatmapSetResolveResult,
    BeatmapsetSnapshot,
    BeatmapSnapshot,
    BeatmapSourceVerification,
    LocalBeatmapStatus,
    OsuFileFetchResult,
    map_external_status,
)

__all__ = [
    "Beatmap",
    "BeatmapEligibility",
    "BeatmapFetchRecord",
    "BeatmapFetchState",
    "BeatmapFetchTarget",
    "BeatmapFileAttachment",
    "BeatmapFileProvider",
    "BeatmapFileSource",
    "BeatmapFileState",
    "BeatmapFreshnessDecision",
    "BeatmapFreshnessPolicy",
    "BeatmapMetadataProvider",
    "BeatmapMetadataSource",
    "BeatmapRankStatus",
    "BeatmapResolveOptions",
    "BeatmapResolveResult",
    "BeatmapSet",
    "BeatmapSetResolveResult",
    "BeatmapSnapshot",
    "BeatmapSourceError",
    "BeatmapSourceErrorCategory",
    "BeatmapSourceVerification",
    "BeatmapStatus",
    "BeatmapsetSnapshot",
    "EligibilityResult",
    "LocalBeatmapStatus",
    "OsuFileFetchResult",
    "map_external_status",
]
