"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Generic
from typing_extensions import Final, override
from caterpillar.abc import _ArrayFactoryLike, _OptionLike, _VT

@dataclass(init=False, eq=False)
class Flag(Generic[_VT]):
    """Simple customizable user-flag."""
    name: str
    value: _VT | None = ...
    def __init__(self, name: str, value: _VT | None = ...) -> None:
        ...

    @override
    def __hash__(self) -> int:
        """
        Custom hash method based on the flag's name.

        :return: The hash value.
        """
        ...

    @override
    def __eq__(self, value: object, /) -> bool:
        ...



GLOBAL_STRUCT_OPTIONS: set[_OptionLike] = ...
GLOBAL_UNION_OPTIONS: set[_OptionLike] = ...
GLOBAL_FIELD_FLAGS: set[_OptionLike] = ...
GLOBAL_BITFIELD_FLAGS: set[_OptionLike] = ...
def configure(base: set[_OptionLike], *flags: _OptionLike) -> None:
    """
    Update the base set of flags with additional flags.

    :param base: The base set of flags.
    :param flags: Additional flags to be added.
    """
    ...

def set_struct_flags(*flags: _OptionLike, with_union: bool = ...) -> None:
    """
    Set default flags for structs.

    :param flags: Flags to be set.
    :param with_union: Whether to include the flags for unions as well.
    """
    ...

def set_field_flags(*flags: _OptionLike) -> None:
    """
    Set default flags for fields.

    :param flags: Flags to be set.
    """
    ...

def set_union_flags(*flags: _OptionLike) -> None:
    """
    Set default flags for unions.

    :param flags: Flags to be set.
    """
    ...

def get_flags(obj: object, attr: str | None = ...) -> list[_OptionLike]:
    """
    Get the flags associated with an object.

    .. versionchanged:: 2.8.0
        now always returns a list

    :param obj: The object.
    :param attr: The attribute name containing the flags (default is "flags").
    :return: The set of flags, or None if no flags are present.
    """
    ...

def has_flag(flag: _OptionLike[_VT], obj: object, attr: str | None = ...) -> bool:
    """
    Check if an object has a specific flag.

    :param flag: The flag to check, either as a string or a Flag instance.
    :param obj: The object.
    :param attr: The attribute name containing the flags (default is "flags").
    :return: True if the flag is present, False otherwise.
    """
    ...

def get_flag(name: str, obj: object, attr: str | None = ...) -> _OptionLike[_VT] | None:
    """
    Get a specific flag associated with an object.

    :param name: The name of the flag.
    :param obj: The object.
    :param attr: The attribute name containing the flags (default is "flags").
    :return: The Flag instance if found, otherwise None.
    """
    ...

S_DISCARD_UNNAMED: Final[Flag] = ...
S_SLOTS: Final[Flag] = ...
S_REPLACE_TYPES: Final[Flag] = ...
S_EVAL_ANNOTATIONS: Final[Flag] = ...
S_UNION: Final[Flag] = ...
S_ADD_BYTES: Final[Flag] = ...
S_DISCARD_CONST: Final[Flag] = ...
F_KEEP_POSITION: Final[Flag] = ...
F_DYNAMIC: Final[Flag] = ...
F_SEQUENTIAL: Final[Flag] = ...
F_OFFSET_OVERRIDE: Final[Flag] = ...
O_ARRAY_FACTORY: Flag[_ArrayFactoryLike] = ...
B_OVERWRITE_ALIGNMENT: Final[Flag] = ...
B_GROUP_END: Final[Flag] = ...
B_GROUP_NEW: Final[Flag] = ...
B_GROUP_KEEP: Final[Flag] = ...
B_NO_AUTO_BOOL: Final[Flag] = ...
