"""
This type stub file was generated by pyright.
"""

from typing import Any, Generic, TYPE_CHECKING, overload
from typing_extensions import Buffer, Final, Literal, TypeIs, override
from caterpillar.abc import _ActionLike, _ArchLike, _ContainsStruct, _ContextLambda, _EndianLike, _IT, _OT, _StreamType, _StructLike, _SupportsType
from caterpillar.fields import FieldStruct

"""
Module containing shared constants and utility functions for managing
and processing structs.

This module defines a set of constants and functions used across different
operations involving structs, bitfields, and related concepts. It includes
key attributes for managing struct definitions, mode constants for packing
/unpacking operations, and action handling for custom processing.

The module introduces the concept of "Actions", which are used to define
custom behavior that should be executed before parsing a struct field (e.g.,
installing IO hooks for checksums or hash calculations). Actions are
represented by classes with `__action_XX` methods.

Usage Example:
  To define a struct that executes a custom action before parsing a field:

  >>> class MyAction:
  >>>     def __action_unpack__(self, context: _ContextLike) -> None:
  >>>         ...
  >>>
  >>> @struct
  >>> class MyStruct:
  >>>     any_name: MyAction()

In this case, the action will be executed before parsing any subsequent fields
and won't be stored as part of the struct model.
"""
if TYPE_CHECKING:
    ...
MODE_PACK: Literal[0] = ...
MODE_UNPACK: Literal[1] = ...
ATTR_STRUCT: Final[str] = ...
ATTR_BYTEORDER: Final[str] = ...
ATTR_TYPE: Final[str] = ...
ATTR_BITS: Final[str] = ...
ATTR_SIGNED: Final[str] = ...
ATTR_TEMPLATE: Final[str] = ...
ATTR_PACK: Final[str] = ...
ATTR_UNPACK: Final[str] = ...
ATTR_ACTION_PACK: Final[str] = ...
ATTR_ACTION_UNPACK: Final[str] = ...
def constval(value: _OT) -> _ContextLambda[_OT]:
    """Returns a lambda that returns a constant value when invoked.

    :param value: The constant value to be returned by the lambda.
    :type value: _OT
    :return: A lambda function that, when called, returns the given constant value.
    :rtype: _ContextLambda[_OT]
    """
    ...

class Action:
    """
    A class representing an action to be executed during the parsing or processing
    of a struct. This is used for cases where a field requires an operation to be
    performed instead of directly storing data.

    An action can be used to execute custom logic (such as modifying the IO stream)
    before the next field is processed. For example, it could be used to trigger
    checksum or hash calculations before reading a struct field.

    There are two types of actions:

    1. **Packing actions**: These actions are triggered before packing the data into the struct (i.e., before serializing or encoding).
    2. **Unpacking actions**: These actions are triggered before unpacking the data from the struct (i.e., before deserializing or decoding).

    Example:

    >>> def checksum_action(context: _ContextLike) -> None:
    ...     # This action could perform some checksum or logging logic
    ...     pass
    ...
    >>> @struct
    ... class MyStruct:
    ...     some_field: Bytes(10)
    ...     checksum: Action(checksum_action) # runs only when packing

    In this example, the `checksum` field is an action, and the `checksum_action`
    will be invoked before the `some_field` field is parsed.

    The action itself is not stored as part of the struct's model; it merely runs
    during struct processing.

    :param pack: The callable that will be executed before packing the struct (optional).
    :type pack: _ContextLambda | None
    :param unpack: The callable that will be executed before unpacking the struct (optional).
    :type unpack: _ContextLambda | None
    """
    __slots__: tuple[str, str] = ...
    def __init__(self, pack: _ContextLambda[None] | None = ..., unpack: _ContextLambda[None] | None = ..., both: _ContextLambda[None] | None = ...) -> None:
        ...

    @override
    def __repr__(self) -> str:
        """
        Return a string representation of the action, showing its callable name
        and location.

        If only one of the action types is provided (either packing or unpacking),
        the corresponding action type (`PackAction` or `UnpackAction`) is displayed.

        :return: A string representation of the action.
        :rtype: str
        """
        ...

    @staticmethod
    def is_action(obj: object) -> TypeIs[_ActionLike]:
        """
        Checks if the given object is an instance of an `Action` class,
        based on the presence of the `__action_pack__` or `__action_unpack__` attributes.

        :param obj: The object to check.
        :type obj: Any
        :return: True if the object has either a `__action_pack__` or `__action_unpack__` attribute, indicating it is an action.
        :rtype: bool
        """
        ...



def hasstruct(obj: object) -> TypeIs[_ContainsStruct]:
    """
    Check if the given object has a structure attribute.

    :param obj: The object to check.
    :return: True if the object has a structure attribute, else False.
    """
    ...

@overload
def getstruct(obj: type[_IT], /, __default: None = ...) -> FieldStruct[_IT, _IT]:
    ...

@overload
def getstruct(obj: _ContainsStruct[_IT, _OT], /, __default: None = ...) -> _StructLike[_IT, _OT]:
    ...

@overload
def getstruct(obj: object, /, __default: _StructLike | None = ...) -> _StructLike | FieldStruct | None:
    ...

def getstruct(obj: object, /, __default: _StructLike | None = ...) -> _StructLike | FieldStruct | None:
    """
    Get the structure attribute of the given object.

    :param obj: The object to get the structure attribute from.
    :return: The structure attribute of the object.
    """
    ...

def typeof(struct: _StructLike | _SupportsType | _ContainsStruct | object) -> type:
    """Returns the type of a given struct or object, checking for a custom type annotation.

    If the given object has a `__type__` attribute, this function returns that type. If not, it
    returns the object's default type. If the type cannot be resolved, the function defaults to
    returning `object`.

    :param struct: The struct or object whose type is to be resolved.
    :type struct: _StructLike | _SupportsType | _ContainsStruct | object
    :return: The resolved type of the struct or object.
    :rtype: type
    """
    ...

class PackMixin(Generic[_IT]):
    """Mixin providing serialization helpers for packing objects into binary
    representations.

    This mixin exposes a unified ``to_bytes`` interface that can either return
    serialized bytes directly or write them into a provided writable stream.

    .. versionadded:: 2.8.1
    """
    @overload
    def to_bytes(self, obj: _IT, *, fp: _StreamType, order: _EndianLike | None = ..., arch: _ArchLike | None = ..., use_tempfile: bool = ..., **kwargs: Any) -> None:
        ...

    @overload
    def to_bytes(self, obj: _IT, *, fp: None = ..., order: _EndianLike | None = ..., arch: _ArchLike | None = ..., use_tempfile: bool = ..., **kwargs: Any) -> bytes:
        ...

    def to_bytes(self, obj: _IT, *, fp: _StreamType | None = ..., order: _EndianLike | None = ..., arch: _ArchLike | None = ..., use_tempfile: bool = ..., **kwargs: Any) -> bytes | None:
        """Serialize the object into its binary representation.

        If ``fp`` is provided, the binary data is written directly into the
        given stream using ``pack_into``. Otherwise, the binary data is
        returned as a ``bytes`` object using ``pack``.

        :param obj: Object instance to serialize
        :type obj: _IT
        :param fp: Writable stream to receive the serialized data. If None,
            the serialized bytes are returned, defaults to None
        :type fp: _StreamType | None, optional
        :param order: Endianness override for serialization, defaults to None
        :type order: _EndianLike | None, optional
        :param arch: Architecture override for serialization, defaults to None
        :type arch: _ArchLike | None, optional
        :param use_tempfile: Whether to use a temporary file during packing,
            defaults to False
        :type use_tempfile: bool, optional
        :raises Exception: Propagates any exception raised by the underlying
            packing implementation
        :return: Serialized bytes if ``fp`` is None, otherwise None
        :rtype: bytes | None
        """
        ...



class UnpackMixin(Generic[_OT]):
    """Mixin providing deserialization helpers for constructing objects from
    binary data sources.

    This mixin supports unpacking from raw bytes, streams, or files, and also
    defines a convenience left-shift operator for inline unpacking.

    .. versionadded:: 2.8.1
    """
    def __lshift__(self, data: Buffer | _StreamType) -> _OT:
        """Unpack binary data using the left-shift operator.

        This operator is a shorthand for calling :meth:`from_bytes`, enabling
        concise inline unpacking from a bytes-like object or a readable stream.

        :param data: Raw bytes or a readable stream containing serialized data
        :type data: Buffer | _StreamType
        :return: Parsed associated type instance
        :rtype: _OT
        """
        ...

    def from_bytes(self, data: Buffer | _StreamType, *, order: _EndianLike | None = ..., arch: _ArchLike | None = ..., **kwargs: Any) -> _OT:
        """Construct an object from raw binary data or a stream.

        This is a convenience wrapper around the underlying ``unpack``
        function, allowing associated types to be instantiated directly from
        bytes without importing parsing utilities.

        :param data: Raw bytes or a readable stream containing serialized data
        :type data: Buffer | _StreamType
        :param order: Endianness override for parsing, defaults to None
        :type order: _EndianLike | None, optional
        :param arch: Architecture override for parsing, defaults to None
        :type arch: _ArchLike | None, optional
        :raises Exception: Propagates any exception raised by the underlying
            unpacking implementation
        :return: Parsed associated type instance
        :rtype: _OT
        """
        ...

    def from_file(self, filename: str, *, order: _EndianLike | None = ..., arch: _ArchLike | None = ..., **kwargs: Any) -> _OT:
        """Construct an instance from a binary file on disk.

        This is a convenience wrapper around ``unpack_file`` for reading and
        parsing structured data directly from a file path.

        :param filename: Path to the file containing serialized data
        :type filename: str
        :param order: Endianness override for parsing, defaults to None
        :type order: _EndianLike | None, optional
        :param arch: Architecture override for parsing, defaults to None
        :type arch: _ArchLike | None, optional
        :raises Exception: Propagates any exception raised by the underlying
            file-unpacking implementation
        :return: Parsed associated type instance
        :rtype: _OT
        """
        ...
