"""
This type stub file was generated by pyright.
"""

import enum
import typing
import ssl
from contextlib import asynccontextmanager, contextmanager
from types import TracebackType
from ._auth import Auth
from ._config import Limits, Timeout
from ._models import Cookies, Headers, Request, Response
from ._transports.base import AsyncBaseTransport, BaseTransport
from ._types import AsyncByteStream, AuthTypes, CertTypes, CookieTypes, HeaderTypes, ProxyTypes, QueryParamTypes, RequestContent, RequestData, RequestExtensions, RequestFiles, SyncByteStream, TimeoutTypes
from ._urls import QueryParams, URL

if typing.TYPE_CHECKING:
    ...
__all__ = ["USE_CLIENT_DEFAULT", "AsyncClient", "Client"]
T = typing.TypeVar("T", bound="Client")
U = typing.TypeVar("U", bound="AsyncClient")
class UseClientDefault:
    """
    For some parameters such as `auth=...` and `timeout=...` we need to be able
    to indicate the default "unset" state, in a way that is distinctly different
    to using `None`.

    The default "unset" state indicates that whatever default is set on the
    client should be used. This is different to setting `None`, which
    explicitly disables the parameter, possibly overriding a client default.

    For example we use `timeout=USE_CLIENT_DEFAULT` in the `request()` signature.
    Omitting the `timeout` parameter will send a request using whatever default
    timeout has been configured on the client. Including `timeout=None` will
    ensure no timeout is used.

    Note that user code shouldn't need to use the `USE_CLIENT_DEFAULT` constant,
    but it is used internally when a parameter is not included.
    """
    ...


USE_CLIENT_DEFAULT = ...
logger = ...
USER_AGENT = ...
ACCEPT_ENCODING = ...
class ClientState(enum.Enum):
    UNOPENED = ...
    OPENED = ...
    CLOSED = ...


class BoundSyncStream(SyncByteStream):
    """
    A byte stream that is bound to a given response instance, and that
    ensures the `response.elapsed` is set once the response is closed.
    """
    def __init__(self, stream: SyncByteStream, response: Response, start: float) -> None:
        ...

    def __iter__(self) -> typing.Iterator[bytes]:
        ...

    def close(self) -> None:
        ...



class BoundAsyncStream(AsyncByteStream):
    """
    An async byte stream that is bound to a given response instance, and that
    ensures the `response.elapsed` is set once the response is closed.
    """
    def __init__(self, stream: AsyncByteStream, response: Response, start: float) -> None:
        ...

    async def __aiter__(self) -> typing.AsyncIterator[bytes]:
        ...

    async def aclose(self) -> None:
        ...



EventHook = typing.Callable[..., typing.Any]
class BaseClient:
    def __init__(self, *, auth: AuthTypes | None = ..., params: QueryParamTypes | None = ..., headers: HeaderTypes | None = ..., cookies: CookieTypes | None = ..., timeout: TimeoutTypes = ..., follow_redirects: bool = ..., max_redirects: int = ..., event_hooks: None | typing.Mapping[str, list[EventHook]] = ..., base_url: URL | str = ..., trust_env: bool = ..., default_encoding: str | typing.Callable[[bytes], str] = ...) -> None:
        ...

    @property
    def is_closed(self) -> bool:
        """
        Check if the client being closed
        """
        ...

    @property
    def trust_env(self) -> bool:
        ...

    @property
    def timeout(self) -> Timeout:
        ...

    @timeout.setter
    def timeout(self, timeout: TimeoutTypes) -> None:
        ...

    @property
    def event_hooks(self) -> dict[str, list[EventHook]]:
        ...

    @event_hooks.setter
    def event_hooks(self, event_hooks: dict[str, list[EventHook]]) -> None:
        ...

    @property
    def auth(self) -> Auth | None:
        """
        Authentication class used when none is passed at the request-level.

        See also [Authentication][0].

        [0]: /quickstart/#authentication
        """
        ...

    @auth.setter
    def auth(self, auth: AuthTypes) -> None:
        ...

    @property
    def base_url(self) -> URL:
        """
        Base URL to use when sending requests with relative URLs.
        """
        ...

    @base_url.setter
    def base_url(self, url: URL | str) -> None:
        ...

    @property
    def headers(self) -> Headers:
        """
        HTTP headers to include when sending requests.
        """
        ...

    @headers.setter
    def headers(self, headers: HeaderTypes) -> None:
        ...

    @property
    def cookies(self) -> Cookies:
        """
        Cookie values to include when sending requests.
        """
        ...

    @cookies.setter
    def cookies(self, cookies: CookieTypes) -> None:
        ...

    @property
    def params(self) -> QueryParams:
        """
        Query parameters to include in the URL when sending requests.
        """
        ...

    @params.setter
    def params(self, params: QueryParamTypes) -> None:
        ...

    def build_request(self, method: str, url: URL | str, *, content: RequestContent | None = ..., data: RequestData | None = ..., files: RequestFiles | None = ..., json: typing.Any | None = ..., params: QueryParamTypes | None = ..., headers: HeaderTypes | None = ..., cookies: CookieTypes | None = ..., timeout: TimeoutTypes | UseClientDefault = ..., extensions: RequestExtensions | None = ...) -> Request:
        """
        Build and return a request instance.

        * The `params`, `headers` and `cookies` arguments
        are merged with any values set on the client.
        * The `url` argument is merged with any `base_url` set on the client.

        See also: [Request instances][0]

        [0]: /advanced/clients/#request-instances
        """
        ...



class Client(BaseClient):
    """
    An HTTP client, with connection pooling, HTTP/2, redirects, cookie persistence, etc.

    It can be shared between threads.

    Usage:

    ```python
    >>> client = httpx.Client()
    >>> response = client.get('https://example.org')
    ```

    **Parameters:**

    * **auth** - *(optional)* An authentication class to use when sending
    requests.
    * **params** - *(optional)* Query parameters to include in request URLs, as
    a string, dictionary, or sequence of two-tuples.
    * **headers** - *(optional)* Dictionary of HTTP headers to include when
    sending requests.
    * **cookies** - *(optional)* Dictionary of Cookie items to include when
    sending requests.
    * **verify** - *(optional)* Either `True` to use an SSL context with the
    default CA bundle, `False` to disable verification, or an instance of
    `ssl.SSLContext` to use a custom context.
    * **http2** - *(optional)* A boolean indicating if HTTP/2 support should be
    enabled. Defaults to `False`.
    * **proxy** - *(optional)* A proxy URL where all the traffic should be routed.
    * **timeout** - *(optional)* The timeout configuration to use when sending
    requests.
    * **limits** - *(optional)* The limits configuration to use.
    * **max_redirects** - *(optional)* The maximum number of redirect responses
    that should be followed.
    * **base_url** - *(optional)* A URL to use as the base when building
    request URLs.
    * **transport** - *(optional)* A transport class to use for sending requests
    over the network.
    * **trust_env** - *(optional)* Enables or disables usage of environment
    variables for configuration.
    * **default_encoding** - *(optional)* The default encoding to use for decoding
    response text, if no charset information is included in a response Content-Type
    header. Set to a callable for automatic character set detection. Default: "utf-8".
    """
    def __init__(self, *, auth: AuthTypes | None = ..., params: QueryParamTypes | None = ..., headers: HeaderTypes | None = ..., cookies: CookieTypes | None = ..., verify: ssl.SSLContext | str | bool = ..., cert: CertTypes | None = ..., trust_env: bool = ..., http1: bool = ..., http2: bool = ..., proxy: ProxyTypes | None = ..., mounts: None | typing.Mapping[str, BaseTransport | None] = ..., timeout: TimeoutTypes = ..., follow_redirects: bool = ..., limits: Limits = ..., max_redirects: int = ..., event_hooks: None | typing.Mapping[str, list[EventHook]] = ..., base_url: URL | str = ..., transport: BaseTransport | None = ..., default_encoding: str | typing.Callable[[bytes], str] = ...) -> None:
        ...

    def request(self, method: str, url: URL | str, *, content: RequestContent | None = ..., data: RequestData | None = ..., files: RequestFiles | None = ..., json: typing.Any | None = ..., params: QueryParamTypes | None = ..., headers: HeaderTypes | None = ..., cookies: CookieTypes | None = ..., auth: AuthTypes | UseClientDefault | None = ..., follow_redirects: bool | UseClientDefault = ..., timeout: TimeoutTypes | UseClientDefault = ..., extensions: RequestExtensions | None = ...) -> Response:
        """
        Build and send a request.

        Equivalent to:

        ```python
        request = client.build_request(...)
        response = client.send(request, ...)
        ```

        See `Client.build_request()`, `Client.send()` and
        [Merging of configuration][0] for how the various parameters
        are merged with client-level configuration.

        [0]: /advanced/clients/#merging-of-configuration
        """
        ...

    @contextmanager
    def stream(self, method: str, url: URL | str, *, content: RequestContent | None = ..., data: RequestData | None = ..., files: RequestFiles | None = ..., json: typing.Any | None = ..., params: QueryParamTypes | None = ..., headers: HeaderTypes | None = ..., cookies: CookieTypes | None = ..., auth: AuthTypes | UseClientDefault | None = ..., follow_redirects: bool | UseClientDefault = ..., timeout: TimeoutTypes | UseClientDefault = ..., extensions: RequestExtensions | None = ...) -> typing.Iterator[Response]:
        """
        Alternative to `httpx.request()` that streams the response body
        instead of loading it into memory at once.

        **Parameters**: See `httpx.request`.

        See also: [Streaming Responses][0]

        [0]: /quickstart#streaming-responses
        """
        ...

    def send(self, request: Request, *, stream: bool = ..., auth: AuthTypes | UseClientDefault | None = ..., follow_redirects: bool | UseClientDefault = ...) -> Response:
        """
        Send a request.

        The request is sent as-is, unmodified.

        Typically you'll want to build one with `Client.build_request()`
        so that any client-level configuration is merged into the request,
        but passing an explicit `httpx.Request()` is supported as well.

        See also: [Request instances][0]

        [0]: /advanced/clients/#request-instances
        """
        ...

    def get(self, url: URL | str, *, params: QueryParamTypes | None = ..., headers: HeaderTypes | None = ..., cookies: CookieTypes | None = ..., auth: AuthTypes | UseClientDefault | None = ..., follow_redirects: bool | UseClientDefault = ..., timeout: TimeoutTypes | UseClientDefault = ..., extensions: RequestExtensions | None = ...) -> Response:
        """
        Send a `GET` request.

        **Parameters**: See `httpx.request`.
        """
        ...

    def options(self, url: URL | str, *, params: QueryParamTypes | None = ..., headers: HeaderTypes | None = ..., cookies: CookieTypes | None = ..., auth: AuthTypes | UseClientDefault = ..., follow_redirects: bool | UseClientDefault = ..., timeout: TimeoutTypes | UseClientDefault = ..., extensions: RequestExtensions | None = ...) -> Response:
        """
        Send an `OPTIONS` request.

        **Parameters**: See `httpx.request`.
        """
        ...

    def head(self, url: URL | str, *, params: QueryParamTypes | None = ..., headers: HeaderTypes | None = ..., cookies: CookieTypes | None = ..., auth: AuthTypes | UseClientDefault = ..., follow_redirects: bool | UseClientDefault = ..., timeout: TimeoutTypes | UseClientDefault = ..., extensions: RequestExtensions | None = ...) -> Response:
        """
        Send a `HEAD` request.

        **Parameters**: See `httpx.request`.
        """
        ...

    def post(self, url: URL | str, *, content: RequestContent | None = ..., data: RequestData | None = ..., files: RequestFiles | None = ..., json: typing.Any | None = ..., params: QueryParamTypes | None = ..., headers: HeaderTypes | None = ..., cookies: CookieTypes | None = ..., auth: AuthTypes | UseClientDefault = ..., follow_redirects: bool | UseClientDefault = ..., timeout: TimeoutTypes | UseClientDefault = ..., extensions: RequestExtensions | None = ...) -> Response:
        """
        Send a `POST` request.

        **Parameters**: See `httpx.request`.
        """
        ...

    def put(self, url: URL | str, *, content: RequestContent | None = ..., data: RequestData | None = ..., files: RequestFiles | None = ..., json: typing.Any | None = ..., params: QueryParamTypes | None = ..., headers: HeaderTypes | None = ..., cookies: CookieTypes | None = ..., auth: AuthTypes | UseClientDefault = ..., follow_redirects: bool | UseClientDefault = ..., timeout: TimeoutTypes | UseClientDefault = ..., extensions: RequestExtensions | None = ...) -> Response:
        """
        Send a `PUT` request.

        **Parameters**: See `httpx.request`.
        """
        ...

    def patch(self, url: URL | str, *, content: RequestContent | None = ..., data: RequestData | None = ..., files: RequestFiles | None = ..., json: typing.Any | None = ..., params: QueryParamTypes | None = ..., headers: HeaderTypes | None = ..., cookies: CookieTypes | None = ..., auth: AuthTypes | UseClientDefault = ..., follow_redirects: bool | UseClientDefault = ..., timeout: TimeoutTypes | UseClientDefault = ..., extensions: RequestExtensions | None = ...) -> Response:
        """
        Send a `PATCH` request.

        **Parameters**: See `httpx.request`.
        """
        ...

    def delete(self, url: URL | str, *, params: QueryParamTypes | None = ..., headers: HeaderTypes | None = ..., cookies: CookieTypes | None = ..., auth: AuthTypes | UseClientDefault = ..., follow_redirects: bool | UseClientDefault = ..., timeout: TimeoutTypes | UseClientDefault = ..., extensions: RequestExtensions | None = ...) -> Response:
        """
        Send a `DELETE` request.

        **Parameters**: See `httpx.request`.
        """
        ...

    def close(self) -> None:
        """
        Close transport and proxies.
        """
        ...

    def __enter__(self: T) -> T:
        ...

    def __exit__(self, exc_type: type[BaseException] | None = ..., exc_value: BaseException | None = ..., traceback: TracebackType | None = ...) -> None:
        ...



class AsyncClient(BaseClient):
    """
    An asynchronous HTTP client, with connection pooling, HTTP/2, redirects,
    cookie persistence, etc.

    It can be shared between tasks.

    Usage:

    ```python
    >>> async with httpx.AsyncClient() as client:
    >>>     response = await client.get('https://example.org')
    ```

    **Parameters:**

    * **auth** - *(optional)* An authentication class to use when sending
    requests.
    * **params** - *(optional)* Query parameters to include in request URLs, as
    a string, dictionary, or sequence of two-tuples.
    * **headers** - *(optional)* Dictionary of HTTP headers to include when
    sending requests.
    * **cookies** - *(optional)* Dictionary of Cookie items to include when
    sending requests.
    * **verify** - *(optional)* Either `True` to use an SSL context with the
    default CA bundle, `False` to disable verification, or an instance of
    `ssl.SSLContext` to use a custom context.
    * **http2** - *(optional)* A boolean indicating if HTTP/2 support should be
    enabled. Defaults to `False`.
    * **proxy** - *(optional)* A proxy URL where all the traffic should be routed.
    * **timeout** - *(optional)* The timeout configuration to use when sending
    requests.
    * **limits** - *(optional)* The limits configuration to use.
    * **max_redirects** - *(optional)* The maximum number of redirect responses
    that should be followed.
    * **base_url** - *(optional)* A URL to use as the base when building
    request URLs.
    * **transport** - *(optional)* A transport class to use for sending requests
    over the network.
    * **trust_env** - *(optional)* Enables or disables usage of environment
    variables for configuration.
    * **default_encoding** - *(optional)* The default encoding to use for decoding
    response text, if no charset information is included in a response Content-Type
    header. Set to a callable for automatic character set detection. Default: "utf-8".
    """
    def __init__(self, *, auth: AuthTypes | None = ..., params: QueryParamTypes | None = ..., headers: HeaderTypes | None = ..., cookies: CookieTypes | None = ..., verify: ssl.SSLContext | str | bool = ..., cert: CertTypes | None = ..., http1: bool = ..., http2: bool = ..., proxy: ProxyTypes | None = ..., mounts: None | typing.Mapping[str, AsyncBaseTransport | None] = ..., timeout: TimeoutTypes = ..., follow_redirects: bool = ..., limits: Limits = ..., max_redirects: int = ..., event_hooks: None | typing.Mapping[str, list[EventHook]] = ..., base_url: URL | str = ..., transport: AsyncBaseTransport | None = ..., trust_env: bool = ..., default_encoding: str | typing.Callable[[bytes], str] = ...) -> None:
        ...

    async def request(self, method: str, url: URL | str, *, content: RequestContent | None = ..., data: RequestData | None = ..., files: RequestFiles | None = ..., json: typing.Any | None = ..., params: QueryParamTypes | None = ..., headers: HeaderTypes | None = ..., cookies: CookieTypes | None = ..., auth: AuthTypes | UseClientDefault | None = ..., follow_redirects: bool | UseClientDefault = ..., timeout: TimeoutTypes | UseClientDefault = ..., extensions: RequestExtensions | None = ...) -> Response:
        """
        Build and send a request.

        Equivalent to:

        ```python
        request = client.build_request(...)
        response = await client.send(request, ...)
        ```

        See `AsyncClient.build_request()`, `AsyncClient.send()`
        and [Merging of configuration][0] for how the various parameters
        are merged with client-level configuration.

        [0]: /advanced/clients/#merging-of-configuration
        """
        ...

    @asynccontextmanager
    async def stream(self, method: str, url: URL | str, *, content: RequestContent | None = ..., data: RequestData | None = ..., files: RequestFiles | None = ..., json: typing.Any | None = ..., params: QueryParamTypes | None = ..., headers: HeaderTypes | None = ..., cookies: CookieTypes | None = ..., auth: AuthTypes | UseClientDefault | None = ..., follow_redirects: bool | UseClientDefault = ..., timeout: TimeoutTypes | UseClientDefault = ..., extensions: RequestExtensions | None = ...) -> typing.AsyncIterator[Response]:
        """
        Alternative to `httpx.request()` that streams the response body
        instead of loading it into memory at once.

        **Parameters**: See `httpx.request`.

        See also: [Streaming Responses][0]

        [0]: /quickstart#streaming-responses
        """
        ...

    async def send(self, request: Request, *, stream: bool = ..., auth: AuthTypes | UseClientDefault | None = ..., follow_redirects: bool | UseClientDefault = ...) -> Response:
        """
        Send a request.

        The request is sent as-is, unmodified.

        Typically you'll want to build one with `AsyncClient.build_request()`
        so that any client-level configuration is merged into the request,
        but passing an explicit `httpx.Request()` is supported as well.

        See also: [Request instances][0]

        [0]: /advanced/clients/#request-instances
        """
        ...

    async def get(self, url: URL | str, *, params: QueryParamTypes | None = ..., headers: HeaderTypes | None = ..., cookies: CookieTypes | None = ..., auth: AuthTypes | UseClientDefault | None = ..., follow_redirects: bool | UseClientDefault = ..., timeout: TimeoutTypes | UseClientDefault = ..., extensions: RequestExtensions | None = ...) -> Response:
        """
        Send a `GET` request.

        **Parameters**: See `httpx.request`.
        """
        ...

    async def options(self, url: URL | str, *, params: QueryParamTypes | None = ..., headers: HeaderTypes | None = ..., cookies: CookieTypes | None = ..., auth: AuthTypes | UseClientDefault = ..., follow_redirects: bool | UseClientDefault = ..., timeout: TimeoutTypes | UseClientDefault = ..., extensions: RequestExtensions | None = ...) -> Response:
        """
        Send an `OPTIONS` request.

        **Parameters**: See `httpx.request`.
        """
        ...

    async def head(self, url: URL | str, *, params: QueryParamTypes | None = ..., headers: HeaderTypes | None = ..., cookies: CookieTypes | None = ..., auth: AuthTypes | UseClientDefault = ..., follow_redirects: bool | UseClientDefault = ..., timeout: TimeoutTypes | UseClientDefault = ..., extensions: RequestExtensions | None = ...) -> Response:
        """
        Send a `HEAD` request.

        **Parameters**: See `httpx.request`.
        """
        ...

    async def post(self, url: URL | str, *, content: RequestContent | None = ..., data: RequestData | None = ..., files: RequestFiles | None = ..., json: typing.Any | None = ..., params: QueryParamTypes | None = ..., headers: HeaderTypes | None = ..., cookies: CookieTypes | None = ..., auth: AuthTypes | UseClientDefault = ..., follow_redirects: bool | UseClientDefault = ..., timeout: TimeoutTypes | UseClientDefault = ..., extensions: RequestExtensions | None = ...) -> Response:
        """
        Send a `POST` request.

        **Parameters**: See `httpx.request`.
        """
        ...

    async def put(self, url: URL | str, *, content: RequestContent | None = ..., data: RequestData | None = ..., files: RequestFiles | None = ..., json: typing.Any | None = ..., params: QueryParamTypes | None = ..., headers: HeaderTypes | None = ..., cookies: CookieTypes | None = ..., auth: AuthTypes | UseClientDefault = ..., follow_redirects: bool | UseClientDefault = ..., timeout: TimeoutTypes | UseClientDefault = ..., extensions: RequestExtensions | None = ...) -> Response:
        """
        Send a `PUT` request.

        **Parameters**: See `httpx.request`.
        """
        ...

    async def patch(self, url: URL | str, *, content: RequestContent | None = ..., data: RequestData | None = ..., files: RequestFiles | None = ..., json: typing.Any | None = ..., params: QueryParamTypes | None = ..., headers: HeaderTypes | None = ..., cookies: CookieTypes | None = ..., auth: AuthTypes | UseClientDefault = ..., follow_redirects: bool | UseClientDefault = ..., timeout: TimeoutTypes | UseClientDefault = ..., extensions: RequestExtensions | None = ...) -> Response:
        """
        Send a `PATCH` request.

        **Parameters**: See `httpx.request`.
        """
        ...

    async def delete(self, url: URL | str, *, params: QueryParamTypes | None = ..., headers: HeaderTypes | None = ..., cookies: CookieTypes | None = ..., auth: AuthTypes | UseClientDefault = ..., follow_redirects: bool | UseClientDefault = ..., timeout: TimeoutTypes | UseClientDefault = ..., extensions: RequestExtensions | None = ...) -> Response:
        """
        Send a `DELETE` request.

        **Parameters**: See `httpx.request`.
        """
        ...

    async def aclose(self) -> None:
        """
        Close transport and proxies.
        """
        ...

    async def __aenter__(self: U) -> U:
        ...

    async def __aexit__(self, exc_type: type[BaseException] | None = ..., exc_value: BaseException | None = ..., traceback: TracebackType | None = ...) -> None:
        ...
