"""
This type stub file was generated by pyright.
"""

import typing
import ssl
from ._types import CertTypes, HeaderTypes, TimeoutTypes
from ._urls import URL

if typing.TYPE_CHECKING:
    ...
__all__ = ["Limits", "Proxy", "Timeout", "create_ssl_context"]
class UnsetType:
    ...


UNSET = ...
def create_ssl_context(verify: ssl.SSLContext | str | bool = ..., cert: CertTypes | None = ..., trust_env: bool = ...) -> ssl.SSLContext:
    ...

class Timeout:
    """
    Timeout configuration.

    **Usage**:

    Timeout(None)               # No timeouts.
    Timeout(5.0)                # 5s timeout on all operations.
    Timeout(None, connect=5.0)  # 5s timeout on connect, no other timeouts.
    Timeout(5.0, connect=10.0)  # 10s timeout on connect. 5s timeout elsewhere.
    Timeout(5.0, pool=None)     # No timeout on acquiring connection from pool.
                                # 5s timeout elsewhere.
    """
    def __init__(self, timeout: TimeoutTypes | UnsetType = ..., *, connect: None | float | UnsetType = ..., read: None | float | UnsetType = ..., write: None | float | UnsetType = ..., pool: None | float | UnsetType = ...) -> None:
        ...

    def as_dict(self) -> dict[str, float | None]:
        ...

    def __eq__(self, other: typing.Any) -> bool:
        ...

    def __repr__(self) -> str:
        ...



class Limits:
    """
    Configuration for limits to various client behaviors.

    **Parameters:**

    * **max_connections** - The maximum number of concurrent connections that may be
            established.
    * **max_keepalive_connections** - Allow the connection pool to maintain
            keep-alive connections below this point. Should be less than or equal
            to `max_connections`.
    * **keepalive_expiry** - Time limit on idle keep-alive connections in seconds.
    """
    def __init__(self, *, max_connections: int | None = ..., max_keepalive_connections: int | None = ..., keepalive_expiry: float | None = ...) -> None:
        ...

    def __eq__(self, other: typing.Any) -> bool:
        ...

    def __repr__(self) -> str:
        ...



class Proxy:
    def __init__(self, url: URL | str, *, ssl_context: ssl.SSLContext | None = ..., auth: tuple[str, str] | None = ..., headers: HeaderTypes | None = ...) -> None:
        ...

    @property
    def raw_auth(self) -> tuple[bytes, bytes] | None:
        ...

    def __repr__(self) -> str:
        ...



DEFAULT_TIMEOUT_CONFIG = ...
DEFAULT_LIMITS = ...
DEFAULT_MAX_REDIRECTS = ...
