"""
This type stub file was generated by pyright.
"""

import typing
from ._types import PrimitiveData
from ._urls import URL

if typing.TYPE_CHECKING:
    ...
def primitive_value_to_str(value: PrimitiveData) -> str:
    """
    Coerce a primitive data type into a string value.

    Note that we prefer JSON-style 'true'/'false' for boolean values here.
    """
    ...

def get_environment_proxies() -> dict[str, str | None]:
    """Gets proxy information from the environment"""
    ...

def to_bytes(value: str | bytes, encoding: str = ...) -> bytes:
    ...

def to_str(value: str | bytes, encoding: str = ...) -> str:
    ...

def to_bytes_or_str(value: str, match_type_of: typing.AnyStr) -> typing.AnyStr:
    ...

def unquote(value: str) -> str:
    ...

def peek_filelike_length(stream: typing.Any) -> int | None:
    """
    Given a file-like stream object, return its length in number of bytes
    without reading it into memory.
    """
    ...

class URLPattern:
    """
    A utility class currently used for making lookups against proxy keys...

    # Wildcard matching...
    >>> pattern = URLPattern("all://")
    >>> pattern.matches(httpx.URL("http://example.com"))
    True

    # Witch scheme matching...
    >>> pattern = URLPattern("https://")
    >>> pattern.matches(httpx.URL("https://example.com"))
    True
    >>> pattern.matches(httpx.URL("http://example.com"))
    False

    # With domain matching...
    >>> pattern = URLPattern("https://example.com")
    >>> pattern.matches(httpx.URL("https://example.com"))
    True
    >>> pattern.matches(httpx.URL("http://example.com"))
    False
    >>> pattern.matches(httpx.URL("https://other.com"))
    False

    # Wildcard scheme, with domain matching...
    >>> pattern = URLPattern("all://example.com")
    >>> pattern.matches(httpx.URL("https://example.com"))
    True
    >>> pattern.matches(httpx.URL("http://example.com"))
    True
    >>> pattern.matches(httpx.URL("https://other.com"))
    False

    # With port matching...
    >>> pattern = URLPattern("https://example.com:1234")
    >>> pattern.matches(httpx.URL("https://example.com:1234"))
    True
    >>> pattern.matches(httpx.URL("https://example.com"))
    False
    """
    def __init__(self, pattern: str) -> None:
        ...

    def matches(self, other: URL) -> bool:
        ...

    @property
    def priority(self) -> tuple[int, int, int]:
        """
        The priority allows URLPattern instances to be sortable, so that
        we can match from most specific to least specific.
        """
        ...

    def __hash__(self) -> int:
        ...

    def __lt__(self, other: URLPattern) -> bool:
        ...

    def __eq__(self, other: typing.Any) -> bool:
        ...



def is_ipv4_hostname(hostname: str) -> bool:
    ...

def is_ipv6_hostname(hostname: str) -> bool:
    ...
