"""
This type stub file was generated by pyright.
"""

import typing
import ssl
from contextlib import contextmanager
from ._models import Response
from ._types import AuthTypes, CookieTypes, HeaderTypes, ProxyTypes, QueryParamTypes, RequestContent, RequestData, RequestFiles, TimeoutTypes
from ._urls import URL

if typing.TYPE_CHECKING:
    ...
__all__ = ["delete", "get", "head", "options", "patch", "post", "put", "request", "stream"]
def request(method: str, url: URL | str, *, params: QueryParamTypes | None = ..., content: RequestContent | None = ..., data: RequestData | None = ..., files: RequestFiles | None = ..., json: typing.Any | None = ..., headers: HeaderTypes | None = ..., cookies: CookieTypes | None = ..., auth: AuthTypes | None = ..., proxy: ProxyTypes | None = ..., timeout: TimeoutTypes = ..., follow_redirects: bool = ..., verify: ssl.SSLContext | str | bool = ..., trust_env: bool = ...) -> Response:
    """
    Sends an HTTP request.

    **Parameters:**

    * **method** - HTTP method for the new `Request` object: `GET`, `OPTIONS`,
    `HEAD`, `POST`, `PUT`, `PATCH`, or `DELETE`.
    * **url** - URL for the new `Request` object.
    * **params** - *(optional)* Query parameters to include in the URL, as a
    string, dictionary, or sequence of two-tuples.
    * **content** - *(optional)* Binary content to include in the body of the
    request, as bytes or a byte iterator.
    * **data** - *(optional)* Form data to include in the body of the request,
    as a dictionary.
    * **files** - *(optional)* A dictionary of upload files to include in the
    body of the request.
    * **json** - *(optional)* A JSON serializable object to include in the body
    of the request.
    * **headers** - *(optional)* Dictionary of HTTP headers to include in the
    request.
    * **cookies** - *(optional)* Dictionary of Cookie items to include in the
    request.
    * **auth** - *(optional)* An authentication class to use when sending the
    request.
    * **proxy** - *(optional)* A proxy URL where all the traffic should be routed.
    * **timeout** - *(optional)* The timeout configuration to use when sending
    the request.
    * **follow_redirects** - *(optional)* Enables or disables HTTP redirects.
    * **verify** - *(optional)* Either `True` to use an SSL context with the
    default CA bundle, `False` to disable verification, or an instance of
    `ssl.SSLContext` to use a custom context.
    * **trust_env** - *(optional)* Enables or disables usage of environment
    variables for configuration.

    **Returns:** `Response`

    Usage:

    ```
    >>> import httpx
    >>> response = httpx.request('GET', 'https://httpbin.org/get')
    >>> response
    <Response [200 OK]>
    ```
    """
    ...

@contextmanager
def stream(method: str, url: URL | str, *, params: QueryParamTypes | None = ..., content: RequestContent | None = ..., data: RequestData | None = ..., files: RequestFiles | None = ..., json: typing.Any | None = ..., headers: HeaderTypes | None = ..., cookies: CookieTypes | None = ..., auth: AuthTypes | None = ..., proxy: ProxyTypes | None = ..., timeout: TimeoutTypes = ..., follow_redirects: bool = ..., verify: ssl.SSLContext | str | bool = ..., trust_env: bool = ...) -> typing.Iterator[Response]:
    """
    Alternative to `httpx.request()` that streams the response body
    instead of loading it into memory at once.

    **Parameters**: See `httpx.request`.

    See also: [Streaming Responses][0]

    [0]: /quickstart#streaming-responses
    """
    ...

def get(url: URL | str, *, params: QueryParamTypes | None = ..., headers: HeaderTypes | None = ..., cookies: CookieTypes | None = ..., auth: AuthTypes | None = ..., proxy: ProxyTypes | None = ..., follow_redirects: bool = ..., verify: ssl.SSLContext | str | bool = ..., timeout: TimeoutTypes = ..., trust_env: bool = ...) -> Response:
    """
    Sends a `GET` request.

    **Parameters**: See `httpx.request`.

    Note that the `data`, `files`, `json` and `content` parameters are not available
    on this function, as `GET` requests should not include a request body.
    """
    ...

def options(url: URL | str, *, params: QueryParamTypes | None = ..., headers: HeaderTypes | None = ..., cookies: CookieTypes | None = ..., auth: AuthTypes | None = ..., proxy: ProxyTypes | None = ..., follow_redirects: bool = ..., verify: ssl.SSLContext | str | bool = ..., timeout: TimeoutTypes = ..., trust_env: bool = ...) -> Response:
    """
    Sends an `OPTIONS` request.

    **Parameters**: See `httpx.request`.

    Note that the `data`, `files`, `json` and `content` parameters are not available
    on this function, as `OPTIONS` requests should not include a request body.
    """
    ...

def head(url: URL | str, *, params: QueryParamTypes | None = ..., headers: HeaderTypes | None = ..., cookies: CookieTypes | None = ..., auth: AuthTypes | None = ..., proxy: ProxyTypes | None = ..., follow_redirects: bool = ..., verify: ssl.SSLContext | str | bool = ..., timeout: TimeoutTypes = ..., trust_env: bool = ...) -> Response:
    """
    Sends a `HEAD` request.

    **Parameters**: See `httpx.request`.

    Note that the `data`, `files`, `json` and `content` parameters are not available
    on this function, as `HEAD` requests should not include a request body.
    """
    ...

def post(url: URL | str, *, content: RequestContent | None = ..., data: RequestData | None = ..., files: RequestFiles | None = ..., json: typing.Any | None = ..., params: QueryParamTypes | None = ..., headers: HeaderTypes | None = ..., cookies: CookieTypes | None = ..., auth: AuthTypes | None = ..., proxy: ProxyTypes | None = ..., follow_redirects: bool = ..., verify: ssl.SSLContext | str | bool = ..., timeout: TimeoutTypes = ..., trust_env: bool = ...) -> Response:
    """
    Sends a `POST` request.

    **Parameters**: See `httpx.request`.
    """
    ...

def put(url: URL | str, *, content: RequestContent | None = ..., data: RequestData | None = ..., files: RequestFiles | None = ..., json: typing.Any | None = ..., params: QueryParamTypes | None = ..., headers: HeaderTypes | None = ..., cookies: CookieTypes | None = ..., auth: AuthTypes | None = ..., proxy: ProxyTypes | None = ..., follow_redirects: bool = ..., verify: ssl.SSLContext | str | bool = ..., timeout: TimeoutTypes = ..., trust_env: bool = ...) -> Response:
    """
    Sends a `PUT` request.

    **Parameters**: See `httpx.request`.
    """
    ...

def patch(url: URL | str, *, content: RequestContent | None = ..., data: RequestData | None = ..., files: RequestFiles | None = ..., json: typing.Any | None = ..., params: QueryParamTypes | None = ..., headers: HeaderTypes | None = ..., cookies: CookieTypes | None = ..., auth: AuthTypes | None = ..., proxy: ProxyTypes | None = ..., follow_redirects: bool = ..., verify: ssl.SSLContext | str | bool = ..., timeout: TimeoutTypes = ..., trust_env: bool = ...) -> Response:
    """
    Sends a `PATCH` request.

    **Parameters**: See `httpx.request`.
    """
    ...

def delete(url: URL | str, *, params: QueryParamTypes | None = ..., headers: HeaderTypes | None = ..., cookies: CookieTypes | None = ..., auth: AuthTypes | None = ..., proxy: ProxyTypes | None = ..., follow_redirects: bool = ..., timeout: TimeoutTypes = ..., verify: ssl.SSLContext | str | bool = ..., trust_env: bool = ...) -> Response:
    """
    Sends a `DELETE` request.

    **Parameters**: See `httpx.request`.

    Note that the `data`, `files`, `json` and `content` parameters are not available
    on this function, as `DELETE` requests should not include a request body.
    """
    ...
