"""
This type stub file was generated by pyright.
"""

import typing
from ._models import Request, Response
from hashlib import _Hash

if typing.TYPE_CHECKING:
    ...
__all__ = ["Auth", "BasicAuth", "DigestAuth", "NetRCAuth"]
class Auth:
    """
    Base class for all authentication schemes.

    To implement a custom authentication scheme, subclass `Auth` and override
    the `.auth_flow()` method.

    If the authentication scheme does I/O such as disk access or network calls, or uses
    synchronization primitives such as locks, you should override `.sync_auth_flow()`
    and/or `.async_auth_flow()` instead of `.auth_flow()` to provide specialized
    implementations that will be used by `Client` and `AsyncClient` respectively.
    """
    requires_request_body = ...
    requires_response_body = ...
    def auth_flow(self, request: Request) -> typing.Generator[Request, Response, None]:
        """
        Execute the authentication flow.

        To dispatch a request, `yield` it:

        ```
        yield request
        ```

        The client will `.send()` the response back into the flow generator. You can
        access it like so:

        ```
        response = yield request
        ```

        A `return` (or reaching the end of the generator) will result in the
        client returning the last response obtained from the server.

        You can dispatch as many requests as is necessary.
        """
        ...

    def sync_auth_flow(self, request: Request) -> typing.Generator[Request, Response, None]:
        """
        Execute the authentication flow synchronously.

        By default, this defers to `.auth_flow()`. You should override this method
        when the authentication scheme does I/O and/or uses concurrency primitives.
        """
        ...

    async def async_auth_flow(self, request: Request) -> typing.AsyncGenerator[Request, Response]:
        """
        Execute the authentication flow asynchronously.

        By default, this defers to `.auth_flow()`. You should override this method
        when the authentication scheme does I/O and/or uses concurrency primitives.
        """
        ...



class FunctionAuth(Auth):
    """
    Allows the 'auth' argument to be passed as a simple callable function,
    that takes the request, and returns a new, modified request.
    """
    def __init__(self, func: typing.Callable[[Request], Request]) -> None:
        ...

    def auth_flow(self, request: Request) -> typing.Generator[Request, Response, None]:
        ...



class BasicAuth(Auth):
    """
    Allows the 'auth' argument to be passed as a (username, password) pair,
    and uses HTTP Basic authentication.
    """
    def __init__(self, username: str | bytes, password: str | bytes) -> None:
        ...

    def auth_flow(self, request: Request) -> typing.Generator[Request, Response, None]:
        ...



class NetRCAuth(Auth):
    """
    Use a 'netrc' file to lookup basic auth credentials based on the url host.
    """
    def __init__(self, file: str | None = ...) -> None:
        ...

    def auth_flow(self, request: Request) -> typing.Generator[Request, Response, None]:
        ...



class DigestAuth(Auth):
    _ALGORITHM_TO_HASH_FUNCTION: dict[str, typing.Callable[[bytes], _Hash]] = ...
    def __init__(self, username: str | bytes, password: str | bytes) -> None:
        ...

    def auth_flow(self, request: Request) -> typing.Generator[Request, Response, None]:
        ...



class _DigestAuthChallenge(typing.NamedTuple):
    realm: bytes
    nonce: bytes
    algorithm: str
    opaque: bytes | None
    qop: bytes | None
    ...
