"""
This type stub file was generated by pyright.
"""

from typing import Any, AsyncIterable, AsyncIterator, Iterable, Iterator
from ._multipart import MultipartStream
from ._types import AsyncByteStream, RequestContent, RequestData, RequestFiles, ResponseContent, SyncByteStream

__all__ = ["ByteStream"]
class ByteStream(AsyncByteStream, SyncByteStream):
    def __init__(self, stream: bytes) -> None:
        ...

    def __iter__(self) -> Iterator[bytes]:
        ...

    async def __aiter__(self) -> AsyncIterator[bytes]:
        ...



class IteratorByteStream(SyncByteStream):
    CHUNK_SIZE = ...
    def __init__(self, stream: Iterable[bytes]) -> None:
        ...

    def __iter__(self) -> Iterator[bytes]:
        ...



class AsyncIteratorByteStream(AsyncByteStream):
    CHUNK_SIZE = ...
    def __init__(self, stream: AsyncIterable[bytes]) -> None:
        ...

    async def __aiter__(self) -> AsyncIterator[bytes]:
        ...



class UnattachedStream(AsyncByteStream, SyncByteStream):
    """
    If a request or response is serialized using pickle, then it is no longer
    attached to a stream for I/O purposes. Any stream operations should result
    in `httpx.StreamClosed`.
    """
    def __iter__(self) -> Iterator[bytes]:
        ...

    async def __aiter__(self) -> AsyncIterator[bytes]:
        ...



def encode_content(content: str | bytes | Iterable[bytes] | AsyncIterable[bytes]) -> tuple[dict[str, str], SyncByteStream | AsyncByteStream]:
    ...

def encode_urlencoded_data(data: RequestData) -> tuple[dict[str, str], ByteStream]:
    ...

def encode_multipart_data(data: RequestData, files: RequestFiles, boundary: bytes | None) -> tuple[dict[str, str], MultipartStream]:
    ...

def encode_text(text: str) -> tuple[dict[str, str], ByteStream]:
    ...

def encode_html(html: str) -> tuple[dict[str, str], ByteStream]:
    ...

def encode_json(json: Any) -> tuple[dict[str, str], ByteStream]:
    ...

def encode_request(content: RequestContent | None = ..., data: RequestData | None = ..., files: RequestFiles | None = ..., json: Any | None = ..., boundary: bytes | None = ...) -> tuple[dict[str, str], SyncByteStream | AsyncByteStream]:
    """
    Handles encoding the given `content`, `data`, `files`, and `json`,
    returning a two-tuple of (<headers>, <stream>).
    """
    ...

def encode_response(content: ResponseContent | None = ..., text: str | None = ..., html: str | None = ..., json: Any | None = ...) -> tuple[dict[str, str], SyncByteStream | AsyncByteStream]:
    """
    Handles encoding the given `content`, returning a two-tuple of
    (<headers>, <stream>).
    """
    ...
