"""
This type stub file was generated by pyright.
"""

import typing
import click
import httpcore
from ._models import Response

if typing.TYPE_CHECKING:
    ...
def print_help() -> None:
    ...

def get_lexer_for_response(response: Response) -> str:
    ...

def format_request_headers(request: httpcore.Request, http2: bool = ...) -> str:
    ...

def format_response_headers(http_version: bytes, status: int, reason_phrase: bytes | None, headers: list[tuple[bytes, bytes]]) -> str:
    ...

def print_request_headers(request: httpcore.Request, http2: bool = ...) -> None:
    ...

def print_response_headers(http_version: bytes, status: int, reason_phrase: bytes | None, headers: list[tuple[bytes, bytes]]) -> None:
    ...

def print_response(response: Response) -> None:
    ...

_PCTRTT = typing.Tuple[typing.Tuple[str, str], ...]
_PCTRTTT = typing.Tuple[_PCTRTT, ...]
_PeerCertRetDictType = typing.Dict[str, typing.Union[str, _PCTRTTT, _PCTRTT]]
def format_certificate(cert: _PeerCertRetDictType) -> str:
    ...

def trace(name: str, info: typing.Mapping[str, typing.Any], verbose: bool = ...) -> None:
    ...

def download_response(response: Response, download: typing.BinaryIO) -> None:
    ...

def validate_json(ctx: click.Context, param: click.Option | click.Parameter, value: typing.Any) -> typing.Any:
    ...

def validate_auth(ctx: click.Context, param: click.Option | click.Parameter, value: typing.Any) -> typing.Any:
    ...

def handle_help(ctx: click.Context, param: click.Option | click.Parameter, value: typing.Any) -> None:
    ...

@click.command(add_help_option=False)
@click.argument("url", type=str)
@click.option("--method", "-m", "method", type=str, help="Request method, such as GET, POST, PUT, PATCH, DELETE, OPTIONS, HEAD. " "[Default: GET, or POST if a request body is included]")
@click.option("--params", "-p", "params", type=(str, str), multiple=True, help="Query parameters to include in the request URL.")
@click.option("--content", "-c", "content", type=str, help="Byte content to include in the request body.")
@click.option("--data", "-d", "data", type=(str, str), multiple=True, help="Form data to include in the request body.")
@click.option("--files", "-f", "files", type=(str, click.File(mode="rb")), multiple=True, help="Form files to include in the request body.")
@click.option("--json", "-j", "json", type=str, callback=validate_json, help="JSON data to include in the request body.")
@click.option("--headers", "-h", "headers", type=(str, str), multiple=True, help="Include additional HTTP headers in the request.")
@click.option("--cookies", "cookies", type=(str, str), multiple=True, help="Cookies to include in the request.")
@click.option("--auth", "auth", type=(str, str), default=(None, None), callback=validate_auth, help="Username and password to include in the request. " "Specify '-' for the password to use a password prompt. " "Note that using --verbose/-v will expose the Authorization header, " "including the password encoding in a trivially reversible format.")
@click.option("--proxy", "proxy", type=str, default=None, help="Send the request via a proxy. Should be the URL giving the proxy address.")
@click.option("--timeout", "timeout", type=float, default=5, help="Timeout value to use for network operations, such as establishing the " "connection, reading some data, etc... [Default: 5.0]")
@click.option("--follow-redirects", "follow_redirects", is_flag=True, default=False, help="Automatically follow redirects.")
@click.option("--no-verify", "verify", is_flag=True, default=True, help="Disable SSL verification.")
@click.option("--http2", "http2", type=bool, is_flag=True, default=False, help="Send the request using HTTP/2, if the remote server supports it.")
@click.option("--download", type=click.File("wb"), help="Save the response content as a file, rather than displaying it.")
@click.option("--verbose", "-v", type=bool, is_flag=True, default=False, help="Verbose. Show request as well as response.")
@click.option("--help", is_flag=True, is_eager=True, expose_value=False, callback=handle_help, help="Show this message and exit.")
def main(url: str, method: str, params: list[tuple[str, str]], content: str, data: list[tuple[str, str]], files: list[tuple[str, click.File]], json: str, headers: list[tuple[str, str]], cookies: list[tuple[str, str]], auth: tuple[str, str] | None, proxy: str, timeout: float, follow_redirects: bool, verify: bool, http2: bool, download: typing.BinaryIO | None, verbose: bool) -> None:
    """
    An HTTP command line client.
    Sends a request and displays the response.
    """
    ...
