"""
This type stub file was generated by pyright.
"""

import typing
from ._types import AsyncByteStream, FileTypes, RequestData, RequestFiles, SyncByteStream

_HTML5_FORM_ENCODING_REPLACEMENTS = ...
_HTML5_FORM_ENCODING_RE = ...
def get_multipart_boundary_from_content_type(content_type: bytes | None) -> bytes | None:
    ...

class DataField:
    """
    A single form field item, within a multipart form field.
    """
    def __init__(self, name: str, value: str | bytes | int | float | None) -> None:
        ...

    def render_headers(self) -> bytes:
        ...

    def render_data(self) -> bytes:
        ...

    def get_length(self) -> int:
        ...

    def render(self) -> typing.Iterator[bytes]:
        ...



class FileField:
    """
    A single file field item, within a multipart form field.
    """
    CHUNK_SIZE = ...
    def __init__(self, name: str, value: FileTypes) -> None:
        ...

    def get_length(self) -> int | None:
        ...

    def render_headers(self) -> bytes:
        ...

    def render_data(self) -> typing.Iterator[bytes]:
        ...

    def render(self) -> typing.Iterator[bytes]:
        ...



class MultipartStream(SyncByteStream, AsyncByteStream):
    """
    Request content as streaming multipart encoded form data.
    """
    def __init__(self, data: RequestData, files: RequestFiles, boundary: bytes | None = ...) -> None:
        ...

    def iter_chunks(self) -> typing.Iterator[bytes]:
        ...

    def get_content_length(self) -> int | None:
        """
        Return the length of the multipart encoded content, or `None` if
        any of the files have a length that cannot be determined upfront.
        """
        ...

    def get_headers(self) -> dict[str, str]:
        ...

    def __iter__(self) -> typing.Iterator[bytes]:
        ...

    async def __aiter__(self) -> typing.AsyncIterator[bytes]:
        ...
