"""
This type stub file was generated by pyright.
"""

from typing import Any

"""
This type stub file was generated by pyright.
"""
class GreenThreadLocal:
    """
    threading.local() replacement for greenlets.
    """
    def __init__(self) -> None:
        ...

    def __getattr__(self, name: str) -> Any:
        ...

    def __setattr__(self, name: str, val: Any) -> None:
        ...

    def __delattr__(self, name: str) -> None:
        ...
