"""
This type stub file was generated by pyright.
"""

from typing import Any, MutableMapping, Protocol, Sequence, Tuple

"""
Type definitions for structlog.
"""

EventDict = MutableMapping[str, Any]
Context = MutableMapping[str, Any]
ExcInfo = Tuple[type[BaseException], BaseException, Any] | Tuple[None, None, None]

class WrappedLogger(Protocol):
    """Protocol for wrapped logger instances."""
    def log(self, level: int | str, event: str, **kw: Any) -> Any: ...
    def debug(self, event: str, **kw: Any) -> Any: ...
    def info(self, event: str, **kw: Any) -> Any: ...
    def warning(self, event: str, **kw: Any) -> Any: ...
    def error(self, event: str, **kw: Any) -> Any: ...
    def critical(self, event: str, **kw: Any) -> Any: ...

class Processor(Protocol):
    """Protocol for structlog processors."""
    def __call__(
        self,
        logger: WrappedLogger,
        method_name: str,
        event_dict: EventDict,
    ) -> EventDict: ...

class BindableLogger(Protocol):
    """Protocol for bindable logger."""
    def bind(self, **new_values: Any) -> Any: ...
    def unbind(self, *keys: str) -> Any: ...
    def try_unbind(self, *keys: str) -> Any: ...
    def new(self, **new_values: Any) -> Any: ...

class FilteringBoundLogger(Protocol):
    """Protocol for filtering bound logger."""
    def bind(self, **new_values: Any) -> Any: ...
    def unbind(self, *keys: str) -> Any: ...

class ExceptionRenderer(Protocol):
    """Protocol for exception rendering."""
    def __call__(self, exc_info: ExcInfo) -> str: ...

class ExceptionTransformer(Protocol):
    """Protocol for exception transformation."""
    def __call__(self, exc_info: ExcInfo) -> ExcInfo: ...

__all__ = (
    "BindableLogger",
    "Context",
    "EventDict",
    "ExcInfo",
    "ExceptionRenderer",
    "ExceptionTransformer",
    "FilteringBoundLogger",
    "Processor",
    "WrappedLogger",
)
