"""AuthService — 登録・ログインフローのオーケストレーション。"""

from __future__ import annotations

import re
import secrets
from datetime import UTC, datetime
from typing import TYPE_CHECKING

import structlog

from osu_server.domain.auth import (
    LoginResponse,
    LoginResult,
    RegistrationForm,
    RegistrationResult,
)
from osu_server.domain.session import SessionData
from osu_server.domain.user import User

if TYPE_CHECKING:
    from osu_server.domain.auth import LoginRequest
    from osu_server.repositories.interfaces.role_repository import RoleRepository
    from osu_server.repositories.interfaces.session_store import SessionStore
    from osu_server.repositories.interfaces.user_repository import UserRepository
    from osu_server.services.password_service import PasswordService
    from osu_server.services.permission_service import PermissionService

logger: structlog.stdlib.BoundLogger = structlog.get_logger(__name__)  # pyright: ignore[reportAny]

# ── Validation constants ─────────────────────────────────────────────

_USERNAME_MIN = 2
_USERNAME_MAX = 15
_USERNAME_PATTERN = re.compile(r"^[a-zA-Z0-9_ -]+$")

_PASSWORD_MIN = 8
_PASSWORD_MAX = 32
_PASSWORD_UNIQUE_MIN = 4

_EMAIL_PATTERN = re.compile(r"^[^@\s]{1,200}@[^@\s.]{1,30}\.[^@.\s]{1,24}$")

_MSG_USERNAME_CHARS = (
    "Username may only contain alphanumeric characters, spaces, underscores, and hyphens."
)
_MSG_PASSWORD_COMPROMISED = (
    "This password has been compromised in a data breach. Please choose a different password."
)


class AuthService:
    """ログイン/登録オーケストレーション。

    register() はバリデーション → 重複チェック → HIBP → (check_only なら終了)
    → パスワードハッシュ → ユーザー作成 → デフォルトロール付与の順で処理する。
    """

    _user_repo: UserRepository
    _role_repo: RoleRepository
    _password_service: PasswordService
    _permission_service: PermissionService
    _session_store: SessionStore

    def __init__(
        self,
        user_repo: UserRepository,
        role_repo: RoleRepository,
        password_service: PasswordService,
        permission_service: PermissionService,
        session_store: SessionStore,
    ) -> None:
        self._user_repo = user_repo
        self._role_repo = role_repo
        self._password_service = password_service
        self._permission_service = permission_service
        self._session_store = session_store

    # ── Public API ───────────────────────────────────────────────────

    async def register(
        self,
        form_data: RegistrationForm,
        check_only: bool = False,
    ) -> RegistrationResult:
        """アカウント登録を実行する。

        全バリデーションエラーを蓄積して返却する(最初のエラーで中断しない)。
        check_only=True の場合はバリデーションのみ実行し、アカウントは作成しない。
        """
        errors: dict[str, list[str]] = {}

        # Phase 1: Format validation (synchronous, no I/O)
        self._validate_username_format(form_data.username, errors)
        self._validate_password_format(form_data.password, errors)
        self._validate_email_format(form_data.email, errors)

        # Phase 2: Uniqueness / disallowed checks (I/O)
        safe_username = User.normalize_username(form_data.username)
        await self._check_username_availability(safe_username, errors)
        await self._check_email_availability(form_data.email, errors)

        # Phase 3: Password security (HIBP + custom banned list)
        await self._check_password_banned(form_data.password, errors)

        # Return early if any errors
        if errors:
            failed_fields = ", ".join(sorted(errors))
            logger.warning(
                "registration_failed",
                username=form_data.username,
                reason=f"validation errors: {failed_fields}",
            )
            return RegistrationResult(success=False, errors=errors)

        # check_only mode: validation passed, no account creation
        if check_only:
            return RegistrationResult(success=True)

        # Phase 4: Validate default role exists (fail fast before user creation)
        default_role = await self._role_repo.get_default_role()

        # Phase 5: Create account
        password_hash = await self._password_service.prepare_password(form_data.password)
        now = datetime.now(UTC)

        user = User(
            id=0,  # auto-generated by repository
            username=form_data.username,
            safe_username=safe_username,
            email=form_data.email.lower(),
            password_hash=password_hash,
            country="XX",
            created_at=now,
            updated_at=now,
        )
        try:
            created_user = await self._user_repo.create(user)
        except ValueError as exc:
            # DB unique constraint caught a concurrent duplicate registration
            msg = str(exc)
            if "safe_username" in msg:
                errors.setdefault("username", []).append("Username is already taken.")
            elif "email" in msg:
                errors.setdefault("email", []).append("Email address is already in use.")
            else:
                errors.setdefault("username", []).append("Registration failed. Please try again.")
            return RegistrationResult(success=False, errors=errors)

        # Phase 6: Assign default role
        await self._role_repo.assign_role(created_user.id, default_role.id)

        logger.info(
            "registration_success",
            username=form_data.username,
            user_id=created_user.id,
        )
        return RegistrationResult(success=True)

    async def login(
        self,
        login_request: LoginRequest,
        *,
        country: str,
    ) -> LoginResponse | LoginResult:
        """ログイン認証を実行し、成功時に SessionData を構築して返す。

        認証失敗(ユーザー不在・パスワード不一致)は区別せず
        ``LoginResult.AUTHENTICATION_FAILED`` を返す。
        予期しない例外は ``LoginResult.SERVER_ERROR`` を返す。

        Args:
            login_request: パース済みのログインリクエスト。
            country: Transport 層で解決済みの2文字国コード。
        """
        try:
            return await self._do_login(login_request, country=country)
        except Exception:
            logger.error(
                "login_error",
                username=login_request.username,
                exc_info=True,
            )
            return LoginResult.SERVER_ERROR

    async def _do_login(
        self,
        login_request: LoginRequest,
        *,
        country: str,
    ) -> LoginResponse | LoginResult:
        """login() の内部実装。例外は呼び出し元でキャッチする。"""
        # 1. ユーザー検索
        safe_username = User.normalize_username(login_request.username)
        user = await self._user_repo.get_by_safe_username(safe_username)
        if user is None:
            logger.warning(
                "login_failed",
                username=login_request.username,
                reason="authentication_failed",
            )
            return LoginResult.AUTHENTICATION_FAILED

        # 2. パスワード照合 (argon2id hash vs MD5 hex)
        password_ok = await self._password_service.verify(
            user.password_hash,
            login_request.password_md5,
        )
        if not password_ok:
            logger.warning(
                "login_failed",
                username=login_request.username,
                reason="authentication_failed",
            )
            return LoginResult.AUTHENTICATION_FAILED

        # 3. 権限計算
        roles = await self._role_repo.get_roles_for_user(user.id)
        privileges = await self._permission_service.compute_permissions(user.id)
        role_ids = tuple(role.id for role in roles)

        # 4. 国コード (Transport 層で解決済み)

        # 5. トークン生成
        token = secrets.token_urlsafe(32)

        # 6. SessionData 構築
        client = login_request.client_info
        session_data = SessionData(
            user_id=user.id,
            username=user.username,
            privileges=int(privileges),
            country=country,
            osu_version=client.osu_version,
            utc_offset=client.utc_offset,
            display_city=client.display_city,
            client_hashes=client.client_hashes,
            pm_private=client.pm_private,
        )

        # 7. セッション作成(既存セッションは SessionStore.create() が自動置換)
        await self._session_store.create(user.id, token, session_data)

        logger.info(
            "login_success",
            username=user.username,
            user_id=user.id,
        )

        # 8. LoginResponse 返却
        return LoginResponse(
            token=token,
            user=user,
            privileges=privileges,
            role_ids=role_ids,
            country=country,
            session_data=session_data,
        )

    # ── Private validation helpers ───────────────────────────────────

    @staticmethod
    def _validate_username_format(
        username: str,
        errors: dict[str, list[str]],
    ) -> None:
        msgs: list[str] = []

        if len(username) < _USERNAME_MIN or len(username) > _USERNAME_MAX:
            msgs.append(
                f"Username must be between {_USERNAME_MIN} and {_USERNAME_MAX} characters."
            )

        if username and not _USERNAME_PATTERN.match(username):
            msgs.append(_MSG_USERNAME_CHARS)

        if " " in username and "_" in username:
            msgs.append("Username cannot contain both spaces and underscores.")

        if msgs:
            errors["username"] = msgs

    @staticmethod
    def _validate_password_format(
        password: str,
        errors: dict[str, list[str]],
    ) -> None:
        msgs: list[str] = []

        if len(password) < _PASSWORD_MIN or len(password) > _PASSWORD_MAX:
            msgs.append(
                f"Password must be between {_PASSWORD_MIN} and {_PASSWORD_MAX} characters."
            )

        if len(set(password)) < _PASSWORD_UNIQUE_MIN:
            msgs.append(
                f"Password must contain at least {_PASSWORD_UNIQUE_MIN} unique characters."
            )

        if msgs:
            errors["password"] = msgs

    @staticmethod
    def _validate_email_format(
        email: str,
        errors: dict[str, list[str]],
    ) -> None:
        if not _EMAIL_PATTERN.match(email):
            errors["email"] = ["Invalid email address format."]

    async def _check_username_availability(
        self,
        safe_username: str,
        errors: dict[str, list[str]],
    ) -> None:
        existing = await self._user_repo.get_by_safe_username(safe_username)
        if existing is not None:
            errors.setdefault("username", []).append("Username is already taken.")
            return

        if await self._user_repo.is_username_disallowed(safe_username):
            errors.setdefault("username", []).append("This username is not allowed.")

    async def _check_email_availability(
        self,
        email: str,
        errors: dict[str, list[str]],
    ) -> None:
        existing = await self._user_repo.get_by_email(email)
        if existing is not None:
            errors.setdefault("email", []).append("Email address is already in use.")

    async def _check_password_banned(
        self,
        password: str,
        errors: dict[str, list[str]],
    ) -> None:
        if await self._password_service.is_password_banned(password):
            errors.setdefault("password", []).append(_MSG_PASSWORD_COMPROMISED)
