"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from datetime import datetime, timedelta
from enum import Enum
from typing import List, Optional, Union
from glide_shared.constants import TEncodable

@dataclass
class PubSubMsg:
    """
    Describes the incoming pubsub message

    Attributes:
        message (TEncodable): Incoming message.
        channel (TEncodable): Name of an channel that triggered the message.
        pattern (Optional[TEncodable]): Pattern that triggered the message.
    """
    message: TEncodable
    channel: TEncodable
    pattern: Optional[TEncodable]
    ...


class ConditionalChange(Enum):
    """
    A condition to the `SET`, `ZADD` and `GEOADD` commands.
    """
    ONLY_IF_EXISTS = ...
    ONLY_IF_DOES_NOT_EXIST = ...


class HashFieldConditionalChange(Enum):
    """
    Field conditional change options for HSETEX command.
    """
    ONLY_IF_ALL_EXIST = ...
    ONLY_IF_NONE_EXIST = ...


@dataclass
class OnlyIfEqual:
    """
    Change condition to the `SET` command,
    For additional conditonal options see ConditionalChange

    - comparison_value - value to compare to the current value of a key.

    If comparison_value is equal to the key, it will overwrite the value of key to the new provided value
    Equivalent to the IFEQ comparison-value in the Valkey API
    """
    comparison_value: TEncodable
    ...


class ExpiryType(Enum):
    """
    SET option: The type of the expiry.
    """
    SEC = ...
    MILLSEC = ...
    UNIX_SEC = ...
    UNIX_MILLSEC = ...
    KEEP_TTL = ...


class ExpiryTypeGetEx(Enum):
    """
    GetEx option: The type of the expiry.
    """
    SEC = ...
    MILLSEC = ...
    UNIX_SEC = ...
    UNIX_MILLSEC = ...
    PERSIST = ...


class InfoSection(Enum):
    """
    INFO option: a specific section of information:

    When no parameter is provided, the default option is assumed.
    """
    SERVER = ...
    CLIENTS = ...
    MEMORY = ...
    PERSISTENCE = ...
    STATS = ...
    REPLICATION = ...
    CPU = ...
    COMMAND_STATS = ...
    LATENCY_STATS = ...
    SENTINEL = ...
    CLUSTER = ...
    MODULES = ...
    KEYSPACE = ...
    ERROR_STATS = ...
    ALL = ...
    DEFAULT = ...
    EVERYTHING = ...


class ExpireOptions(Enum):
    """
    EXPIRE option: options for setting key expiry.
    """
    HasNoExpiry = ...
    HasExistingExpiry = ...
    NewExpiryGreaterThanCurrent = ...
    NewExpiryLessThanCurrent = ...


class UpdateOptions(Enum):
    """
    Options for updating elements of a sorted set key.
    """
    LESS_THAN = ...
    GREATER_THAN = ...


class ExpirySet:
    """
    SET option: Represents the expiry type and value to be executed with "SET" command.

    Attributes:
        cmd_arg (str): The expiry type.
        value (str): The value for the expiry type.
    """
    def __init__(self, expiry_type: ExpiryType, value: Optional[Union[int, datetime, timedelta]]) -> None:
        ...

    def __eq__(self, other: object) -> bool:
        ...

    def set_expiry_type_and_value(self, expiry_type: ExpiryType, value: Optional[Union[int, datetime, timedelta]]) -> None:
        """
        Args:
            expiry_type (ExpiryType): The expiry type.
            value (Optional[Union[int, datetime, timedelta]]): The value of the expiration type. The type of expiration
                determines the type of expiration value:

                    - SEC: Union[int, timedelta]
                    - MILLSEC: Union[int, timedelta]
                    - UNIX_SEC: Union[int, datetime]
                    - UNIX_MILLSEC: Union[int, datetime]
                    - KEEP_TTL: Type[None]
        """
        ...

    def get_cmd_args(self) -> List[str]:
        ...



class ExpiryGetEx:
    """
    GetEx option: Represents the expiry type and value to be executed with "GetEx" command.

    Attributes:
        cmd_arg (str): The expiry type.
        value (str): The value for the expiry type.
    """
    def __init__(self, expiry_type: ExpiryTypeGetEx, value: Optional[Union[int, datetime, timedelta]]) -> None:
        ...

    def set_expiry_type_and_value(self, expiry_type: ExpiryTypeGetEx, value: Optional[Union[int, datetime, timedelta]]) -> None:
        """
        Args:
            expiry_type (ExpiryType): The expiry type.
            value (Optional[Union[int, datetime, timedelta]]): The value of the expiration type. The type of expiration
                determines the type of expiration value:

                    - SEC: Union[int, timedelta]
                    - MILLSEC: Union[int, timedelta]
                    - UNIX_SEC: Union[int, datetime]
                    - UNIX_MILLSEC: Union[int, datetime]
                    - PERSIST: Type[None]
        """
        ...

    def get_cmd_args(self) -> List[str]:
        ...



class InsertPosition(Enum):
    BEFORE = ...
    AFTER = ...


class FlushMode(Enum):
    """
    Defines flushing mode for:

    `FLUSHALL` command and `FUNCTION FLUSH` command.

    See [FLUSHAL](https://valkey.io/commands/flushall/) and [FUNCTION-FLUSH](https://valkey.io/commands/function-flush/)
    for details

    SYNC was introduced in version 6.2.0.
    """
    ASYNC = ...
    SYNC = ...


class FunctionRestorePolicy(Enum):
    """
    Options for the FUNCTION RESTORE command.
    """
    APPEND = ...
    FLUSH = ...
    REPLACE = ...
