"""
This type stub file was generated by pyright.
"""

from enum import Enum
from typing import List, Optional, Tuple, Union
from glide_shared.commands.command_args import Limit
from glide_shared.constants import TEncodable

class InfBound(Enum):
    """
    Enumeration representing numeric and lexicographic positive and negative infinity bounds for sorted set.
    """
    POS_INF = ...
    NEG_INF = ...


class AggregationType(Enum):
    """
    Enumeration representing aggregation types for `ZINTERSTORE` and `ZUNIONSTORE` sorted set commands.
    """
    SUM = ...
    MIN = ...
    MAX = ...


class ScoreFilter(Enum):
    """
    Defines which elements to pop from a sorted set.

    ScoreFilter is a mandatory option for [ZMPOP](https://valkey.io/commands/zmpop)
    and [BZMPOP](https://valkey.io/commands/bzmpop).
    """
    MIN = ...
    MAX = ...


class ScoreBoundary:
    """
    Represents a specific numeric score boundary in a sorted set.

    Args:
        value (float): The score value.
        is_inclusive (bool): Whether the score value is inclusive. Defaults to True.
    """
    def __init__(self, value: float, is_inclusive: bool = ...) -> None:
        ...



class LexBoundary:
    """
    Represents a specific lexicographic boundary in a sorted set.

    Args:
        value (str): The lex value.
        is_inclusive (bool): Whether the score value is inclusive. Defaults to True.
    """
    def __init__(self, value: str, is_inclusive: bool = ...) -> None:
        ...



class RangeByIndex:
    """
    Represents a range by index (rank) in a sorted set.

    The `start` and `end` arguments represent zero-based indexes.

    Attributes:
        start (int): The start index of the range.
        end (int): The end index of the range.
    """
    def __init__(self, start: int, end: int) -> None:
        ...



class RangeByScore:
    """
    Represents a range by score in a sorted set.

    The `start` and `end` arguments represent score boundaries.

    Attributes:
        start (Union[InfBound, ScoreBoundary]): The start score boundary.
        end (Union[InfBound, ScoreBoundary]): The end score boundary.
        limit (Optional[Limit]): The limit argument for a range query. Defaults to None. See `Limit`
            class for more information.
    """
    def __init__(self, start: Union[InfBound, ScoreBoundary], end: Union[InfBound, ScoreBoundary], limit: Optional[Limit] = ...) -> None:
        ...



class RangeByLex:
    """
    Represents a range by lexicographical order in a sorted set.

    The `start` and `end` arguments represent lexicographical boundaries.

    Attributes:
        start (Union[InfBound, LexBoundary]): The start lexicographic boundary.
        end (Union[InfBound, LexBoundary]): The end lexicographic boundary.
        limit (Optional[Limit]): The limit argument for a range query. Defaults to None. See `Limit` class
            for more information.
    """
    def __init__(self, start: Union[InfBound, LexBoundary], end: Union[InfBound, LexBoundary], limit: Optional[Limit] = ...) -> None:
        ...



class GeospatialData:
    """
    Represents a geographic position defined by longitude and latitude.

    The exact limits, as specified by EPSG:900913 / EPSG:3785 / OSGEO:41001 are the following:

        - Valid longitudes are from -180 to 180 degrees.
        - Valid latitudes are from -85.05112878 to 85.05112878 degrees.

    Attributes:
        longitude (float): The longitude coordinate.
        latitude (float): The latitude coordinate.
    """
    def __init__(self, longitude: float, latitude: float) -> None:
        ...



class GeoUnit(Enum):
    """
    Enumeration representing distance units options for the `GEODIST` command.
    """
    METERS = ...
    KILOMETERS = ...
    MILES = ...
    FEET = ...


class GeoSearchByRadius:
    """
    Represents search criteria of searching within a certain radius from a specified point.

    Attributes:
        radius (float): Radius of the search area.
        unit (GeoUnit): Unit of the radius. See `GeoUnit`.
    """
    def __init__(self, radius: float, unit: GeoUnit) -> None:
        """
        Initialize the search criteria.
        """
        ...

    def to_args(self) -> List[str]:
        """
        Convert the search criteria to the corresponding part of the command.

        Returns:
            List[str]: List representation of the search criteria.
        """
        ...



class GeoSearchByBox:
    """
    Represents search criteria of searching within a specified rectangular area.

    Attributes:
        width (float): Width of the bounding box.
        height (float): Height of the bounding box
        unit (GeoUnit): Unit of the radius. See `GeoUnit`.
    """
    def __init__(self, width: float, height: float, unit: GeoUnit) -> None:
        """
        Initialize the search criteria.
        """
        ...

    def to_args(self) -> List[str]:
        """
        Convert the search criteria to the corresponding part of the command.

        Returns:
            List[str]: List representation of the search criteria.
        """
        ...



class GeoSearchCount:
    """
    Represents the count option for limiting the number of results in a GeoSearch.

    Attributes:
        count (int): The maximum number of results to return.
        any_option (bool): Whether to allow returning as enough matches are found.
            This means that the results returned may not be the ones closest to the specified point. Default to False.
    """
    def __init__(self, count: int, any_option: bool = ...) -> None:
        """
        Initialize the count option.
        """
        ...

    def to_args(self) -> List[str]:
        """
        Convert the count option to the corresponding part of the command.

        Returns:
            List[str]: List representation of the count option.
        """
        ...



def separate_keys(keys: Union[List[TEncodable], List[Tuple[TEncodable, float]]]) -> Tuple[List[TEncodable], List[TEncodable]]:
    """
    Returns separate lists of keys and weights in case of weighted keys.
    """
    ...
