"""
This type stub file was generated by pyright.
"""

from collections.abc import Collection
from typing import Any, Callable, Generic
from typing_extensions import TypeVar, overload, override
from caterpillar.options import Flag
from caterpillar.shared import PackMixin, UnpackMixin
from caterpillar.abc import _ArgType, _ContextLambda, _ContextLike, _EndianLike, _IT, _LengthT, _OT, _OptionLike, _StructLike, _SwitchLambda
from ._base import Field

class ByteOrderMixin(Generic[_IT, _OT]):
    def __set_byteorder__(self, order: _EndianLike) -> Field[_IT, _OT]:
        """Returns a field with the given byteorder"""
        ...



class FieldMixin(ByteOrderMixin[_IT, _OT]):
    """A simple mixin to support operators used to create :class:`Field` instances."""
    def __or__(self, flag: _OptionLike) -> Field[_IT, _OT]:
        """Creates a field *with* the given flag."""
        ...

    def __xor__(self, flag: Flag) -> Field[_IT, _OT]:
        """Creates a field *without* the given flag."""
        ...

    def __matmul__(self, offset: _ContextLambda[int] | int) -> Field[_IT, _OT]:
        """Creates a field that should start at the given offset."""
        ...

    def __getitem__(self, dim: _LengthT) -> Field[Collection[_IT], Collection[_OT]]:
        """Returns a sequenced field."""
        ...

    def __rshift__(self, switch: _SwitchLambda | dict[str, _StructLike]) -> Field[_IT, _OT]:
        """Inserts switch options into the new field"""
        ...

    def __floordiv__(self, condition: _ContextLambda[bool] | bool) -> Field[_IT, _OT]:
        """Returns a field with the given condition"""
        ...

    def __rsub__(self, bits: _ContextLambda[int] | int) -> Field[_IT, _OT]:
        """Returns a field with the given bit count"""
        ...

    @overload
    def __and__(self, other: _StructLike[_ChainHeadT, _ChainTailT]) -> Chain[_IT, _ChainTailT]:
        ...

    @overload
    def __and__(self, other: Chain[_ChainHeadT, _ChainTailT]) -> Chain[_ChainHeadT, _OT]:
        ...

    def __and__(self, other: Chain[_ChainHeadT, _ChainTailT] | _StructLike[_IT, _OT]) -> Chain:
        """Returns a chain with the next element added at the end"""
        ...



class FieldStruct(FieldMixin[_IT, _OT], PackMixin[_IT], UnpackMixin[_OT]):
    """
    A mix-in class combining the behavior of _StructLike with additional
    functionality for packing and unpacking structured data.
    """
    def pack_single(self, obj: _IT, context: _ContextLike) -> None:
        """
        Abstract method to pack a single element.

        :param obj: The element to pack.
        :type obj: Any
        :param context: The current operation context.
        :type context: _ContextLike
        :raises NotImplementedError: This method must be implemented by subclasses.
        """
        ...

    def unpack_single(self, context: _ContextLike) -> _OT:
        """
        Abstract method to unpack a single element.

        :param context: The current operation context.
        :type context: _ContextLike
        :raises NotImplementedError: This method must be implemented by subclasses.
        :return: The unpacked element.
        """
        ...

    def pack_seq(self, seq: Collection[_IT], context: _ContextLike) -> None:
        """
        Pack a sequence of elements using the provided context.

        :param seq: The sequence of elements to pack.
        :type seq: Iterable
        :param context: The current operation context.
        :type context: _ContextLike
        """
        ...

    def unpack_seq(self, context: _ContextLike) -> Collection[_OT]:
        """
        Unpack a sequence of elements using the provided context.

        :param context: The current operation context.
        :type context: _ContextLike
        :return: The list of unpacked elements.
        """
        ...

    def __pack__(self, obj: _IT, context: _ContextLike) -> None:
        """
        Pack data based on whether the field is sequential or not.

        :param obj: The data to pack.
        :type obj: Any
        :param context: The current operation context.
        :type context: _ContextLike
        """
        ...

    def __unpack__(self, context: _ContextLike) -> _OT:
        """
        Unpack data based on whether the field is sequential or not.

        :param context: The current operation context.
        :type context: _ContextLike
        :return: The unpacked data.
        """
        ...

    @override
    def __repr__(self) -> str:
        """
        String representation of the FieldStruct instance.

        :return: A string representation.
        """
        ...



_ChainHeadT = TypeVar("_ChainHeadT", default=Any)
_ChainTailT = TypeVar("_ChainTailT", default=Any)
class Chain(FieldStruct[_ChainHeadT, _ChainTailT]):
    """
    Represents a chain of structures where each structure in the chain is linked
    to the next one, forming a sequence.

    :param initial: The initial structure in the chain.
    :param structs: Additional structures to be added to the chain.

    The chain allows packing and unpacking data through its elements in sequence.

    .. note::
        - Unpacking travels from the head to the tail.
        - Packing travels from the tail to the head.
    """
    __slots__: tuple[str, ...] = ...
    def __init__(self, initial: _StructLike[_ChainHeadT, Any], *structs: _StructLike[Any, Any], tail: _StructLike[bytes, _ChainTailT] | None = ...) -> None:
        ...

    @property
    def head(self) -> _StructLike[_ChainHeadT, Any]:
        """
        Get the head of the chain, i.e., the first structure.

        :return: The head of the chain.
        :rtype: _StructLike
        """
        ...

    @property
    def tail(self) -> _StructLike[Any, _ChainTailT]:
        """
        Get the tail of the chain, i.e., the last structure.

        :return: The tail of the chain.
        :rtype: _StructLike
        """
        ...

    def __size__(self, context: _ContextLike) -> int:
        """
        Calculate the size of the chain in bytes.

        :param context: The context for the calculation.
        :type context: _ContextLike
        :return: The size of the chain.
        :rtype: int
        """
        ...

    def __type__(self) -> type | str | None:
        """
        Get the type of the tail structure in the chain.

        :return: The type of the tail structure.
        :rtype: type
        """
        ...

    @override
    def __and__(self, other: _StructLike[_IT, _OT]) -> Chain[_ChainHeadT, _OT]:
        """
        Concatenate another structure to the end of the chain.

        :param other: The structure to concatenate.
        :type other: _StructLike
        :return: The updated chain.
        :rtype: Chain
        """
        ...

    def __rand__(self, other: _StructLike[_IT, _OT]) -> Chain[_ChainHeadT, _OT]:
        """
        Concatenate another structure to the beginning of the chain.

        :param other: The structure to concatenate.
        :type other: _StructLike
        :return: The updated chain.
        :rtype: Chain
        """
        ...

    @override
    def unpack_single(self, context: _ContextLike) -> _ChainTailT:
        """
        Unpack a single data instance from the chain.

        :param context: The context for the unpacking operation.
        :type context: _ContextLike
        :return: A memory view representing the unpacked data.
        :rtype: memoryview
        """
        ...

    @override
    def pack_single(self, obj: _IT, context: _ContextLike) -> None:
        """
        Pack a single data instance into the chain.

        :param Any obj: The data to pack into the chain.
        :param context: The context for the packing operation.
        :type context: _ContextLike
        """
        ...



class Operator(Generic[_IT, _OT]):
    """Defines a custom opearator (user-defined)

    It operates _infix_ between two statements and takes them as
    agruments. For instance, the following example will return
    an array of structures:

    .. code-block:: python

        from caterpillar.fields import uint16, Operator
        from caterpillar.model import struct

        M = Operator(lambda a, b: a[b*2])

        @struct
        class Format:
            f1: uint16 /M/ 3

    This class reserves the `/` operator. It is also possible to
    use this class as a decorator on callable objects:

    .. code-block:: python

        @Operator
        def M(a, b):
            return a[b*2]

    :param func: The function to be applied.
    :type func: Callable[[Any, Any], _StructLike]
    """
    def __init__(self, func: Callable[[Any, Any], _StructLike[_IT, _OT]]) -> None:
        ...

    def __truediv__(self, arg2: object) -> _StructLike[_IT, _OT]:
        ...

    def __rtruediv__(self, arg1: object) -> Operator[_IT, _OT]:
        ...

    def __call__(self, arg1: object, arg2: object) -> _StructLike[_IT, _OT]:
        ...



def get_args(args: _ArgType | list[_ArgType], context: _ContextLike) -> list[Any]:
    """
    Get arguments for an instance.

    :param args: Input arguments.
    :type args: Any
    :param context: The current operation context.
    :type context: _ContextLike
    :return: A list of processed arguments.
    :rtype: list
    """
    ...

def get_kwargs(kwargs: dict[str, _ArgType], context: _ContextLike) -> dict[str, Any]:
    """
    Process a dictionary of keyword arguments, replacing callable values with their
    results.

    :param kwargs: Dictionary of keyword arguments.
    :type kwargs: dict
    :param context: The current operation context.
    :type context: _ContextLike
    :return: A new dictionary with processed keyword arguments.
    :rtype: dict
    """
    ...
