"""
This type stub file was generated by pyright.
"""

from collections.abc import Iterable
from typing import Any, Protocol, TYPE_CHECKING, runtime_checkable
from typing_extensions import override
from caterpillar.abc import _ArgType, _ContextLambda, _ContextLike, _GreedyType, _IT, _StructLike
from .common import Bytes, Memory
from cryptography.hazmat.primitives.ciphers import CipherAlgorithm, modes
from cryptography.hazmat.primitives.padding import PaddingContext

if TYPE_CHECKING:
    ...
@runtime_checkable
class Padding(Protocol):
    def unpadder(self) -> PaddingContext:
        """Abstract method to get an unpadder for padding."""
        ...

    def padder(self) -> PaddingContext:
        """Abstract method to get a padder for padding."""
        ...



class Encrypted(Memory):
    """Struct that is able to encrypt/decrypt blocks of memory.

    :param length: Length of the encrypted data.
    :type length: Union[int, _GreedyType, _ContextLambda]
    :param algorithm: Encryption algorithm.
    :type algorithm: Type[algorithms.CipherAlgorithm]
    :param mode: Encryption mode.
    :type mode: Union[Type[modes.Mode], modes.Mode]
    :param padding: Padding scheme for encryption.
    :type padding: Union[Padding, Type[Padding]], optional
    :param algo_args: Additional arguments for the encryption algorithm.
    :type algo_args: Optional[Iterable[_ArgType]], optional
    :param mode_args: Additional arguments for the encryption mode.
    :type mode_args: Optional[Iterable[_ArgType]], optional
    :param padding_args: Additional arguments for the padding scheme.
    :type padding_args: Optional[Iterable[_ArgType]], optional
    :param post: Post-processing structure.
    """
    def __init__(self, length: int | _GreedyType | _ContextLambda[int], algorithm: type[CipherAlgorithm], mode: type[modes.Mode] | modes.Mode, padding: Padding | type[Padding] | None = ..., algo_args: Iterable[_ArgType] | None = ..., mode_args: Iterable[_ArgType] | None = ..., padding_args: Iterable[_ArgType] | None = ..., post: _StructLike | None = ...) -> None:
        ...

    def algorithm(self, context: _ContextLike) -> CipherAlgorithm:
        """
        Get the encryption algorithm instance.

        :param context: The current operation context.
        :type context: _ContextLike
        :return: An instance of the encryption algorithm.
        :rtype: algorithms.CipherAlgorithm
        """
        ...

    def mode(self, context: _ContextLike) -> modes.Mode | None:
        """
        Get the encryption mode instance.

        :param context: The current operation context.
        :type context: _ContextLike
        :return: An instance of the encryption mode.
        :rtype: modes.Mode
        """
        ...

    def padding(self, context: _ContextLike) -> Padding | None:
        """
        Get the padding scheme instance.

        :param context: The current operation context.
        :type context: _ContextLike
        :return: An instance of the padding scheme.
        :rtype: Padding
        """
        ...

    def get_instance(self, type_: type[_IT], field: _IT | Any | None, args: dict[str, _ArgType] | Iterable[_ArgType] | None, context: _ContextLike) -> _IT | None:
        """
        Get an instance of a specified type.

        :param type_: The desired type of the instance.
        :type type_: type
        :param field: The field or instance.
        :type field: Any
        :param args: Additional arguments for the instance.
        :type args: Any
        :param context: The current operation context.
        :type context: _ContextLambda
        :return: An instance of the specified type.
        :rtype: Any
        """
        ...

    @override
    def pack_single(self, obj: bytes | memoryview | bytearray, context: _ContextLike) -> None:
        """
        Pack a single element.

        :param obj: The element to pack.
        :type obj: Any
        :param context: The current operation context.
        :type context: _ContextLike
        """
        ...

    @override
    def unpack_single(self, context: _ContextLike) -> memoryview:
        """
        Unpack a single element.

        :param context: The current operation context.
        :type context: _ContextLike
        :return: The unpacked element as a memoryview.
        :rtype: memoryview
        """
        ...



_KeyType = int | str | bytes
class KeyCipher(Bytes):
    __slots__: tuple[str, ...] = ...
    def __init__(self, key: _KeyType | _ContextLambda[_KeyType], length: _GreedyType | _ContextLambda[int] | int | None = ...) -> None:
        ...

    def is_lazy(self) -> bool:
        ...

    def set_key(self, key: _KeyType | _ContextLambda[_KeyType], context: _ContextLike | None = ...) -> None:
        ...

    def process(self, obj: bytes, context: _ContextLike) -> bytes:
        ...

    @override
    def pack_single(self, obj: bytes, context: _ContextLike) -> None:
        ...

    @override
    def unpack_single(self, context: _ContextLike) -> bytes:
        ...



class Xor(KeyCipher):
    __slots__: tuple[()] = ...


class Or(KeyCipher):
    __slots__: tuple[()] = ...


class And(KeyCipher):
    __slots__: tuple[()] = ...
