"""
This type stub file was generated by pyright.
"""

from types import TracebackType
from typing import Callable, Generic, Protocol, TYPE_CHECKING
from typing_extensions import Literal, Self, TypeVar, override
from caterpillar.abc import _ContextLambda, _ContextLike, _StructLike
from cryptography.hazmat.primitives import hashes, hmac

DEFAULT_DIGEST_PATH = ...
if TYPE_CHECKING:
    ...
class _DigestValue:
    """
    A placeholder class representing a digest value.

    This class is used as a placeholder for digests or checksum values in
    the context of cryptographic algorithms or other hash-like operations.
    """
    @override
    def __repr__(self) -> str:
        ...



_AlgoObjT = TypeVar("_AlgoObjT")
_AlgoReturnT = TypeVar("_AlgoReturnT", default=bytes)
_AlgoUpadeFunc = Callable[[_AlgoObjT, bytes, _ContextLike], _AlgoObjT | None]
_AlgoFinishFunc = Callable[[_AlgoObjT, _ContextLike], _AlgoReturnT]
_AlgoCreateFunc = _ContextLambda[_AlgoObjT]
class Algorithm(Generic[_AlgoObjT, _AlgoReturnT]):
    """
    .. versionadded:: 2.4.0

    A class representing a cryptographic or checksum algorithm.

    This class allows for the creation, updating, and finalization of values using a
    specified algorithm. It abstracts the necessary methods to interact with
    hash algorithms or checksums like SHA256 or CRC32.

    Example usage with SHA256:

    >>> SHA256 = Algorithm(
    ...     create=lambda context: hashlib.sha256(),
    ...     update=lambda algo_obj, data, context: algo_obj.update(data),
    ...     digest=lambda algo_obj, context: algo_obj.digest(),
    ... )

    Example usage with CRC32:

    >>> CRC32 = Algorithm(
    ...     create=lambda context: zlib.crc32(b""),
    ...     update=lambda crc_value, data, context: crc32(data, crc_value),
    ...     digest=lambda crc_value, context: crc_value,
    ... )

    This class can be used to handle both cryptographic algorithms and non-cryptographic checksums.

    :param create: A callable that creates an instance of the algorithm or checksum.
    :type create: Callable[[_ContextLike], Any]
    :param update: A callable that updates the algorithm or checksum with new data.
    :type update: Callable[[Any, bytes, _ContextLike], Any]
    :param digest: A callable that returns the digest or checksum value.
    :type digest: Callable[[Any, _ContextLike], bytes]
    :param name: An optional name for the algorithm.
    :type name: Optional[str]
    """
    __slots__: tuple[str, ...] = ...
    def __init__(self, create: _AlgoCreateFunc[_AlgoObjT] | None = ..., update: _AlgoUpadeFunc[_AlgoObjT] | None = ..., digest: _AlgoFinishFunc[_AlgoObjT, _AlgoReturnT] | None = ..., name: str | None = ...) -> None:
        ...

    @override
    def __repr__(self) -> str:
        """
        Return a string representation of the Algorithm instance.

        The representation includes the name of the algorithm, or '<not set>' if no name is provided.

        :return: The string representation of the algorithm.
        :rtype: str
        """
        ...

    def create(self, context: _ContextLike) -> _AlgoObjT:
        """
        Create an instance of the algorithm or checksum using the provided context.

        This method invokes the `create` callable passed during initialization.

        :param context: The context in which to create the algorithm instance.
        :type context: _ContextLike
        :return: An instance of the algorithm or checksum.
        :rtype: Any
        :raises NotImplementedError: If the `create` method is not implemented for this algorithm.
        """
        ...

    def update(self, algo_obj: _AlgoObjT, data: bytes, context: _ContextLike) -> _AlgoObjT | None:
        """
        Update the algorithm or checksum with the given data.

        This method invokes the `update` callable passed during initialization.

        :param algo_obj: The algorithm instance to update (e.g., a SHA256 object).
        :param data: The data to be used for updating the algorithm.
        :param context: The context in which the update takes place.
        :type algo_obj: Any
        :type data: bytes
        :type context: _ContextLike
        :return: The updated algorithm instance or checksum value.
        :rtype: Any
        :raises NotImplementedError: If the `update` method is not implemented for this algorithm.
        """
        ...

    def digest(self, algo_obj: _AlgoObjT, context: _ContextLike) -> _AlgoReturnT:
        """
        Compute the digest or checksum value from the algorithm instance.

        This method invokes the `digest` callable passed during initialization.

        :param algo_obj: The algorithm instance from which to compute the digest.
        :param context: The context in which the digest operation takes place.
        :type algo_obj: Any
        :type context: _ContextLike
        :return: The computed digest or checksum value.
        :rtype: bytes
        :raises NotImplementedError: If the `digest` method is not implemented for this algorithm.
        """
        ...



class Digest(Generic[_AlgoObjT, _AlgoReturnT]):
    """A class to handle the creation, updating, and verification of digests
    using a specified algorithm.

    .. versionadded:: 2.4.0

    .. versionchanged:: 2.4.3

        Python 3.14 is **not** supported, use :class:`DigestField` instead.

    The `Digest` class allows you to integrate hash or checksum algorithms
    into a struct by installing hooks that manage the digest state during
    packing and unpacking. It supports automatic calculation and validation
    of digests during serialization (packing) and deserialization (unpacking).

    Example usage:

    >>> @struct
    ... class Format:
    ...     with Digest(SHA256, Bytes(32), "sha256", verify=True):
    ...         user_data: Bytes(10)
    ...

    This example defines a struct with a `user_data` field and a `sha256` digest
    field. The `Digest` class automatically calculates the SHA256 checksum of
    `user_data` during packing and validates the checksum during unpacking.

    The resulting struct has the following fields:

    >>> Format.__struct__.fields
    [
        Action(Digest.begin),
        Field('user_data', struct=<Bytes>),
        Action(Digest.end),
        Field('sha256', struct=<Bytes>),
        Action(Digest.verify)
    ]

    The `Action` objects install hooks into the current stream for digest calculation
    and validation. When packing an object, the digest will be updated automatically:

    >>> obj = Format(user_data=b"helloworld" * 10)
    Format(user_data=b"helloworld", sha256=<_DigestValue>)

    On packing, the digest is calculated and included in the serialized output:

    >>> pack(obj, Format)
    b"hello world\\xb9M'\\xb9" ...

    If verification is enabled, unpacking will check the validity of the digest:

    >>> unpack(Format, b"invalid data with sha256")
    Traceback (most recent call last):
    ...
    caterpillar.exception.ValidationError: Failed to verify digest of 'sha256'!
    - Expected: <expected_digest_value>
    - Actual: <actual_digest_value>
    Context-Path: <root>.sha256

    :param algorithm: The checksum or cryptographic algorithm used to generate the digest.
    :type algorithm: Algorithm
    :param struct: The struct to which the digest will be attached.
    :type struct: _StructLike
    :param name: An optional name for the digest field (defaults to 'sha256' or another default name).
    :type name: Optional[str]
    :param verify: Whether to enable verification of the digest upon unpacking. Default is False.
    :type verify: bool
    :param path: Optional path to the digest field in the context, used for accessing and storing the digest.
    :type path: Optional[str]
    """
    def __init__(self, algorithm: Algorithm[_AlgoObjT, _AlgoReturnT], struct: _StructLike[_AlgoReturnT, _AlgoReturnT], name: str | None = ..., verify: bool = ..., path: str | None = ...) -> None:
        ...

    @override
    def __repr__(self) -> str:
        ...

    def __enter__(self) -> Self:
        """
        Install the start action for the digest field during struct definition.

        This method is used in a `with` block to set up the digest calculation at the beginning.

        :return: The current Digest instance for further use.
        :rtype: Self
        :raises ValueError: If the start action already exists.
        """
        ...

    def __exit__(self, exc_type: type, exc_value: Exception, traceback: TracebackType) -> None:
        """
        Install the end action for the digest field and finalize the struct field definitions.

        This method is used to finalize the digest field in a `with` block.

        :raises ValueError: If the end action already exists.
        """
        ...

    def begin(self, context: _ContextLike) -> None:
        """
        Initialize the digest calculation at the beginning of packing/unpacking.

        This method sets up the algorithm and prepares the context for checksum calculation.

        :param context: The current context during packing/unpacking.
        :type context: _ContextLike
        """
        ...

    def end_pack(self, context: _ContextLike) -> None:
        """
        Finalize the digest calculation at the end of packing/unpacking.

        This method calculates the digest and stores it in the context for later use.

        :param context: The current context during packing/unpacking.
        :type context: _ContextLike
        """
        ...

    def end_unpack(self, context: _ContextLike) -> None:
        """
        Finalize the digest calculation at the end of unpacking.

        This method retrieves the digest from the context and updates the checksum.

        :param context: The current context during unpacking.
        :type context: _ContextLike
        """
        ...

    def update(self, data: bytes, context: _ContextLike) -> None:
        """
        Update the checksum with new data during packing/unpacking.

        This method feeds new data into the algorithm to update the digest.

        :param data: The data to update the checksum with.
        :type data: bytes
        :param context: The current context during packing/unpacking.
        :type context: _ContextLike
        """
        ...

    def verfiy(self, context: _ContextLike) -> None:
        """
        Verify the checksum upon unpacking.

        This method checks if the digest calculated during unpacking matches the expected digest.
        If verification fails, a `ValidationError` is raised.

        :param context: The current context during unpacking.
        :type context: _ContextLike
        :raises ValidationError: If the digest verification fails.
        """
        ...



CTX_DIGEST_OBJ: Literal["_digest_obj"] = ...
CTX_DIGEST_HOOK: Literal["_digest_hook"] = ...
CTX_DIGEST_ALGO: Literal["_digest_algo"] = ...
CTX_DIGEST: Literal["_digest"] = ...
class DigestFieldAction(Generic[_AlgoObjT, _AlgoReturnT]):
    """
    .. versionadded:: 2.4.5

    Represents an Action used to initialize a digest computation before struct processing begins.

    This action is intended to be used as a pre-processing step before serializing or parsing
    struct fields that are to be hashed. It injects a digest hook into the IO stream to intercept
    and update digest state as data is read or written.

    The following context variables will be populated based on the given target:
    - ``_digest_obj__<target>``: The current state of the digest computation. (hash object)
    - ``_digest_hook__<target>``: The IO hook associated with the digest computation.
    - ``_digest_algo__<target>``: The algorithm used for the digest computation.

    :param target: The unique name identifying this digest field.
    :type target: str
    :param algorithm: The digest algorithm implementation (must support create/update/digest).
    :type algorithm: Algorithm
    """
    def __init__(self, target: str, algorithm: Algorithm[_AlgoObjT, _AlgoReturnT]) -> None:
        ...

    def update(self, data: bytes, context: _ContextLike) -> None:
        """
        Updates the digest object with new data.

        This method is registered with an IO hook so it gets triggered
        automatically during reads/writes to accumulate digest state.
        """
        ...

    def begin(self, context: _ContextLike) -> None:
        """
        Initializes the digest algorithm and attaches an IO hook to track data.
        """
        ...

    __action_unpack__ = ...


class DigestField(Generic[_AlgoReturnT]):
    """
    .. versionadded:: 2.4.5

    Represents a field in a struct that stores or verifies a digest.

    This struct field computes a digest over all preceding fields and then either:
      - Packs the resulting digest value.
      - Unpacks a stored digest and optionally verifies it.

    Example Usage:

    .. code-block:: python

        @struct
        class Format:
            _hash_begin: DigestField.begin("hash", Sha2_256_Algo)
            user_data: Bytes(10)
            hash: Sha2_256_Field("hash", verify=True) = None


    :param target: The unique name shared with the corresponding :class:`DigestFieldAction`.
    :type target: str
    :param struct:  The struct used to pack/unpack the digest value (e.g., Bytes(32))
    :type struct: _StructLike
    :param verify:  Whether to verify the unpacked digest against the computed one.
    :type verify: bool
    """
    def __init__(self, target: str, struct: _StructLike[_AlgoReturnT, _AlgoReturnT], verify: bool = ...) -> None:
        ...

    def __type__(self) -> type:
        """Defines the Python type returned after unpacking (always bytes)."""
        ...

    def __size__(self, context: _ContextLike) -> int:
        """Returns the size in bytes of the digest field."""
        ...

    def __pack__(self, obj: None, context: _ContextLike) -> None:
        """
        Called during packing. Computes the digest over all previously packed data,
        stores it in the context, finalizes the IO hook, and packs the digest itself.
        """
        ...

    def __unpack__(self, context: _ContextLike) -> _AlgoReturnT:
        """
        Called during unpacking. Computes the digest over all preceding data, reads
        the stored digest, optionally verifies it, and returns the unpacked value.

        :raises ValidationError: If verification is enabled and the digest does not match.
        """
        ...

    @staticmethod
    def begin(target: str, algo: Algorithm[_AlgoObjT, _AlgoReturnT]) -> DigestFieldAction[_AlgoObjT, _AlgoReturnT]:
        """Factory method to create a DigestFieldAction used at the start of a struct
        to set up hashing for the named digest field.

        :param target: Shared identifier between DigestField and its corresponding action.
        :type target: str
        :param algo:  Digest algorithm (e.g., Sha2_256_Algo)
        :type algo: Algorithm
        :return: An action to initialize hashing in the struct context.
        :rtype: _Action
        """
        ...



class _DigestFactory(Protocol[_AlgoObjT, _AlgoReturnT]):
    def __call__(self, name: str | None = ..., verify: bool = ..., path: str | None = ...) -> Digest[_AlgoObjT, _AlgoReturnT]:
        ...



class _DigestFieldFactory(Protocol[_AlgoReturnT]):
    def __call__(self, name: str, verify: bool = ...) -> DigestField[_AlgoReturnT]:
        ...



Crc32_Algo = ...
Crc32 = ...
Crc32_Field = ...
Adler_Algo = ...
Adler = ...
Adler_Field = ...
Sha1_Algo = ...
Sha2_224_Algo = ...
Sha2_256_Algo = ...
Sha2_384_Algo = ...
Sha2_512_Algo = ...
Sha3_224_Algo = ...
Sha3_256_Algo = ...
Sha3_384_Algo = ...
Sha3_512_Algo = ...
Md5_Algo = ...
Sha1 = ...
Sha2_224 = ...
Sha2_256 = ...
Sha2_384 = ...
Sha2_512 = ...
Sha3_224 = ...
Sha3_256 = ...
Sha3_384 = ...
Sha3_512 = ...
Md5 = ...
Sha1_Field = ...
Sha2_224_Field = ...
Sha2_256_Field = ...
Sha2_384_Field = ...
Sha2_512_Field = ...
Sha3_224_Field = ...
Sha3_256_Field = ...
Sha3_384_Field = ...
Sha3_512_Field = ...
Md5_Field = ...
class HMACAlgorithm(Algorithm["hmac.HMAC"]):
    """
    HMAC (Hash-based Message Authentication Code) algorithm implementation.

    This class wraps an HMAC algorithm using a specified hash function and key.
    """
    def __init__(self, key: bytes | _ContextLambda[bytes], algorithm: hashes.HashAlgorithm) -> None:
        ...

    @override
    def create(self, context: _ContextLike) -> hmac.HMAC:
        """
        Creates an HMAC object with the provided key and algorithm.
        """
        ...

    @override
    def update(self, algo_obj: hmac.HMAC, data: bytes, context: _ContextLike) -> None:
        """
        Updates the HMAC object with new data.
        """
        ...

    @override
    def digest(self, algo_obj: hmac.HMAC, context: _ContextLike) -> bytes:
        """
        Finalizes the HMAC object and returns the computed digest.
        """
        ...



class HMAC(Digest["hmac.HMAC", bytes]):
    """
    HMAC Digest handler, used to create and verify HMACs based on a provided key and algorithm.
    """
    def __init__(self, key: bytes | _ContextLambda[bytes], algorithm: hashes.HashAlgorithm, name: str | None = ..., verify: bool = ..., path: str | None = ...) -> None:
        ...
