"""
This type stub file was generated by pyright.
"""

from io import RawIOBase
from typing import Callable
from typing_extensions import Buffer, override
from caterpillar.abc import _ContextLambda, _ContextLike

HookInit = _ContextLambda[None]
HookUpdate = Callable[[bytes, _ContextLike], bytes | None]
HookRead = Callable[[bytes, _ContextLike], bytes | None]
HookWrite = Callable[[bytes, _ContextLike], bytes | None]
HookFinish = _ContextLambda[None]
class IOHook(RawIOBase):
    """
    A custom I/O stream wrapper that allows hooks to be installed for various
    stages of stream interaction, such as initialization, reading and writing.

    This class can be used to augment the functionality of an existing stream (e.g.,
    file streams, memory buffers, or network sockets) by attaching custom logic for
    handling data as it is read or written.

    :param io: The underlying I/O stream to which the hooks are applied.
    :type io: RawIOBase
    :param init: Optional hook function to be called during initialization.
    :type init: Optional[HookInit]
    :param update: Optional hook function to modify data before or after reading/writing.
    :type update: Optional[HookUpdate]
    :param read: Optional hook function to be applied to data after reading.
    :type read: Optional[HookRead]
    :param write: Optional hook function to be applied to data before writing.
    :type write: Optional[HookWrite]
    :param finish: Optional hook function to be called when the stream is finished.
    :type finish: Optional[HookFinish]
    """
    def __init__(self, io: RawIOBase | None, init: HookInit | None = ..., update: HookUpdate | None = ..., read: HookRead | None = ..., write: HookWrite | None = ..., finish: HookFinish | None = ...) -> None:
        ...

    def assert_context_set(self) -> None:
        """
        Ensures that the context has been set before any I/O operations are performed.

        :raises ValueError: If the context is not set.
        """
        ...

    def init(self, context: _ContextLike) -> None:
        """
        Initialize the I/O hook with the provided context. This triggers the
        `init` hook, if available, and sets up the context for subsequent operations.

        :param context: The context to be used for initializing the stream.
        :type context: _ContextLike
        """
        ...

    def finish(self, context: _ContextLike) -> None:
        """
        Finalize the I/O hook by calling the `finish` hook (if provided) and
        restoring the original I/O stream in the context.

        :param context: The context used during the finalization.
        :type context: _ContextLike
        """
        ...

    @override
    def seekable(self) -> bool:
        """
        Checks if the underlying I/O stream is seekable.

        :return: True if the stream supports seeking, otherwise False.
        :rtype: bool
        """
        ...

    @override
    def readable(self) -> bool:
        """
        Checks if the underlying I/O stream is readable.

        :return: True if the stream supports reading, otherwise False.
        :rtype: bool
        """
        ...

    @override
    def read(self, size: int = ...) -> bytes | None:
        """
        Read data from the stream, applying the optional hooks (if any).

        - The `update` hook, if provided, will be called to modify the data.
        - The `read` hook, if provided, will be called to further modify the data.

        :param size: The number of bytes to read, defaults to -1 (read until EOF).
        :type size: int
        :return: The read data, possibly modified by the hooks.
        :rtype: Union[bytes, None]
        """
        ...

    @override
    def write(self, b: Buffer, /) -> int:
        """
        Write data to the stream, applying the optional hooks (if any).

        - The `update` hook, if provided, will be called to modify the data before writing.
        - The `write` hook, if provided, will be called to modify the data before the final write operation.

        :param b: The data to write.
        :type b: bytes
        :return: The number of bytes written to the underlying stream.
        :rtype: Union[int, None]
        """
        ...

    @override
    def writable(self) -> bool:
        """
        Checks if the underlying I/O stream is writable.

        :return: True if the stream supports writing, otherwise False.
        :rtype: bool
        """
        ...

    @override
    def tell(self) -> int:
        """
        Returns the current position of the underlying stream.

        :return: The current position in the stream.
        :rtype: int
        """
        ...

    @override
    def seek(self, offset: int, whence: int = ...) -> int:
        """
        Move the cursor to a new position in the underlying stream.

        :param offset: The offset to move.
        :param whence: The reference point for the offset (default is 0, SEEK_SET).
        :return: The new position in the stream.
        :rtype: int
        """
        ...
