"""
This type stub file was generated by pyright.
"""

import ipaddress
import re
from typing import Final
from typing_extensions import override
from caterpillar.abc import _ContextLike
from .common import Transformer
from ._base import singleton

@singleton
class IPv4Address(Transformer[ipaddress.IPv4Address, int, ipaddress.IPv4Address, int]):
    """
    A transformer for encoding and decoding IPv4 addresses.
    """
    __slots__: tuple[()] = ...
    def __init__(self) -> None:
        """
        Initialize the IPv4Address transformer.
        """
        ...

    @override
    def __type__(self) -> type:
        """
        Get the type associated with the transformer.

        :return: The type associated with the transformer.
        :rtype: type
        """
        ...

    @override
    def encode(self, obj: ipaddress.IPv4Address, context: _ContextLike) -> int:
        """
        Encode an IPv4Address object.

        :param ipaddress.IPv4Address obj: The IPv4Address object to encode.
        :param _ContextLike context: The context for encoding.
        :return: The encoded value.
        """
        ...

    @override
    def decode(self, parsed: int, context: _ContextLike) -> ipaddress.IPv4Address:
        """
        Decode an encoded IPv4 address.

        :param int parsed: The parsed integer value representing the IPv4 address.
        :param _ContextLike context: The context for decoding.
        :return: The decoded IPv4 address.
        """
        ...



@singleton
class IPv6Address(Transformer[ipaddress.IPv6Address, int, ipaddress.IPv6Address, int]):
    """
    A transformer for encoding and decoding IPv6 addresses.
    """
    __slots__: tuple[()] = ...
    def __init__(self) -> None:
        """
        Initialize the IPv6Address transformer.
        """
        ...

    @override
    def __type__(self) -> type:
        """
        Get the type associated with the transformer.

        :return: The type associated with the transformer.
        :rtype: type
        """
        ...

    @override
    def encode(self, obj: ipaddress.IPv6Address, context: _ContextLike) -> int:
        """
        Encode an IPv6Address object.

        :param ipaddress.IPv6Address obj: The IPv6Address object to encode.
        :param _ContextLike context: The context for encoding.
        :return: The encoded value.
        """
        ...

    @override
    def decode(self, parsed: int, context: _ContextLike) -> ipaddress.IPv6Address:
        """
        Decode an encoded IPv6 address.

        :param int parsed: The parsed integer value representing the IPv6 address.
        :param _ContextLike context: The context for decoding.
        :return: The decoded IPv6 address.
        """
        ...



class MACAddress(Transformer[str | bytes, bytes, bytes, bytes]):
    """
    A transformer for encoding and decoding MAC addresses.

    :param Optional[str] sep: The separator to use in the MAC address representation.
    """
    DELIMITERS: re.Pattern[bytes] = ...
    def __init__(self, sep: str | None = ..., encoding: str | None = ...) -> None:
        """
        Initialize the MACAddress transformer.

        :param Optional[str] sep: The separator to use in the MAC address representation.
        """
        ...

    @override
    def encode(self, obj: str | bytes, context: _ContextLike) -> bytes:
        """
        Encode a MAC address.

        :param Union[str, bytes] obj: The MAC address to encode.
        :param _ContextLike context: The context for encoding.
        :return: The encoded value.
        """
        ...

    @override
    def decode(self, parsed: bytes, context: _ContextLike) -> bytes:
        """
        Decode an encoded MAC address.

        :param bytes parsed: The parsed bytes representing the MAC address.
        :param _ContextLike context: The context for decoding.
        :return: The decoded MAC address.
        """
        ...



MAC: Final[MACAddress] = ...
