"""
This type stub file was generated by pyright.
"""

from typing import Any, Final, Generic, TypeVar
from typing_extensions import override
from caterpillar.options import Flag
from caterpillar.abc import _ContextLambda, _ContextLike, _IT, _StructLike
from ._mixin import FieldStruct

_PtrValueT = TypeVar("_PtrValueT")
PTR_STRICT: Flag[None] = ...
class pointer(Generic[_PtrValueT], int):
    """
    A custom integer subclass representing a pointer to another struct within the stream.

    :ivar Any obj: The associated object, if any.
    """
    obj: _PtrValueT | None
    @override
    def __repr__(self) -> str:
        ...

    def get(self) -> _PtrValueT | None:
        ...



class Pointer(FieldStruct[int, pointer[_PtrValueT]]):
    """
    A struct that represents a pointer to another struct within the stream.

    :ivar model: An optional configurable model to parse at the offset position.
    :ivar struct: The configured struct to use.
    """
    __slots__: tuple[str, ...] = ...
    def __init__(self, struct: _StructLike[int, int] | _ContextLambda[_StructLike[int, int]], model: _StructLike[_PtrValueT, _PtrValueT] | None = ...) -> None:
        ...

    def __mul__(self, model: _StructLike[_IT, _IT]) -> Pointer[_IT]:
        """
        Create a new Pointer with a specified model.

        :param model: The model to use.
        :return: A new Pointer with the specified model.
        :rtype: Pointer
        """
        ...

    def __type__(self) -> type[pointer[Any]]:
        """
        Get the type associated with the Pointer.

        :return: The type associated with the Pointer.
        :rtype: type
        """
        ...

    def __size__(self, context: _ContextLike) -> int:
        """
        Get the size of the Pointer struct.

        :param context: The context for size calculation.
        :return: The size of the Pointer struct.
        :rtype: int
        """
        ...

    @override
    def unpack_single(self, context: _ContextLike) -> pointer[_PtrValueT]:
        """
        Unpack a single value using the Pointer struct.

        :param context: The context for unpacking.
        :return: The unpacked value.
        """
        ...

    @override
    def pack_single(self, obj: int, context: _ContextLike) -> None:
        """
        Pack a single value using the Pointer struct.

        :param obj: The value to pack.
        :param context: The context for packing.
        """
        ...



UNSIGNED_POINTER_TYS: dict[int, _StructLike[int, int]] = ...
SIGNED_POINTER_TYS: dict[int, _StructLike[int, int]] = ...
def uintptr_fn(context: _ContextLike) -> _StructLike[int, int]:
    """
    Generator function to decide which struct to use as the pointer type based
    on the current architecture.

    :param _ContextLike context: The input context.
    :return: The struct to use.
    :rtype: _StructLike
    """
    ...

def intptr_fn(context: _ContextLike) -> _StructLike[int, int]:
    """
    Generator function to decide which struct to use as the pointer type based
    on the current architecture.

    :param _ContextLike context: The input context.
    :return: The struct to use.
    :rtype: _StructLike
    """
    ...

uintptr: Final[Pointer[Any]] = ...
intptr: Final[Pointer[Any]] = ...
class relative_pointer(pointer[_PtrValueT]):
    """
    A custom integer subclass representing a relative pointer to another struct within the stream.

    :ivar obj: The associated object, if any.
    :ivar base: The base offset.
    :ivar absolute: The absolute offset.
    """
    base: int
    @property
    def absolute(self) -> int:
        """
        Get the absolute offset.

        :return: The absolute offset.
        :rtype: int
        """
        ...



class RelativePointer(Pointer[_PtrValueT]):
    """
    A struct that represents a relative pointer to another struct within the stream.
    """
    @override
    def __type__(self) -> str | type[relative_pointer[Any]]:
        """
        Get the type associated with the RelativePointer.

        :return: The type associated with the RelativePointer.
        :rtype: type
        """
        ...



offintptr: Final[RelativePointer[Any]] = ...
offuintptr: Final[RelativePointer[Any]] = ...
