"""
This type stub file was generated by pyright.
"""

import typing
from typing_extensions import override
from caterpillar.abc import _ContextLike
from ._mixin import FieldStruct

if typing.TYPE_CHECKING:
    ...
VARINT_LSB = ...
class VarInt(FieldStruct[int, int]):
    """Variable-length integer struct.

    This class implements variable-length unsigned integer for big-endian and
    little-endian encoding. The default behaviour uses big-endian encoding. It
    has an additional flag that can be configured globally or once per field.

    ``VARINT_LSB`` specifies that the last significant byte will use a ``1`` to
    identify the end of the varint. Otherwise, zero will be used (which is the
    default setting). The following configurations are therefore possible:

    >>> field = be + vint; print(pack(1024, field))
    b'\\x88\\x00'
    >>> field = be + vint | VARINT_LSB; print(pack(1024, field))
    b'\\x08\\x80'
    >>> field = le + vint; print(pack(1024, field))
    b'\\x80\\x08'
    >>> field = le + vint | VARINT_LSB; print(pack(1024, field))
    b'\\x00\\x88'
    """
    __slots__: tuple[str, ...] = ...
    def __init__(self) -> None:
        ...

    def __type__(self) -> type:
        ...

    def __size__(self, context: _ContextLike) -> int:
        ...

    def bit_config(self, context: _ContextLike) -> tuple[int, ...]:
        ...

    @override
    def pack_single(self, obj: int, context: _ContextLike) -> None:
        """
        Pack a single value into the stream.

        :param obj: The value to pack.
        :param context: The current context.
        """
        ...

    @override
    def unpack_single(self, context: _ContextLike) -> int:
        """
        Unpack a single value from the stream.

        :param stream: The input stream.
        :param context: The current context.
        :return: The unpacked value.
        """
        ...



vint: typing.Final[VarInt] = ...
