"""
This type stub file was generated by pyright.
"""

from enum import Enum
from typing import List, Mapping, Optional
from glide_shared.constants import TEncodable

class OrderBy(Enum):
    """Sort order for FT.SEARCH SORTBY clause."""
    ASC = ...
    DESC = ...


class InfoScope(Enum):
    """Controls which nodes provide index information in cluster mode."""
    LOCAL = ...
    PRIMARY = ...
    CLUSTER = ...


class ShardScope(Enum):
    """Shard scope for cluster query operations."""
    ALLSHARDS = ...
    SOMESHARDS = ...


class ConsistencyMode(Enum):
    """Consistency mode for cluster query operations."""
    CONSISTENT = ...
    INCONSISTENT = ...


class FtSearchLimit:
    """
    This class represents the arguments for the LIMIT option of the FT.SEARCH command.
    """
    def __init__(self, offset: int, count: int) -> None:
        """
        Initialize a new FtSearchLimit instance.

        Args:
            offset (int): The number of keys to skip before returning the result for the FT.SEARCH command.
            count (int): The total number of keys to be returned by FT.SEARCH command.
        """
        ...

    def to_args(self) -> List[TEncodable]:
        """
        Get the arguments for the LIMIT option of FT.SEARCH.

        Returns:
            List[TEncodable]: A list of LIMIT option arguments.
        """
        ...



class ReturnField:
    """
    This class represents the arguments for the RETURN option of the FT.SEARCH command.
    """
    def __init__(self, field_identifier: TEncodable, alias: Optional[TEncodable] = ...) -> None:
        """
        Initialize a new ReturnField instance.

        Args:
            field_identifier (TEncodable): The identifier for the field of the key that has to returned as a result of
                FT.SEARCH command.
            alias (Optional[TEncodable]): The alias to override the name of the field in the FT.SEARCH result.
        """
        ...

    def to_args(self) -> List[TEncodable]:
        """
        Get the arguments for the RETURN option of FT.SEARCH.

        Returns:
            List[TEncodable]: A list of RETURN option arguments.
        """
        ...



class FtSearchOptions:
    """
    This class represents the input options to be used in the FT.SEARCH command.
    All fields in this class are optional inputs for FT.SEARCH.
    """
    def __init__(self, return_fields: Optional[List[ReturnField]] = ..., timeout: Optional[int] = ..., params: Optional[Mapping[TEncodable, TEncodable]] = ..., limit: Optional[FtSearchLimit] = ..., count: Optional[bool] = ..., nocontent: Optional[bool] = ..., dialect: Optional[int] = ..., verbatim: Optional[bool] = ..., inorder: Optional[bool] = ..., slop: Optional[int] = ..., sortby: Optional[TEncodable] = ..., sortby_order: Optional[OrderBy] = ..., withsortkeys: Optional[bool] = ..., shard_scope: Optional[ShardScope] = ..., consistency: Optional[ConsistencyMode] = ...) -> None:
        """
        Initialize the FT.SEARCH optional fields.

        Args:
            return_fields (Optional[List[ReturnField]]): The fields of a key that are returned by FT.SEARCH command.
                See `ReturnField`.
            timeout (Optional[int]): This value overrides the timeout parameter of the module.
                The unit for the timeout is in milliseconds.
            params (Optional[Mapping[TEncodable, TEncodable]]): Param key/value pairs that can be referenced from within the
                query expression.
            limit (Optional[FtSearchLimit]): This option provides pagination capability. Only the keys that satisfy the offset
                and count values are returned. See `FtSearchLimit`.
            count (Optional[bool]): This flag option suppresses returning the contents of keys.
                Only the number of keys is returned.
            nocontent (Optional[bool]): If set, the query returns only the document IDs and not the content.
                The document entries in the result will have empty attribute maps.
            dialect (Optional[int]): The query dialect version to use. The only supported dialect is ``2``.
            verbatim (Optional[bool]): If set, stemming is not applied to text terms in the query.
            inorder (Optional[bool]): If set, proximity matching of text terms must be in order.
            slop (Optional[int]): Specifies a slop value for proximity matching of text terms.
            sortby (Optional[TEncodable]): Field name to sort results by. Sorting is applied before the LIMIT clause.
            sortby_order (Optional[OrderBy]): Sort direction (ASC or DESC). Only used when ``sortby`` is set.
            withsortkeys (Optional[bool]): If set and ``sortby`` is specified, augments the output
                with the sort key value. When enabled, each document value in the result map becomes
                a two-element list ``[sort_key, field_map]`` instead of just ``field_map``. The sort
                key is the value of the field used for sorting, or ``None`` if the field is missing.
            shard_scope (Optional[ShardScope]): Controls shard participation in cluster mode. See `ShardScope`.
            consistency (Optional[ConsistencyMode]): Controls consistency requirements in cluster mode. See `ConsistencyMode`.
        """
        ...

    def to_args(self) -> List[TEncodable]:
        """
        Get the optional arguments for the FT.SEARCH command.

        Returns:
            List[TEncodable]:
                List of FT.SEARCH optional arguments.
        """
        ...
