"""
This type stub file was generated by pyright.
"""

"""
Deprecated name for :mod:`structlog.typing`.

.. versionadded:: 20.2.0
.. deprecated:: 22.2.0
"""
from .typing import BindableLogger, Context, EventDict, ExcInfo, ExceptionRenderer, ExceptionTransformer, FilteringBoundLogger, Processor, WrappedLogger
__all__ = ("BindableLogger", "Context", "EventDict", "ExcInfo", "ExceptionRenderer", "ExceptionTransformer", "FilteringBoundLogger", "Processor", "WrappedLogger")
