"""
This type stub file was generated by pyright.
"""

import warnings

__version__ = ...
__release__ = ...
__author__ = ...
def native_support() -> bool:
    """Return True if native support is available."""
    ...

__all__ = ["__version__", "__author__", "__release__", "native_support"]
