"""
This type stub file was generated by pyright.
"""

from collections.abc import Collection
from types import TracebackType
from typing import Any, Callable, TYPE_CHECKING
from caterpillar.abc import _ContextLike, _IT, _OT, _StreamType

if TYPE_CHECKING:
    ...
class WithoutContextVar:
    def __init__(self, context: _ContextLike, name: str, value: Any) -> None:
        ...

    def __enter__(self) -> None:
        ...

    def __exit__(self, exc_type: type, exc_value: Exception, traceback: TracebackType) -> None:
        ...



def unpack_seq(context: _ContextLike, unpack_one: Callable[[_ContextLike], _OT]) -> Collection[_OT]:
    """Generic function to unpack sequenced elements.

    :param stream: the input stream
    :type stream: _StreamType
    :param context: the current context
    :type context: _ContextLike
    :return: a list of unpacked elements
    :rtype: List[Any]
    """
    ...

def pack_seq(seq: Collection[_IT], context: _ContextLike, pack_one: Callable[[_IT, _ContextLike], None]) -> None:
    """Generic function to pack sequenced elements.

    :param seq: the iterable of elements
    :type seq: Iterable
    :param stream: the output stream
    :type stream: _StreamType
    :param context: the current operation context
    :type context: _ContextLike
    :raises InvalidValueError: if the input object is not iterable
    """
    ...

def iseof(stream: _StreamType) -> bool:
    """
    Check if the stream is at the end of the file.

    :param _StreamType stream: The input stream.
    :return: True if the stream is at the end of the file, False otherwise.
    :rtype: bool
    """
    ...
