"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from enum import Enum
from typing import Callable
from typing_extensions import Final, override
from caterpillar.abc import _ArchLike, _ContextLambda, _ContextLike, _EndianLike, _OT, _SupportsSetEndian
from caterpillar.options import Flag

@dataclass(frozen=True)
class ByteOrder:
    """
    Represents byte order information, including alignment and size.

    :param name: A string representing the name of the byte order.
    :param ch: A string representing the character used to specify the byte
               order in struct format strings.
    :param alignment: An enumeration representing the alignment (default
                      is `Alignment.NONE`).
    :param size: An enumeration representing the size (default is
                 `Size.STANDARD`).
    """
    name: str
    ch: str
    class Alignment(Enum):
        NONE = ...
        NATIVE = ...


    alignment: Alignment = ...
    class Size(Enum):
        STANDARD = ...
        NATIVE = ...


    size: Size = ...
    def apply(self, other: object) -> None:
        """
        Applies the byte order information to another object.

        :param other: The object to which the byte order information should be applied.
        """
        ...

    def __add__(self, other: _SupportsSetEndian[_OT]) -> _OT:
        """
        Adds the byte order information to another object using the
        `__set_byteorder__` method.

        :param other: The object to which the byte order information should be added.
        :return: The modified object.
        """
        ...

    def __or__(self, other: _OT) -> _OT:
        """
        Applies the byte order information to another object using the `apply` method.

        :param other: The object to which the byte order information should be applied.
        :return: The modified object.
        """
        ...



class DynByteOrder:
    """Represents a dynamic byte order resolved at runtime.

    A dynamic byte order defers endian resolution until pack or unpack
    execution. Resolution may depend on the active context, a field
    value, or a user-provided callable.

    Supported concepts:

    - Root context resolution using CTX_ORDER
    - Context key lookup using a string or callable
    - Runtime resolution using a function
    - Per-field byte order overrides using addition syntax

    Using the root context byte order::

        @struct(order=Dynamic)
        class Format:
            a: uint16
            b: uint32

        pack(obj, **{CTX_ORDER: BigEndian})

    Using a context key::

        @struct(order=Dynamic(this.spec))
        class Format:
            spec: uint8
            a: uint16


    Using a function::

        def func():
            return BigEndian

        @struct(order=DynByteOrder(func=func))
        class Format:
            a: uint16

    Using a per-field dynamic byte order::

        a: Dynamic(this.spec) + uint16

    :param name: Human readable name for the byte order, defaults to None
    :type name: str, optional
    :param key: Context key or callable used to resolve byte order,
        defaults to None
    :type key: str or callable, optional
    :param func: Callable returning an object with a ch attribute,
        defaults to None
    :type func: callable, optional
    :param init_ch: Initial format character, defaults to None
    :type init_ch: str, optional
    """
    def __init__(self, name: str | None = ..., key: str | _ContextLambda[str | _EndianLike | bool] | None = ..., func: Callable[[], _EndianLike] | _ContextLambda[_EndianLike] | None = ..., init_ch: str | None = ...) -> None:
        ...

    def __call__(self, key: str | _ContextLambda[str | _EndianLike | bool]) -> DynByteOrder:
        """Create a derived dynamic byte order bound to a new key.

        :param key: Context key or callable used for byte order lookup
        :type key: str or callable
        :return: A new dynamic byte order instance
        :rtype: DynByteOrder
        """
        ...

    def getch(self, context: _ContextLike) -> str:
        """Resolve the byte order format character from a context.

        Resolution order:

        1. Function result, with or without context
        2. Context key lookup
        3. Root context CTX_ORDER value
        4. Boolean or string fallback

        Resolution prioritizes a callable, then a context key, and finally
        a root context fallback with default behavior.
        :param context: Context providing byte order information
        :type context: object
        :return: Struct format character representing byte order
        :rtype: str
        """
        ...

    @property
    def ch(self) -> str:
        """Return the active byte order character.

        The value may change dynamically by inspecting the caller frame
        and extracting a local variable named context.

        :return: Struct format character for byte order
        :rtype: str
        """
        ...

    @ch.setter
    def ch(self, value: str) -> None:
        """Set the byte order format character explicitly.

        :param value: Struct format character to assign
        :type value: str
        :return: None
        :rtype: None
        """
        ...

    def __add__(self, other: _SupportsSetEndian[_OT]) -> _OT:
        """Apply this byte order to another object.

        Delegates to the other object's byte order assignment method.

        :param other: Object supporting byte order assignment
        :type other: object
        :return: Result of the byte order assignment
        :rtype: object
        """
        ...

    @override
    def __repr__(self) -> str:
        ...



LITTLE_ENDIAN_FMT: Final[str] = ...
Native: Final[ByteOrder] = ...
BigEndian: Final[ByteOrder] = ...
LittleEndian: Final[ByteOrder] = ...
NetEndian: Final[ByteOrder] = ...
SysNative: Final[ByteOrder] = ...
Dynamic: Final[DynByteOrder] = ...
O_DEFAULT_ENDIAN: Final[Flag[_EndianLike]] = ...
def byteorder(obj: object, default: _EndianLike | None = ...) -> _EndianLike:
    """
    Get the byte order of an object, defaulting to SysNative if not explicitly set.

    :param obj: The object to retrieve the byte order from.
    :return: The byte order of the object.
    """
    ...

def byteorder_is_little(obj: object) -> bool:
    """
    Check if the byte order of an object is little-endian.
    """
    ...

@dataclass
class Arch:
    """
    Represents a system architecture with a name and an indication of whether it is 64-bit.

    :param name: The name of the architecture.
    :param ptr_size: the amount of bits one pointer takes
    """
    name: str
    ptr_size: int
    ...


system_arch: Final[Arch] = ...
x86: Final[Arch] = ...
x86_64: Final[Arch] = ...
ARM: Final[Arch] = ...
ARM64: Final[Arch] = ...
AARCH64: Final[Arch] = ...
PowerPC: Final[Arch] = ...
PowerPC64: Final[Arch] = ...
MIPS: Final[Arch] = ...
MIPS64: Final[Arch] = ...
SPARC: Final[Arch] = ...
SPARC64: Final[Arch] = ...
RISC_V64: Final[Arch] = ...
RISC_V: Final[Arch] = ...
AMD: Final[Arch] = ...
AMD64: Final[Arch] = ...
O_DEFAULT_ARCH: Final[Flag[_ArchLike]] = ...
