"""
This type stub file was generated by pyright.
"""

import typing
from typing import Any, Callable, Generic, Protocol
from typing_extensions import Buffer, Final, Literal, Self, Sized, TypeVar, overload, override
from types import FrameType, TracebackType
from dataclasses import dataclass
from caterpillar.options import Flag
from caterpillar.abc import _ArchLike, _ContextFactoryLike, _ContextLambda, _ContextLike, _EndianLike, _IT, _OT, _StreamType
from caterpillar.fields._base import Field

if typing.TYPE_CHECKING:
    ...
CTX_PARENT = ...
CTX_OBJECT = ...
CTX_OFFSETS = ...
CTX_STREAM = ...
CTX_FIELD = ...
CTX_VALUE = ...
CTX_POS = ...
CTX_INDEX = ...
CTX_PATH = ...
CTX_SEQ = ...
CTX_ROOT = ...
CTX_ORDER = ...
CTX_ARCH = ...
class Context(dict[str, Any]):
    """Represents a context object with attribute-style access."""
    @override
    def __setattr__(self, key: str, value: Any, /) -> None:
        """
        Sets an attribute in the context.

        :param key: The attribute key.
        :param value: The value to be set.
        """
        ...

    @overload
    def __getattribute__(self, key: Literal["_field"]) -> Field[_IT, _OT] | None:
        ...

    @overload
    def __getattribute__(self, key: Literal["_parent"]) -> _ContextLike:
        ...

    @overload
    def __getattribute__(self, key: Literal["_obj"]) -> _ContextLike:
        ...

    @overload
    def __getattribute__(self, key: Literal["_offsets"]) -> dict[int, Buffer]:
        ...

    @overload
    def __getattribute__(self, key: Literal["_io"]) -> _StreamType:
        ...

    @overload
    def __getattribute__(self, key: Literal["_pos"]) -> int:
        ...

    @overload
    def __getattribute__(self, key: Literal["_index"]) -> int:
        ...

    @overload
    def __getattribute__(self, key: Literal["_path"]) -> str:
        ...

    @overload
    def __getattribute__(self, key: Literal["_is_seq"]) -> bool:
        ...

    @overload
    def __getattribute__(self, key: Literal["_root"]) -> _ContextLike:
        ...

    @overload
    def __getattribute__(self, key: Literal["_order"]) -> _EndianLike:
        ...

    @overload
    def __getattribute__(self, key: Literal["_arch"]) -> _ArchLike:
        ...

    @overload
    def __getattribute__(self, key: str) -> Any:
        ...

    @override
    def __getattribute__(self, key: str) -> Any:
        """
        Retrieves an attribute from the context.

        :param key: The attribute key.
        :return: The value associated with the key.
        """
        ...

    def __context_getattr__(self, path: str) -> Any:
        """
        Retrieves an attribute from the context.

        :param key: The attribute key.
        :return: The value associated with the key.
        """
        ...

    def __context_setattr__(self, path: str, value: Any) -> None:
        ...

    @overload
    def __getitem__(self, key: Literal["_field"], /) -> Field[_IT, _OT]:
        ...

    @overload
    def __getitem__(self, key: Literal["_order"], /) -> _EndianLike:
        ...

    @overload
    def __getitem__(self, key: Literal["_arch"], /) -> _ArchLike:
        ...

    @overload
    def __getitem__(self, key: Literal["_parent"], /) -> _ContextLike:
        ...

    @overload
    def __getitem__(self, key: Literal["_root"], /) -> _ContextLike:
        ...

    @overload
    def __getitem__(self, key: Literal["_io"], /) -> _StreamType:
        ...

    @overload
    def __getitem__(self, key: Literal["_offsets"], /) -> dict[int, Buffer]:
        ...

    @overload
    def __getitem__(self, key: Literal["_index"], /) -> int:
        ...

    @overload
    def __getitem__(self, key: Literal["_path"], /) -> str:
        ...

    @overload
    def __getitem__(self, key: Literal["_is_seq"], /) -> bool:
        ...

    @overload
    def __getitem__(self, key: Literal["_pos"], /) -> int:
        ...

    @overload
    def __getitem__(self, key: str, /) -> Any:
        ...

    @override
    def __getitem__(self, key: str, /) -> Any:
        ...



O_CONTEXT_FACTORY: Flag[_ContextFactoryLike] = ...
class SetContextVar(Generic[_IT]):
    """Defines an action that sets a context variable during pack or unpack.

    The value assigned to the context key is computed dynamically using
    a user-provided callable evaluated at runtime.

    :param key: Name of the context variable to set
    :type key: str
    :param func: Callable used to compute the context value
    :type func: callable
    """
    def __init__(self, key: str, func: _ContextLambda[_IT]) -> None:
        ...

    def __action_pack__(self, context: _ContextLike) -> None:
        """Apply the context variable assignment during packing.

        The callable is evaluated and its result is stored in the
        context under the configured key.

        :param context: Active packing context
        :type context: object
        :return: None
        :rtype: None
        """
        ...

    def __action_unpack__(self, context: _ContextLike) -> None:
        """Apply the context variable assignment during unpacking.

        The callable is evaluated and its result is stored in the
        context under the configured key.

        :param context: Active unpacking context
        :type context: object
        :return: None
        :rtype: None
        """
        ...



class ExprMixin:
    """
    A mixin class providing methods for creating binary and unary expressions.
    """
    def __add__(self, other: object) -> BinaryExpression:
        ...

    def __sub__(self, other: object) -> BinaryExpression:
        ...

    def __mul__(self, other: object) -> BinaryExpression:
        ...

    def __floordiv__(self, other: object) -> BinaryExpression:
        ...

    def __truediv__(self, other: object) -> BinaryExpression:
        ...

    def __mod__(self, other: object) -> BinaryExpression:
        ...

    def __pow__(self, other: object) -> BinaryExpression:
        ...

    def __xor__(self, other: object) -> BinaryExpression:
        ...

    def __and__(self, other: object) -> BinaryExpression:
        ...

    def __or__(self, other: object) -> BinaryExpression:
        ...

    def __rshift__(self, other: object) -> BinaryExpression:
        ...

    def __lshift__(self, other: object) -> BinaryExpression:
        ...

    __div__ = ...
    def __radd__(self, other: object) -> BinaryExpression:
        ...

    def __rsub__(self, other: object) -> BinaryExpression:
        ...

    def __rmul__(self, other: object) -> BinaryExpression:
        ...

    def __rfloordiv__(self, other: object) -> BinaryExpression:
        ...

    def __rtruediv__(self, other: object) -> BinaryExpression:
        ...

    def __rmod__(self, other: object) -> BinaryExpression:
        ...

    def __rpow__(self, other: object) -> BinaryExpression:
        ...

    def __rxor__(self, other: object) -> BinaryExpression:
        ...

    def __rand__(self, other: object) -> BinaryExpression:
        ...

    def __ror__(self, other: object) -> BinaryExpression:
        ...

    def __rrshift__(self, other: object) -> BinaryExpression:
        ...

    def __rlshift__(self, other: object) -> BinaryExpression:
        ...

    def __neg__(self) -> UnaryExpression:
        ...

    def __pos__(self) -> UnaryExpression:
        ...

    def __invert__(self) -> UnaryExpression:
        ...

    def __contains__(self, other: object) -> BinaryExpression:
        ...

    def __gt__(self, other: object) -> BinaryExpression:
        ...

    def __ge__(self, other: object) -> BinaryExpression:
        ...

    def __lt__(self, other: object) -> BinaryExpression:
        ...

    def __le__(self, other: object) -> BinaryExpression:
        ...

    @override
    def __eq__(self, other: object) -> BinaryExpression:
        ...

    @override
    def __ne__(self, other: object) -> BinaryExpression:
        ...



class ConditionContext:
    """Class implementation of an inline condition.

    Use this class to automatically apply a condition to multiple
    field definitions. Note that this class will only work if it
    has access to the parent stack frame.

    .. code-block:: python

        @struct
        class Format:
            magic: b"MGK"
            length: uint32

            with this.length > 32:
                # other field definitions here
                foo: uint8

    This class will **replace** any existing fields!

    :param condition: a context lambda or constant boolean value
    :type condition: Union[_ContextLambda, bool]
    """
    __slots__: tuple[str, str, str, str] = ...
    def __init__(self, condition: _ContextLambda[bool], depth: int = ...) -> None:
        ...

    def getframe(self, num: int, msg: str) -> FrameType:
        ...

    def __enter__(self) -> Self:
        ...

    def __exit__(self, exc_type: type, exc_value: Exception, traceback: TracebackType) -> None:
        ...



@dataclass(repr=False)
class BinaryExpression(ExprMixin):
    """
    Represents a binary expression.

    :param operand: The binary operator function.
    :param left: The left operand.
    :param right: The right operand.
    """
    operand: Callable[[Any, Any], bool]
    left: Any | _ContextLambda[Any]
    right: Any | _ContextLambda[Any]
    def __call__(self, context: _ContextLike) -> bool:
        ...

    @override
    def __repr__(self) -> str:
        ...

    def __enter__(self) -> Self:
        ...

    def __exit__(self, exc_type: type, exc_value: Exception, traceback: TracebackType) -> None:
        ...



@dataclass
class UnaryExpression:
    """
    Represents a unary expression.

    :param name: The name of the unary operator.
    :param operand: The unary operator function.
    :param value: The operand.
    """
    name: str
    operand: Callable[[Any], Any]
    value: Any | _ContextLambda[Any]
    def __call__(self, context: _ContextLike) -> Any:
        ...

    @override
    def __repr__(self) -> str:
        ...

    def __enter__(self) -> Self:
        ...

    def __exit__(self, exc_type: type, exc_value: Exception, traceback: TracebackType) -> None:
        ...



class _ContextPathOp(Protocol):
    __name__: str
    def __call__(self, *args: Any, **kwds: Any) -> Any:
        ...



_T = TypeVar("_T")
class ContextPath(Generic[_T], ExprMixin):
    """
    Represents a lambda function for retrieving a value from a Context based on a specified path.
    """
    _ops_: list[tuple[_ContextPathOp, list[Any], dict[str, Any]]]
    def __init__(self, path: str | None = ...) -> None:
        """
        Initializes a ContextPath instance with an optional path.

        :param path: The path to use when retrieving a value from a Context.
        """
        ...

    def __call__(self, context: _ContextLike) -> _T:
        """
        Calls the lambda function to retrieve a value from a Context.

        :param context: The Context from which to retrieve the value.
        :param kwds: Additional keyword arguments.
        :return: The value retrieved from the Context based on the path.
        """
        ...

    def __getitem__(self, key: Any) -> Self:
        ...

    def __type__(self) -> type:
        ...

    @overload
    def __getattribute__(self, key: Literal["_field"]) -> ContextPath[Field[_IT, _OT] | None]:
        ...

    @overload
    def __getattribute__(self, key: Literal["_parent"]) -> ContextPath[_ContextLike]:
        ...

    @overload
    def __getattribute__(self, key: Literal["_obj"]) -> ContextPath[_ContextLike]:
        ...

    @overload
    def __getattribute__(self, key: Literal["_offsets"]) -> ContextPath[dict[int, Buffer]]:
        ...

    @overload
    def __getattribute__(self, key: Literal["_io"]) -> ContextPath[_StreamType]:
        ...

    @overload
    def __getattribute__(self, key: Literal["_pos"]) -> ContextPath[int]:
        ...

    @overload
    def __getattribute__(self, key: Literal["_index"]) -> ContextPath[int]:
        ...

    @overload
    def __getattribute__(self, key: Literal["_path"]) -> ContextPath[str]:
        ...

    @overload
    def __getattribute__(self, key: Literal["_is_seq"]) -> ContextPath[bool]:
        ...

    @overload
    def __getattribute__(self, key: Literal["_root"]) -> ContextPath[_ContextLike]:
        ...

    @overload
    def __getattribute__(self, key: Literal["_order"]) -> ContextPath[_EndianLike]:
        ...

    @overload
    def __getattribute__(self, key: Literal["_arch"]) -> ContextPath[_ArchLike]:
        ...

    @overload
    def __getattribute__(self, key: str) -> ContextPath[_IT]:
        ...

    @override
    def __getattribute__(self, key: str) -> ContextPath[_IT]:
        """
        Gets an attribute from the ContextPath, creating a new instance if needed.

        :param key: The attribute key.
        :return: A new ContextPath instance with an updated path.
        """
        ...

    @override
    def __repr__(self) -> str:
        """
        Returns a string representation of the ContextPath.

        :return: A string representation.
        """
        ...

    @override
    def __str__(self) -> str:
        """
        Returns a string representation of the path.

        :return: A string representation of the path.
        """
        ...

    @property
    def parent(self) -> ContextPath[_ContextLike]:
        ...

    @property
    def parentctx(self) -> ContextPath[_ContextLike]:
        """
        .. versionadded:: 2.8.0
        """
        ...



class ContextLength(ExprMixin):
    def __init__(self, path: ContextPath[Sized]) -> None:
        ...

    def __call__(self, context: _ContextLike) -> int:
        """
        Calls the lambda function to retrieve a value from a Context.

        :param context: The Context from which to retrieve the value.
        :param kwds: Additional keyword arguments (ignored in this implementation).
        :return: The value retrieved from the Context based on the path.
        """
        ...

    @override
    def __repr__(self) -> str:
        ...



this: Final[ContextPath[_ContextLike]] = ...
ctx: Final[ContextPath[_ContextLike]] = ...
parent: Final[ContextPath[_ContextLike]] = ...
parentctx: Final[ContextPath[_ContextLike]] = ...
root: Final[ContextPath[_ContextLike]] = ...
