"""
This type stub file was generated by pyright.
"""

from caterpillar.abc import _ContextLike

class StructException(Exception):
    """Base class for all struct-related exceptions"""
    def __init__(self, message: str, context: _ContextLike | None = ...) -> None:
        ...



class DynamicSizeError(StructException):
    """
    Exception raised for errors related to dynamic sizes in structs.

    This can be used when there are issues with determining the size of a struct element at runtime.
    """
    ...


class OptionError(StructException):
    """
    Exception raised for errors related to options in structs.

    This can be used when there are issues with handling options or choices within a struct.
    """
    ...


class ValidationError(StructException):
    """
    Exception raised for errors related to validation in structs.

    This can be used when there are issues with validating the structure or content of a struct.
    """
    ...


class UnsupportedOperation(StructException):
    """
    Exception raised for unsupported operations in structs.

    This can be used when attempting an operation that is not supported or allowed in the context of structs.
    """
    ...


class InvalidValueError(StructException):
    """
    An exception raised for invalid configuration values.
    """
    ...


class StreamError(StructException):
    """
    An exception raised for read and write issues.
    """
    ...


class DelegationError(StructException):
    """
    An exception used if underlying calls fail.
    """
    ...


class Stop(StructException):
    """Stops the current parsing process"""
    ...
