"""
This type stub file was generated by pyright.
"""

__all__ = ["AARCH64", "AMD", "AMD64", "ARM", "ARM64", "BigEndian", "LittleEndian", "PowerPC", "PowerPC64", "RISC_V", "RISC_V64", "x86", "x86_64", "bitfield", "pack", "pack_file", "pack_into", "struct", "union", "unpack", "unpack_file", "sizeof", "Seq", "typeof", "getstruct", "hasstruct", "ContextPath", "ctx", "parent", "this", "lenof", "to_struct", "F", "opt", "C", "P", "G", "Dynamic", "f"]
