"""
This type stub file was generated by pyright.
"""

import ipaddress
import uuid
from datetime import datetime
from .fields.common import CString, Pass, Timestamp, Uuid, boolean, char, double, float16, float32, float64, int16, int24, int32, int64, int8, psize, pssize, uint16, uint24, uint32, uint64, uint8, void_ptr
from .fields.varint import vint
from .fields.net import IPv4Address, IPv6Address, MAC
from .shortcuts import f

bool1_t = f[bool, 1]
int1_t = f[int, 1]
int2_t = f[int, 2]
int3_t = f[int, 3]
int4_t = f[int, 4]
int5_t = f[int, 5]
int6_t = f[int, 6]
int7_t = f[int, 7]
int8_t = f[int, int8]
uint8_t = f[int, uint8]
int16_t = f[int, int16]
uint16_t = f[int, uint16]
int32_t = f[int, int32]
uint32_t = f[int, uint32]
int64_t = f[int, int64]
uint64_t = f[int, uint64]
ssize_t = f[int, pssize]
size_t = f[int, psize]
float16_t = f[float, float16]
float32_t = f[float, float32]
float64_t = f[float, float64]
double_t = f[float, double]
void_ptr_t = f[int, void_ptr]
cstr_t = f[str, CString(...)]
char_t = f[str, char]
boolean_t = f[bool, boolean]
pass_t = f[None, Pass]
uint24_t = f[int, uint24]
int24_t = f[int, int24]
uuid_t = f[uuid.UUID, Uuid]
vint_t = f[int, vint]
MAC_t = f[bytes, MAC]
ipv6_t = f[ipaddress.IPv4Address, IPv6Address]
ipv4_t = f[ipaddress.IPv4Address, IPv4Address]
timestamp_t = f[datetime, Timestamp()]
balign_t = f[None, 0]
__all__ = ["uint8_t", "uint16_t", "uint24_t", "uint32_t", "uint64_t", "int8_t", "int16_t", "int24_t", "int32_t", "int64_t", "float16_t", "float32_t", "float64_t", "double_t", "size_t", "ssize_t", "uuid_t", "pass_t", "cstr_t", "MAC_t", "ipv4_t", "ipv6_t", "vint_t", "int1_t", "int2_t", "int3_t", "int4_t", "int5_t", "int6_t", "int7_t", "void_ptr_t", "balign_t", "timestamp_t"]
