"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from enum import Enum, IntEnum
from typing import Any, Callable, Dict, List, Optional, Protocol, Set, Tuple, Union
from glide_shared.cache import ClientSideCache
from glide_shared.commands.core_options import PubSubMsg

class NodeAddress:
    """
    Represents the address and port of a node in the cluster.

    Attributes:
        host (str, optional): The server host. Defaults to "localhost".
        port (int, optional): The server port. Defaults to 6379.
    """
    def __init__(self, host: str = ..., port: int = ...) -> None:
        ...
    


class AddressResolver(Protocol):
    """
    A callback protocol for resolving server addresses before connection.

    When provided to a client configuration, this callback is invoked for each
    configured address during connection establishment and during cluster topology
    refreshes. The callback receives the configured host and port, and should return
    the actual host and port to use for the connection.

    Use cases:
        - Custom DNS resolution for service discovery
        - Address translation for proxy setups
        - Dynamic endpoint resolution for cloud environments

    Note:
        The resolver must be thread-safe and should avoid blocking operations,
        as it may be called from multiple threads during connection and topology refresh.
        If the resolver raises an exception, the original address will be used as a fallback.

    Example::

        def my_resolver(host: str, port: int) -> Tuple[str, int]:
            # Custom resolution logic
            resolved_host = my_dns_resolver.resolve(host)
            return (resolved_host, port)

        config = GlideClientConfiguration(
            addresses=[NodeAddress("my-service", 6379)],
            address_resolver=my_resolver,
        )
    """
    def __call__(self, host: str, port: int) -> Tuple[str, int]:
        """
        Resolve the given host and port to the actual connection address.

        Args:
            host (str): The configured host name or IP address.
            port (int): The configured port number.

        Returns:
            Tuple[str, int]: A tuple of (resolved_host, resolved_port) to use for connection.
        """
        ...
    


class ReadFrom(Enum):
    """
    Represents the client's read from strategy.
    """
    PRIMARY = ...
    PREFER_REPLICA = ...
    AZ_AFFINITY = ...
    AZ_AFFINITY_REPLICAS_AND_PRIMARY = ...
    ALL_NODES = ...


class ProtocolVersion(Enum):
    """
    Represents the communication protocol with the server.
    """
    RESP2 = ...
    RESP3 = ...


class CompressionBackend(Enum):
    """
    Represents the compression backend to use for automatic compression.
    """
    ZSTD = ...
    LZ4 = ...


class NodeDiscoveryMode(Enum):
    """
    Controls how the client discovers node roles and topology in standalone mode.
    """
    STANDARD = ...
    STATIC = ...
    DISCOVER_ALL = ...


_MIN_COMPRESSED_SIZE_CACHE: Optional[int] = ...
@dataclass
class CompressionConfiguration:
    """
    Represents the compression configuration for automatic compression of values.

    WARNING: This feature is experimental and not recommended for production use.

    Compression is NOT compatible with commands that manipulate string data on the server side:
    - APPEND, GETRANGE, SETRANGE, STRLEN, LCS
    - INCR, INCRBY, INCRBYFLOAT, DECR, DECRBY
    - GETBIT, SETBIT, BITCOUNT, BITPOS, BITFIELD, BITFIELD_RO, BITOP

    Using these commands with compressed values will result in incorrect behavior or errors.

    Attributes:
        enabled (bool): Whether compression is enabled. Defaults to False.
        backend (CompressionBackend): The compression backend to use. Defaults to CompressionBackend.ZSTD.
        compression_level (Optional[int]): The compression level to use. If not set, the backend's default level will be used.
            Valid ranges are backend-specific and validated by the Rust core.
            ZSTD default is 3
            LZ4 default is 0
        min_compression_size (int): The minimum size in bytes for values to be compressed. Values smaller than this will not be compressed. Defaults to 64 bytes.
        max_decompressed_size (Optional[int]): Maximum allowed size in bytes for decompressed data.
            This limit prevents decompression bombs (maliciously crafted compressed data that expands to huge sizes).
            If not set, defaults to 512MB (matching Valkey's proto-max-bulk-len).
    """
    enabled: bool = ...
    backend: CompressionBackend = ...
    compression_level: Optional[int] = ...
    min_compression_size: int = ...
    max_decompressed_size: Optional[int] = ...
    def __post_init__(self) -> None:
        """Validate compression configuration parameters."""
        ...
    


class BackoffStrategy:
    """
    Represents the strategy used to determine how and when to reconnect, in case of connection failures.
    The time between attempts grows exponentially, to the formula rand(0 .. factor * (exponentBase ^ N)), where N
    is the number of failed attempts, and rand(...) applies a jitter of up to jitter_percent% to introduce randomness and reduce retry storms.
    Once the maximum value is reached, that will remain the time between retry attempts until a reconnect attempt is
    successful.
    The client will attempt to reconnect indefinitely.

    Attributes:
        num_of_retries (int): Number of retry attempts that the client should perform when disconnected from the server,
            where the time between retries increases. Once the retries have reached the maximum value, the time between
            retries will remain constant until a reconnect attempt is succesful.
        factor (int): The multiplier that will be applied to the waiting time between each retry.
            This value is specified in milliseconds.
        exponent_base (int): The exponent base configured for the strategy.
        jitter_percent (Optional[int]): The Jitter percent on the calculated duration. If not set, a default value will be used.
    """
    def __init__(self, num_of_retries: int, factor: int, exponent_base: int, jitter_percent: Optional[int] = ...) -> None:
        ...
    


class ServiceType(Enum):
    """
    Represents the types of AWS services that can be used for IAM authentication.
    """
    ELASTICACHE = ...
    MEMORYDB = ...


class IamAuthConfig:
    """
    Configuration settings for IAM authentication.

    Attributes:
        cluster_name (str): The name of the ElastiCache/MemoryDB cluster.
        service (ServiceType): The type of service being used (ElastiCache or MemoryDB).
        region (str): The AWS region where the ElastiCache/MemoryDB cluster is located.
        refresh_interval_seconds (Optional[int]): Optional refresh interval in seconds for renewing IAM authentication tokens.
            If not provided, the core will use a default value of 300 seconds (5 min).
    """
    def __init__(self, cluster_name: str, service: ServiceType, region: str, refresh_interval_seconds: Optional[int] = ...) -> None:
        ...
    


class ServerCredentials:
    """
    Represents the credentials for connecting to a server.

    Exactly one of the following authentication modes must be provided:
        - Password-based authentication: Use password (and optionally username)
        - IAM authentication: Use username (required) and iam_config

    These modes are mutually exclusive - you cannot use both simultaneously.

    Attributes:
        password (Optional[str]): The password that will be used for authenticating connections to the servers.
            Mutually exclusive with iam_config. Either password or iam_config must be provided.
        username (Optional[str]): The username that will be used for authenticating connections to the servers.
            If not supplied for password-based authentication, "default" will be used.
            Required for IAM authentication.
        iam_config (Optional[IamAuthConfig]): IAM authentication configuration. Mutually exclusive with password.
            Either password or iam_config must be provided.
            The client will automatically generate and refresh the authentication token based on the provided configuration.
    """
    def __init__(self, password: Optional[str] = ..., username: Optional[str] = ..., iam_config: Optional[IamAuthConfig] = ...) -> None:
        ...
    
    def is_iam_auth(self) -> bool:
        """Returns True if this credential is configured for IAM authentication."""
        ...
    


class PeriodicChecksManualInterval:
    """
    Represents a manually configured interval for periodic checks.

    Attributes:
        duration_in_sec (int): The duration in seconds for the interval between periodic checks.
    """
    def __init__(self, duration_in_sec: int) -> None:
        ...
    


class PeriodicChecksStatus(Enum):
    """
    Represents the cluster's periodic checks status.
    To configure specific interval, see PeriodicChecksManualInterval.
    """
    ENABLED_DEFAULT_CONFIGS = ...
    DISABLED = ...


class TlsAdvancedConfiguration:
    """
    Represents advanced TLS configuration settings.

    Attributes:
        use_insecure_tls (Optional[bool]): Whether to bypass TLS certificate verification.

            - When set to True, the client skips certificate validation.
              This is useful when connecting to servers or clusters using self-signed certificates,
              or when DNS entries (e.g., CNAMEs) don't match certificate hostnames.

            - This setting is typically used in development or testing environments. **It is
              strongly discouraged in production**, as it introduces security risks such as man-in-the-middle attacks.

            - Only valid if TLS is already enabled in the base client configuration.
              Enabling it without TLS will result in a `ConfigurationError`.

            - Default: False (verification is enforced).

        root_pem_cacerts (Optional[bytes]): Custom root certificate data for TLS connections in PEM format.

            - When provided, these certificates will be used instead of the system's default trust store.
              This is useful for connecting to servers with self-signed certificates or corporate
              certificate authorities.

            - If set to an empty bytes object (non-None but length 0), a `ConfigurationError` will be raised.

            - If None (default), the system's default certificate trust store will be used (platform verifier).

            - The certificate data should be in PEM format as a bytes object.

            - Multiple certificates can be provided by concatenating them in PEM format.

            Example usage::

                # Load from file
                with open('/path/to/ca-cert.pem', 'rb') as f:
                    cert_data = f.read()
                tls_config = TlsAdvancedConfiguration(root_pem_cacerts=cert_data)

                # Or provide directly
                cert_data = b"-----BEGIN CERTIFICATE-----\\n...\\n-----END CERTIFICATE-----"
                tls_config = TlsAdvancedConfiguration(root_pem_cacerts=cert_data)

        client_cert_pem (Optional[bytes]): Client certificate data for mutual TLS authentication in PEM format.

            - When provided along with client_key_pem, enables mutual TLS (mTLS) authentication
              so that the client presents its certificate to the server.

            - This is to be used when the server requires client certificate authentication.

            - If set to an empty bytes object (non-None but length 0), a `ConfigurationError` will be raised.

            - If None (default), no client certificate will be presented.

            - The certificate data should be in PEM format as a bytes object.

            - Must be used together with client_key_pem.

            Example usage::

                # Load from file
                with open('/path/to/client-cert.pem', 'rb') as f:
                    client_cert = f.read()
                with open('/path/to/client-key.pem', 'rb') as f:
                    client_key = f.read()
                tls_config = TlsAdvancedConfiguration(
                    client_cert_pem=client_cert,
                    client_key_pem=client_key
                )

        client_key_pem (Optional[bytes]): Client private key data for mutual TLS authentication in PEM format.

            - When provided along with client_cert_pem, enables mutual TLS (mTLS) authentication.

            - This private key corresponds to the certificate provided in client_cert_pem.

            - If set to an empty bytes object (non-None but length 0), a `ConfigurationError` will be raised.

            - If None (default), no client key will be used.

            - The key data should be in PEM format as a bytes object.

            - Must be used together with client_cert_pem.
    """
    def __init__(self, use_insecure_tls: Optional[bool] = ..., root_pem_cacerts: Optional[bytes] = ..., client_cert_pem: Optional[bytes] = ..., client_key_pem: Optional[bytes] = ...) -> None:
        ...
    


class AdvancedBaseClientConfiguration:
    """
    Represents the advanced configuration settings for a base Glide client.

    Attributes:
        connection_timeout (Optional[int]): The duration in milliseconds to wait for a TCP/TLS connection to complete.
            This applies both during initial client creation and any reconnection that may occur during request processing.
            **Note**: A high connection timeout may lead to prolonged blocking of the entire command pipeline.
            If not explicitly set, a default value of 2000 milliseconds will be used.
        tls_config (Optional[TlsAdvancedConfiguration]): The advanced TLS configuration settings.
            This allows for more granular control of TLS behavior, such as enabling an insecure mode
            that bypasses certificate validation.
        tcp_nodelay (Optional[bool]): Controls TCP_NODELAY socket option (Nagle's algorithm).
            When True, disables Nagle's algorithm for lower latency by sending packets immediately without buffering.
            When False, enables Nagle's algorithm to reduce network overhead by buffering small packets.
            If not explicitly set, defaults to True.
        pubsub_reconciliation_interval (Optional[int]): The interval in milliseconds between PubSub subscription
            reconciliation attempts. The reconciliation process ensures that the client's desired subscriptions
            match the actual subscriptions on the server.
    """
    def __init__(self, connection_timeout: Optional[int] = ..., tls_config: Optional[TlsAdvancedConfiguration] = ..., tcp_nodelay: Optional[bool] = ..., pubsub_reconciliation_interval: Optional[int] = ...) -> None:
        ...
    


class BaseClientConfiguration:
    """
    Represents the configuration settings for a Glide client.

    Attributes:
        addresses (List[NodeAddress]): DNS Addresses and ports of known nodes in the cluster.
            If the server is in cluster mode the list can be partial, as the client will attempt to map out
            the cluster and find all nodes.
            If the server is in standalone mode, only nodes whose addresses were provided will be used by the
            client.
            For example::

                [
                    NodeAddress("sample-address-0001.use1.cache.amazonaws.com", 6379),
                    NodeAddress("sample-address-0002.use1.cache.amazonaws.com", 6379)
                ]

        use_tls (bool): True if communication with the cluster should use Transport Level Security.
            Should match the TLS configuration of the server/cluster, otherwise the connection attempt will fail.
            For advanced tls configuration, please use `AdvancedBaseClientConfiguration`.
        credentials (ServerCredentials): Credentials for authentication process.
            If none are set, the client will not authenticate itself with the server.
        read_from (ReadFrom): If not set, `PRIMARY` will be used.
        request_timeout (Optional[int]): The duration in milliseconds that the client should wait for a request to
            complete.
            This duration encompasses sending the request, awaiting for a response from the server, and any required
            reconnection or retries.
            If the specified timeout is exceeded for a pending request, it will result in a timeout error. If not
            explicitly set, a default value of 250 milliseconds will be used.
        reconnect_strategy (Optional[BackoffStrategy]): Strategy used to determine how and when to reconnect, in case of
            connection failures.
            If not set, a default backoff strategy will be used.
        database_id (Optional[int]): Index of the logical database to connect to.
            Must be a non-negative integer.If not set, the client will connect to database 0.
        client_name (Optional[str]): Client name to be used for the client. Will be used with CLIENT SETNAME command
            during connection establishment.
        protocol (ProtocolVersion): Serialization protocol to be used. If not set, `RESP3` will be used.
        inflight_requests_limit (Optional[int]): The maximum number of concurrent requests allowed to be in-flight
            (sent but not yet completed).
            This limit is used to control the memory usage and prevent the client from overwhelming the server or getting
            stuck in case of a queue backlog.
            If not set, a default value will be used.
        client_az (Optional[str]): Availability Zone of the client.
            If ReadFrom strategy is AZAffinity, this setting ensures that readonly commands are directed to replicas
            within the specified AZ if exits.
            If ReadFrom strategy is AZAffinityReplicasAndPrimary, this setting ensures that readonly commands are directed
            to nodes (first replicas then primary) within the specified AZ if they exist.
        advanced_config (Optional[AdvancedBaseClientConfiguration]): Advanced configuration settings for the client.

        lazy_connect (Optional[bool]): Enables lazy connection mode, where physical connections to the server(s)
            are deferred until the first command is sent. This can reduce startup latency and allow for client
            creation in disconnected environments.

            When set to `True`, the client will not attempt to connect to the specified nodes during
            initialization. Instead, connections will be established only when a command is actually executed.

            Note that the first command executed with lazy connections may experience additional latency
            as it needs to establish the connection first. During this initial connection, the standard
            request timeout does not apply yet - instead, the connection establishment is governed by
            `AdvancedBaseClientConfiguration.connection_timeout`. The request timeout (`request_timeout`)
            only begins counting after the connection has been successfully established. This behavior
            can effectively increase the total time needed for the first command to complete.

            This setting applies to both standalone and cluster modes. Note that if an operation is
            attempted and connection fails (e.g., unreachable nodes), errors will surface at that point.

            If not set, connections are established immediately during client creation (equivalent to `False`).

        compression (Optional[CompressionConfiguration]): Configuration for automatic compression of values.
            ⚠️ WARNING: This feature is experimental and not recommended for production use.
            When enabled, the client will automatically compress values for set-type commands and decompress
            values for get-type commands. This can reduce bandwidth usage and storage requirements.
            Compression is NOT compatible with server-side string manipulation commands (APPEND, GETRANGE, etc.).
            If not set, compression is disabled.

        client_side_cache (Optional[ClientSideCache]): Configuration for client-side caching.
            See `ClientSideCache` for caching behavior details, supported commands, and expiration semantics.

            In order for 2 clients to share the same cache, they must be
            created with the same ``ClientSideCache`` instance.

            - Clients with different ``ClientSideCache`` instances will have separate caches,
              even if the configurations are identical.
            - Clients using different DBs cannot share the same cache.
            - Clients using different ACL users cannot share the same cache.

        address_resolver (Optional[AddressResolver]): Optional callback for resolving server addresses
            before connection. When provided, this callback will be invoked for each configured address
            during connection establishment and during cluster topology refreshes.
            The callback receives the configured host and port, and should return the actual
            host and port to use for the connection.

            This is useful for:
                - Custom DNS resolution for service discovery
                - Address translation for proxy setups
                - Dynamic endpoint resolution for cloud environments

            If not set, addresses are used as configured without modification.

            Example::

                def my_resolver(host: str, port: int) -> Tuple[str, int]:
                    resolved_host = my_dns_resolver.resolve(host)
                    return (resolved_host, port)

                config = GlideClientConfiguration(
                    addresses=[NodeAddress("my-service", 6379)],
                    address_resolver=my_resolver,
                )
    """
    def __init__(self, addresses: List[NodeAddress], use_tls: bool = ..., credentials: Optional[ServerCredentials] = ..., read_from: ReadFrom = ..., request_timeout: Optional[int] = ..., reconnect_strategy: Optional[BackoffStrategy] = ..., database_id: Optional[int] = ..., client_name: Optional[str] = ..., protocol: ProtocolVersion = ..., inflight_requests_limit: Optional[int] = ..., client_az: Optional[str] = ..., advanced_config: Optional[AdvancedBaseClientConfiguration] = ..., lazy_connect: Optional[bool] = ..., compression: Optional[CompressionConfiguration] = ..., client_side_cache: Optional[ClientSideCache] = ..., address_resolver: Optional[Callable[[str, int], Tuple[str, int]]] = ...) -> None:
        ...
    


class AdvancedGlideClientConfiguration(AdvancedBaseClientConfiguration):
    """
    Represents the advanced configuration settings for a Standalone Glide client.
    """
    def __init__(self, connection_timeout: Optional[int] = ..., tls_config: Optional[TlsAdvancedConfiguration] = ..., tcp_nodelay: Optional[bool] = ..., pubsub_reconciliation_interval: Optional[int] = ...) -> None:
        ...
    


class GlideClientConfiguration(BaseClientConfiguration):
    """
    Represents the configuration settings for a Standalone Glide client.

    Attributes:
        addresses (List[NodeAddress]): DNS Addresses and ports of known nodes in the cluster.
            Only nodes whose addresses were provided will be used by the client.
            For example::

                [
                    NodeAddress("sample-address-0001.use1.cache.amazonaws.com", 6379),
                    NodeAddress("sample-address-0002.use1.cache.amazonaws.com", 6379)
                ]

        use_tls (bool): True if communication with the cluster should use Transport Level Security.
                Please use `AdvancedGlideClusterClientConfiguration`.
        credentials (ServerCredentials): Credentials for authentication process.
                If none are set, the client will not authenticate itself with the server.
        read_from (ReadFrom): If not set, `PRIMARY` will be used.
        request_timeout (Optional[int]):  The duration in milliseconds that the client should wait for a request to complete.
                This duration encompasses sending the request, awaiting for a response from the server, and any required
                reconnection or retries.
                If the specified timeout is exceeded for a pending request, it will result in a timeout error.
                If not explicitly set, a default value of 250 milliseconds will be used.
        reconnect_strategy (Optional[BackoffStrategy]): Strategy used to determine how and when to reconnect, in case of
            connection failures.
            If not set, a default backoff strategy will be used.
        database_id (Optional[int]): Index of the logical database to connect to.
        client_name (Optional[str]): Client name to be used for the client. Will be used with CLIENT SETNAME command during
            connection establishment.
        protocol (ProtocolVersion): The version of the RESP protocol to communicate with the server.
        pubsub_subscriptions (Optional[GlideClientConfiguration.PubSubSubscriptions]): Pubsub subscriptions to be used for the
                client.
                Will be applied via SUBSCRIBE/PSUBSCRIBE commands during connection establishment.
        inflight_requests_limit (Optional[int]): The maximum number of concurrent requests allowed to be in-flight
            (sent but not yet completed).
            This limit is used to control the memory usage and prevent the client from overwhelming the server or getting
            stuck in case of a queue backlog.
            If not set, a default value will be used.
        client_az (Optional[str]): Availability Zone of the client.
            If ReadFrom strategy is AZAffinity, this setting ensures that readonly commands are directed to replicas within
            the specified AZ if exits.
            If ReadFrom strategy is AZAffinityReplicasAndPrimary, this setting ensures that readonly commands are directed to
            nodes (first replicas then primary) within the specified AZ if they exist.
        advanced_config (Optional[AdvancedGlideClientConfiguration]): Advanced configuration settings for the client,
            see `AdvancedGlideClientConfiguration`.
        compression (Optional[CompressionConfiguration]): Configuration for automatic compression of values.
            When enabled, the client will automatically compress values for set-type commands and decompress
            values for get-type commands. This can reduce bandwidth usage and storage requirements.
            If not set, compression is disabled.
        read_only (bool): When True, enables read-only mode for the standalone client.
            In read-only mode:
            - The client skips primary node detection (INFO REPLICATION command)
            - Write commands are blocked and will return an error
            - All connected nodes are treated as valid read targets
            - If no ReadFrom strategy is specified, defaults to PreferReplica
            This is useful for connecting to replica-only deployments or when you want to
            prevent accidental write operations.
            Note: read_only mode is not compatible with AZAffinity or AZAffinityReplicasAndPrimary
            read strategies.
            Defaults to False.
        client_side_cache (Optional[ClientSideCache]): Configuration for client-side caching.
            See `ClientSideCache` for caching behavior details, supported commands, and expiration semantics.

            In order for 2 clients to share the same cache, they must be
            created with the same ``ClientSideCache`` instance.

            - Clients with different ``ClientSideCache`` instances will have separate caches,
              even if the configurations are identical.
            - Clients using different DBs cannot share the same cache.
            - Clients using different ACL users cannot share the same cache.
        node_discovery_mode (NodeDiscoveryMode): Controls how the client discovers node roles
            and topology in standalone mode. If not set, `STANDARD` will be used.
    """
    class PubSubChannelModes(IntEnum):
        """
        Describes pubsub subsciption modes.
        See [valkey.io](https://valkey.io/docs/topics/pubsub/) for more details
        """
        Exact = ...
        Pattern = ...
    
    
    @dataclass
    class PubSubSubscriptions:
        """Describes pubsub configuration for standalone mode client.

        Attributes:
            channels_and_patterns (Dict[GlideClientConfiguration.PubSubChannelModes, Set[str]]):
                Channels and patterns by modes.
            callback (Optional[Callable[[PubSubMsg, Any], None]]):
                Optional callback to accept the incomming messages.
            context (Any):
                Arbitrary context to pass to the callback.
        """
        channels_and_patterns: Dict[GlideClientConfiguration.PubSubChannelModes, Set[str]]
        callback: Optional[Callable[[PubSubMsg, Any], None]]
        context: Any
        ...
    
    
    @dataclass
    class PubSubState:
        desired_subscriptions: Dict[GlideClientConfiguration.PubSubChannelModes, Set[str]]
        actual_subscriptions: Dict[GlideClientConfiguration.PubSubChannelModes, Set[str]]
        ...
    
    
    def __init__(self, addresses: List[NodeAddress], use_tls: bool = ..., credentials: Optional[ServerCredentials] = ..., read_from: ReadFrom = ..., request_timeout: Optional[int] = ..., reconnect_strategy: Optional[BackoffStrategy] = ..., database_id: Optional[int] = ..., client_name: Optional[str] = ..., protocol: ProtocolVersion = ..., pubsub_subscriptions: Optional[PubSubSubscriptions] = ..., inflight_requests_limit: Optional[int] = ..., client_az: Optional[str] = ..., advanced_config: Optional[AdvancedGlideClientConfiguration] = ..., lazy_connect: Optional[bool] = ..., compression: Optional[CompressionConfiguration] = ..., read_only: bool = ..., client_side_cache: Optional[ClientSideCache] = ..., node_discovery_mode: NodeDiscoveryMode = ..., address_resolver: Optional[Callable[[str, int], Tuple[str, int]]] = ...) -> None:
        ...
    


class AdvancedGlideClusterClientConfiguration(AdvancedBaseClientConfiguration):
    """
    Represents the advanced configuration settings for a Glide Cluster client.

    Attributes:
        connection_timeout (Optional[int]): The duration in milliseconds to wait for a TCP/TLS connection to complete.
            This applies both during initial client creation and any reconnection that may occur during request processing.
            **Note**: A high connection timeout may lead to prolonged blocking of the entire command pipeline.
            If not explicitly set, a default value of 2000 milliseconds will be used.
        tls_config (Optional[TlsAdvancedConfiguration]): The advanced TLS configuration settings.
            This allows for more granular control of TLS behavior, such as enabling an insecure mode
            that bypasses certificate validation.
        refresh_topology_from_initial_nodes (bool): Enables refreshing the cluster topology using only the initial nodes.
            When this option is enabled, all topology updates (both the periodic checks and on-demand refreshes
            triggered by topology changes) will query only the initial nodes provided when creating the client, rather than using the internal cluster view.
        pubsub_reconciliation_interval (Optional[int]): The interval in milliseconds between PubSub subscription
            reconciliation attempts. The reconciliation process ensures that the client's desired subscriptions
            match the actual subscriptions on the server.
    """
    def __init__(self, connection_timeout: Optional[int] = ..., tls_config: Optional[TlsAdvancedConfiguration] = ..., refresh_topology_from_initial_nodes: bool = ..., tcp_nodelay: Optional[bool] = ..., pubsub_reconciliation_interval: Optional[int] = ...) -> None:
        ...
    


class GlideClusterClientConfiguration(BaseClientConfiguration):
    """
    Represents the configuration settings for a Cluster Glide client.

    Attributes:
        addresses (List[NodeAddress]): DNS Addresses and ports of known nodes in the cluster.
            The list can be partial, as the client will attempt to map out the cluster and find all nodes.
            For example::

                [
                    NodeAddress("sample-address-0001.use1.cache.amazonaws.com", 6379),
                ]

        use_tls (bool): True if communication with the cluster should use Transport Level Security.
                For advanced tls configuration, please use `AdvancedGlideClusterClientConfiguration`.
        credentials (ServerCredentials): Credentials for authentication process.
                If none are set, the client will not authenticate itself with the server.
        read_from (ReadFrom): If not set, `PRIMARY` will be used.
        request_timeout (Optional[int]):  The duration in milliseconds that the client should wait for a request to complete.
            This duration encompasses sending the request, awaiting for a response from the server, and any required
            reconnection or retries.
            If the specified timeout is exceeded for a pending request, it will result in a timeout error. If not explicitly
            set, a default value of 250 milliseconds will be used.
        reconnect_strategy (Optional[BackoffStrategy]): Strategy used to determine how and when to reconnect, in case of
            connection failures.
            If not set, a default backoff strategy will be used.
        database_id (Optional[int]): Index of the logical database to connect to.
        client_name (Optional[str]): Client name to be used for the client. Will be used with CLIENT SETNAME command during
            connection establishment.
        protocol (ProtocolVersion): The version of the RESP protocol to communicate with the server.
        periodic_checks (Union[PeriodicChecksStatus, PeriodicChecksManualInterval]): Configure the periodic topology checks.
            These checks evaluate changes in the cluster's topology, triggering a slot refresh when detected.
            Periodic checks ensure a quick and efficient process by querying a limited number of nodes.
            Defaults to PeriodicChecksStatus.ENABLED_DEFAULT_CONFIGS.
        pubsub_subscriptions (Optional[GlideClusterClientConfiguration.PubSubSubscriptions]): Pubsub subscriptions to be used
            for the client.
            Will be applied via SUBSCRIBE/PSUBSCRIBE/SSUBSCRIBE commands during connection establishment.
        inflight_requests_limit (Optional[int]): The maximum number of concurrent requests allowed to be in-flight
            (sent but not yet completed).
            This limit is used to control the memory usage and prevent the client from overwhelming the server or getting
            stuck in case of a queue backlog.
            If not set, a default value will be used.
        client_az (Optional[str]): Availability Zone of the client.
            If ReadFrom strategy is AZAffinity, this setting ensures that readonly commands are directed to replicas within
            the specified AZ if exits.
            If ReadFrom strategy is AZAffinityReplicasAndPrimary, this setting ensures that readonly commands are directed to
            nodes (first replicas then primary) within the specified AZ if they exist.
        advanced_config (Optional[AdvancedGlideClusterClientConfiguration]) : Advanced configuration settings for the client,
            see `AdvancedGlideClusterClientConfiguration`.
        compression (Optional[CompressionConfiguration]): Configuration for automatic compression of values.
            When enabled, the client will automatically compress values for set-type commands and decompress
            values for get-type commands. This can reduce bandwidth usage and storage requirements.
            If not set, compression is disabled.
        client_side_cache (Optional[ClientSideCache]): Configuration for client-side caching.
            See `ClientSideCache` for caching behavior details, supported commands, and expiration semantics.

            In order for 2 clients to share the same cache, they must be
            created with the same ``ClientSideCache`` instance.

            - Clients with different ``ClientSideCache`` instances will have separate caches,
              even if the configurations are identical.
            - Clients using different DBs cannot share the same cache.
            - Clients using different ACL users cannot share the same cache.

    Note:
        Currently, the reconnection strategy in cluster mode is not configurable, and exponential backoff
        with fixed values is used.
    """
    class PubSubChannelModes(IntEnum):
        """
        Describes pubsub subsciption modes.
        See [valkey.io](https://valkey.io/docs/topics/pubsub/) for more details
        """
        Exact = ...
        Pattern = ...
        Sharded = ...
    
    
    @dataclass
    class PubSubSubscriptions:
        """Describes pubsub configuration for cluster mode client.

        Attributes:
            channels_and_patterns (Dict[GlideClusterClientConfiguration.PubSubChannelModes, Set[str]]):
                Channels and patterns by modes.
            callback (Optional[Callable[[PubSubMsg, Any], None]]):
                Optional callback to accept the incoming messages.
            context (Any):
                Arbitrary context to pass to the callback.
        """
        channels_and_patterns: Dict[GlideClusterClientConfiguration.PubSubChannelModes, Set[str]]
        callback: Optional[Callable[[PubSubMsg, Any], None]]
        context: Any
        ...
    
    
    @dataclass
    class PubSubState:
        desired_subscriptions: Dict[GlideClusterClientConfiguration.PubSubChannelModes, Set[str]]
        actual_subscriptions: Dict[GlideClusterClientConfiguration.PubSubChannelModes, Set[str]]
        ...
    
    
    def __init__(self, addresses: List[NodeAddress], use_tls: bool = ..., credentials: Optional[ServerCredentials] = ..., read_from: ReadFrom = ..., request_timeout: Optional[int] = ..., reconnect_strategy: Optional[BackoffStrategy] = ..., database_id: Optional[int] = ..., client_name: Optional[str] = ..., protocol: ProtocolVersion = ..., periodic_checks: Union[PeriodicChecksStatus, PeriodicChecksManualInterval] = ..., pubsub_subscriptions: Optional[PubSubSubscriptions] = ..., inflight_requests_limit: Optional[int] = ..., client_az: Optional[str] = ..., advanced_config: Optional[AdvancedGlideClusterClientConfiguration] = ..., lazy_connect: Optional[bool] = ..., compression: Optional[CompressionConfiguration] = ..., client_side_cache: Optional[ClientSideCache] = ..., address_resolver: Optional[Callable[[str, int], Tuple[str, int]]] = ...) -> None:
        ...
    


def load_root_certificates_from_file(path: str) -> bytes:
    """
    Load PEM-encoded root certificates from a file.

    This is a convenience function for loading custom root certificates from disk
    to be used with TlsAdvancedConfiguration.

    Args:
        path (str): The file path to the PEM-encoded certificate file.

    Returns:
        bytes: The certificate data in PEM format.

    Raises:
        FileNotFoundError: If the certificate file does not exist.
        ConfigurationError: If the certificate file is empty.

    Example usage::

        from glide_shared.config import load_root_certificates_from_file, TlsAdvancedConfiguration

        # Load certificates from file
        certs = load_root_certificates_from_file('/path/to/ca-cert.pem')

        # Use in TLS configuration
        tls_config = TlsAdvancedConfiguration(root_pem_cacerts=certs)
    """
    ...

def load_client_certificate_from_file(path: str) -> bytes:
    """
    Load PEM-encoded client certificate from a file for mTLS authentication.

    This is a convenience function for loading client certificates from disk
    to be used with TlsAdvancedConfiguration for mutual TLS (mTLS).

    Args:
        path (str): The file path to the PEM-encoded client certificate file.

    Returns:
        bytes: The client certificate data in PEM format.

    Raises:
        FileNotFoundError: If the certificate file does not exist.
        ConfigurationError: If the certificate file is empty.

    Example usage::

        from glide_shared.config import (
            load_client_certificate_from_file,
            load_client_key_from_file,
            TlsAdvancedConfiguration
        )

        # Load client certificate and key from files
        client_cert = load_client_certificate_from_file('/path/to/client-cert.pem')
        client_key = load_client_key_from_file('/path/to/client-key.pem')

        # Use in TLS configuration
        tls_config = TlsAdvancedConfiguration(
            client_cert_pem=client_cert,
            client_key_pem=client_key
        )
    """
    ...

def load_client_key_from_file(path: str) -> bytes:
    """
    Load PEM-encoded client private key from a file for mutual TLS authentication.

    This is a convenience function for loading client private keys from disk
    to be used with TlsAdvancedConfiguration for mutual TLS (mTLS).

    Args:
        path (str): The file path to the PEM-encoded client private key file.

    Returns:
        bytes: The client private key data in PEM format.

    Raises:
        FileNotFoundError: If the key file does not exist.
        ConfigurationError: If the key file is empty.

    Example usage::

        from glide_shared.config import (
            load_client_certificate_from_file,
            load_client_key_from_file,
            TlsAdvancedConfiguration
        )

        # Load client certificate and key from files
        client_cert = load_client_certificate_from_file('/path/to/client-cert.pem')
        client_key = load_client_key_from_file('/path/to/client-key.pem')

        # Use in TLS configuration
        tls_config = TlsAdvancedConfiguration(
            client_cert_pem=client_cert,
            client_key_pem=client_key
        )
    """
    ...

