"""
This type stub file was generated by pyright.
"""

from typing import Optional, Type
from glide_shared.protobuf.response_pb2 import RequestErrorType

class GlideError(Exception):
    """
    Base class for errors.
    """
    def __init__(self, message: Optional[str] = ...) -> None:
        ...
    
    def name(self) -> str:
        ...
    


class ClosingError(GlideError):
    """
    Errors that report that the client has closed and is no longer usable.
    """
    ...


class RequestError(GlideError):
    """
    Errors that were reported during a request.
    """
    ...


class TimeoutError(RequestError):
    """
    Errors that are thrown when a request times out.
    """
    ...


class ExecAbortError(RequestError):
    """
    Errors that are thrown when a transaction is aborted.
    """
    ...


class ConnectionError(RequestError):
    """
    Errors that are thrown when a connection disconnects.
    These errors can be temporary, as the client will attempt to reconnect.
    """
    ...


class ConfigurationError(RequestError):
    """
    Errors that are thrown when a request cannot be completed in current configuration settings.
    """
    ...


class LoggerError(GlideError):
    """
    Errors that are thrown when the logger has an error initializing.
    """
    ...


def get_request_error_class(error_type: Optional[RequestErrorType.ValueType]) -> Type[RequestError]:
    ...

