"""
This type stub file was generated by pyright.
"""

from typing import Optional

"""
OpenTelemetry configuration classes shared between async and sync clients.

OpenTelemetry can only be initialized once per process. Calling OpenTelemetry.init()
more than once will be ignored. If you need to change configuration, restart the process
with new settings.

OpenTelemetry Configuration
----------------------------

OpenTelemetryConfig: Main configuration object for OpenTelemetry exporters and options.

* traces: (optional) Configure trace exporting using OpenTelemetryTracesConfig.

  * endpoint: The collector endpoint for traces. Supported protocols:
    http://, https:// for HTTP/HTTPS, grpc:// for gRPC, file:// for local file export
  * sample_percentage: (optional) The percentage of requests to sample (0-100). Defaults to 1.
    Note: Higher sampling percentages impact performance. Recommended: 1-5% in production.

* metrics: (optional) Configure metrics exporting using OpenTelemetryMetricsConfig.

  * endpoint: The collector endpoint for metrics. Same protocol rules as above.

* flush_interval_ms: (optional) Interval in milliseconds for flushing data. Defaults to 5000ms.

File Exporter Details
---------------------

For file:// endpoints:

* Path must start with file:// (e.g., file:///tmp/otel or file:///tmp/otel/traces.json)
* If path is a directory or lacks extension, data is written to signals.json in that directory
* If path includes filename with extension, that file is used as-is
* Parent directory must exist; otherwise initialization fails with InvalidInput error
* If target file exists, new data is appended (not overwritten)

Validation Rules
----------------

* flush_interval_ms must be a positive integer
* sample_percentage must be between 0 and 100
* File exporter paths must start with file:// and have an existing parent directory
* Invalid configuration will throw an error when calling OpenTelemetry.init()
"""
class OpenTelemetryTracesConfig:
    """Configuration for exporting OpenTelemetry traces."""
    def __init__(self, endpoint: str, sample_percentage: Optional[int] = ...) -> None:
        ...

    def get_endpoint(self) -> str:
        ...

    def get_sample_percentage(self) -> int:
        ...



class OpenTelemetryMetricsConfig:
    """Configuration for exporting OpenTelemetry metrics."""
    def __init__(self, endpoint: str) -> None:
        ...

    def get_endpoint(self) -> str:
        ...



class OpenTelemetryConfig:
    """Configuration for OpenTelemetry integration."""
    def __init__(self, traces: Optional[OpenTelemetryTracesConfig] = ..., metrics: Optional[OpenTelemetryMetricsConfig] = ..., flush_interval_ms: Optional[int] = ...) -> None:
        ...

    def get_traces(self) -> Optional[OpenTelemetryTracesConfig]:
        ...

    def set_traces(self, traces: OpenTelemetryTracesConfig) -> None:
        ...

    def get_metrics(self) -> Optional[OpenTelemetryMetricsConfig]:
        ...

    def get_flush_interval_ms(self) -> Optional[int]:
        ...
