"""
This type stub file was generated by pyright.
"""

from typing import Tuple, Type
from google.protobuf import message

class ProtobufCodec:
    """
    Codec for protobuf messages.
    All of the Varint functions were copied from [protobuf](https://github.com/protocolbuffers/protobuf)
    """
    @classmethod
    def decode_delimited(cls, read_bytes: bytearray, read_bytes_view: memoryview, offset: int, message_class: Type[message.Message]) -> Tuple[message.Message, int]:
        ...

    @classmethod
    def encode_delimited(cls, b_arr: bytearray, message: message.Message) -> None:
        ...



class PartialMessageException(Exception):
    ...
