"""
This type stub file was generated by pyright.
"""

from enum import Enum
from typing import Optional
from glide_shared.protobuf.command_request_pb2 import CommandRequest, Routes, SlotTypes as ProtoSlotTypes

class SlotType(Enum):
    PRIMARY = ...
    REPLICA = ...


class Route:
    def __init__(self) -> None:
        ...
    


class AllNodes(Route):
    """
    Route request to all nodes.

    Warning:
        Don't use it with write commands, they could be routed to a replica (RO) node and fail.
    """
    ...


class AllPrimaries(Route):
    """
    Route request to all primary nodes.
    """
    ...


class RandomNode(Route):
    """
    Route request to a random node.

    Warning:
        Don't use it with write commands, because they could be randomly routed to a replica (RO) node and fail.
    """
    ...


class SlotKeyRoute(Route):
    """Routes a request to a node by its slot key

    Attributes:
        slot_type (SlotType): Defines type of the node being addressed.
        slot_key (str): The request will be sent to nodes managing this key.
    """
    def __init__(self, slot_type: SlotType, slot_key: str) -> None:
        ...
    


class SlotIdRoute(Route):
    """Routes a request to a node by its slot ID

    Attributes:
        slot_type (SlotType): Defines type of the node being addressed.
        slot_id (int): Slot number. There are 16384 slots in a Valkey cluster, and each shard
            manages a slot range. Unless the slot is known, it's better to route using
            `SlotType.PRIMARY`
    """
    def __init__(self, slot_type: SlotType, slot_id: int) -> None:
        ...
    


class ByAddressRoute(Route):
    """Routes a request to a node by its address

    Attributes:
        host (str): The endpoint of the node. If `port` is not provided, should be in the f"{address}:{port}" format,
            where `address` is the preferred endpoint as shown in the output of the `CLUSTER SLOTS` command.
        port (Optional[int]): The port to access on the node. If port is not provided, `host` is assumed to be in
            the format f"{address}:{port}".
    """
    def __init__(self, host: str, port: Optional[int] = ...) -> None:
        ...
    


def to_protobuf_slot_type(slot_type: SlotType) -> ProtoSlotTypes.ValueType:
    ...

def build_protobuf_route(route: Optional[Route]) -> Optional[Routes]:
    ...

def set_protobuf_route(request: CommandRequest, route: Optional[Route]) -> None:
    ...

