"""
This type stub file was generated by pyright.
"""

import typing
import asyncio
import trio
from .._models import Request, Response
from .._types import AsyncByteStream
from .base import AsyncBaseTransport

if typing.TYPE_CHECKING:
    Event = typing.Union[asyncio.Event, trio.Event]
_Message = typing.MutableMapping[str, typing.Any]
_Receive = typing.Callable[[], typing.Awaitable[_Message]]
_Send = typing.Callable[[typing.MutableMapping[str, typing.Any]], typing.Awaitable[None]]
_ASGIApp = typing.Callable[[typing.MutableMapping[str, typing.Any], _Receive, _Send], typing.Awaitable[None]]
__all__ = ["ASGITransport"]
def is_running_trio() -> bool:
    ...

def create_event() -> Event:
    ...

class ASGIResponseStream(AsyncByteStream):
    def __init__(self, body: list[bytes]) -> None:
        ...

    async def __aiter__(self) -> typing.AsyncIterator[bytes]:
        ...



class ASGITransport(AsyncBaseTransport):
    """
    A custom AsyncTransport that handles sending requests directly to an ASGI app.

    ```python
    transport = httpx.ASGITransport(
        app=app,
        root_path="/submount",
        client=("1.2.3.4", 123)
    )
    client = httpx.AsyncClient(transport=transport)
    ```

    Arguments:

    * `app` - The ASGI application.
    * `raise_app_exceptions` - Boolean indicating if exceptions in the application
       should be raised. Default to `True`. Can be set to `False` for use cases
       such as testing the content of a client 500 response.
    * `root_path` - The root path on which the ASGI application should be mounted.
    * `client` - A two-tuple indicating the client IP and port of incoming requests.
    ```
    """
    def __init__(self, app: _ASGIApp, raise_app_exceptions: bool = ..., root_path: str = ..., client: tuple[str, int] = ...) -> None:
        ...

    async def handle_async_request(self, request: Request) -> Response:
        ...
