"""
This type stub file was generated by pyright.
"""

import contextlib
import typing
import ssl
import httpx
from types import TracebackType
from .._config import Limits
from .._models import Request, Response
from .._types import AsyncByteStream, CertTypes, ProxyTypes, SyncByteStream
from .base import AsyncBaseTransport, BaseTransport

"""
Custom transports, with nicely configured defaults.

The following additional keyword arguments are currently supported by httpcore...

* uds: str
* local_address: str
* retries: int

Example usages...

# Disable HTTP/2 on a single specific domain.
mounts = {
    "all://": httpx.HTTPTransport(http2=True),
    "all://*example.org": httpx.HTTPTransport()
}

# Using advanced httpcore configuration, with connection retries.
transport = httpx.HTTPTransport(retries=1)
client = httpx.Client(transport=transport)

# Using advanced httpcore configuration, with unix domain sockets.
transport = httpx.HTTPTransport(uds="socket.uds")
client = httpx.Client(transport=transport)
"""
if typing.TYPE_CHECKING:
    ...
T = typing.TypeVar("T", bound="HTTPTransport")
A = typing.TypeVar("A", bound="AsyncHTTPTransport")
SOCKET_OPTION = typing.Union[typing.Tuple[int, int, int], typing.Tuple[int, int, typing.Union[bytes, bytearray]], typing.Tuple[int, int, None, int],]
__all__ = ["AsyncHTTPTransport", "HTTPTransport"]
HTTPCORE_EXC_MAP: dict[type[Exception], type[httpx.HTTPError]] = ...
@contextlib.contextmanager
def map_httpcore_exceptions() -> typing.Iterator[None]:
    ...

class ResponseStream(SyncByteStream):
    def __init__(self, httpcore_stream: typing.Iterable[bytes]) -> None:
        ...

    def __iter__(self) -> typing.Iterator[bytes]:
        ...

    def close(self) -> None:
        ...



class HTTPTransport(BaseTransport):
    def __init__(self, verify: ssl.SSLContext | str | bool = ..., cert: CertTypes | None = ..., trust_env: bool = ..., http1: bool = ..., http2: bool = ..., limits: Limits = ..., proxy: ProxyTypes | None = ..., uds: str | None = ..., local_address: str | None = ..., retries: int = ..., socket_options: typing.Iterable[SOCKET_OPTION] | None = ...) -> None:
        ...

    def __enter__(self: T) -> T:
        ...

    def __exit__(self, exc_type: type[BaseException] | None = ..., exc_value: BaseException | None = ..., traceback: TracebackType | None = ...) -> None:
        ...

    def handle_request(self, request: Request) -> Response:
        ...

    def close(self) -> None:
        ...



class AsyncResponseStream(AsyncByteStream):
    def __init__(self, httpcore_stream: typing.AsyncIterable[bytes]) -> None:
        ...

    async def __aiter__(self) -> typing.AsyncIterator[bytes]:
        ...

    async def aclose(self) -> None:
        ...



class AsyncHTTPTransport(AsyncBaseTransport):
    def __init__(self, verify: ssl.SSLContext | str | bool = ..., cert: CertTypes | None = ..., trust_env: bool = ..., http1: bool = ..., http2: bool = ..., limits: Limits = ..., proxy: ProxyTypes | None = ..., uds: str | None = ..., local_address: str | None = ..., retries: int = ..., socket_options: typing.Iterable[SOCKET_OPTION] | None = ...) -> None:
        ...

    async def __aenter__(self: A) -> A:
        ...

    async def __aexit__(self, exc_type: type[BaseException] | None = ..., exc_value: BaseException | None = ..., traceback: TracebackType | None = ...) -> None:
        ...

    async def handle_async_request(self, request: Request) -> Response:
        ...

    async def aclose(self) -> None:
        ...
