"""
This type stub file was generated by pyright.
"""

import typing
from .._models import Request, Response
from .base import AsyncBaseTransport, BaseTransport

SyncHandler = typing.Callable[[Request], Response]
AsyncHandler = typing.Callable[[Request], typing.Coroutine[None, None, Response]]
__all__ = ["MockTransport"]
class MockTransport(AsyncBaseTransport, BaseTransport):
    def __init__(self, handler: SyncHandler | AsyncHandler) -> None:
        ...

    def handle_request(self, request: Request) -> Response:
        ...

    async def handle_async_request(self, request: Request) -> Response:
        ...
