"""
This type stub file was generated by pyright.
"""

from ._base import Sequence
from ._struct import Invisible, Struct, StructDefMixin, UnionHook, struct, struct_factory, union
from ._bitfield import Bitfield, BitfieldDefMixin, BitfieldEntry, BitfieldGroup, BitfieldValueFactory, CharFactory, DEFAULT_ALIGNMENT, EndGroup, EnumFactory, NewGroup, SetAlignment, bitfield, bitfield_factory, getbits, issigned
from ._template import TemplateTypeVar, derive, istemplate, template
from .provider import pack, pack_file, pack_into, sizeof, unpack, unpack_file

__all__ = ["Sequence", "Struct", "struct", "UnionHook", "union", "unpack", "unpack_file", "pack", "pack_into", "pack_file", "sizeof", "Bitfield", "bitfield", "BitfieldGroup", "issigned", "getbits", "istemplate", "template", "TemplateTypeVar", "derive", "NewGroup", "EndGroup", "SetAlignment", "BitfieldEntry", "BitfieldValueFactory", "EnumFactory", "CharFactory", "DEFAULT_ALIGNMENT", "Invisible", "StructDefMixin", "struct_factory", "bitfield_factory", "BitfieldDefMixin"]
