"""
This type stub file was generated by pyright.
"""

import dataclasses
from typing import Any, Callable, TypeVar
from typing_extensions import override
from caterpillar.fields import Field
from caterpillar.abc import _ArchLike, _ContextLambda, _EndianLike, _GreedyType, _LengthT, _StructLike, _SwitchLambda

class TemplateTypeVar:
    """Template type variable.

    These specialised type variables are used within a template definition. They
    support most field operators. Therefore, they can be used in some situations
    where you need to adapt the field type at runtime.

    >>> T = TemplateTypeVar("T")

    Note that there is currently no support for inlined type variables, for example:

    >>> @template(T)
    ... class Foo:
    ...     bar: Enum(Baz, T) # !!! throws an error

    is not possible.
    """
    name: str
    field_kwds: dict[str, Any]
    def __init__(self, name: str, **field_kwds: Any) -> None:
        ...

    @override
    def __repr__(self) -> str:
        ...

    def __getitem__(self, amount: _LengthT) -> TemplateTypeVar:
        ...

    def __rshift__(self, switch: _SwitchLambda | dict[str, _StructLike]) -> TemplateTypeVar:
        ...

    def __matmul__(self, offset: int | _ContextLambda[int]) -> TemplateTypeVar:
        ...

    def __set_byteorder__(self, order: _EndianLike) -> TemplateTypeVar:
        ...

    def __rsub__(self, bits: int | _ContextLambda[int]) -> TemplateTypeVar:
        ...

    def __floordiv__(self, condition: bool | _ContextLambda[bool]) -> TemplateTypeVar:
        ...

    def to_field(self, struct: _StructLike | _ContextLambda, arch: _ArchLike | None = ..., default: Any = ...) -> Field:
        ...



def get_caller_module(frame: int = ...) -> str:
    ...

@dataclasses.dataclass
class TemplateInfo:
    required_tys: dict[str, Any]
    positional_tys: dict[str, Any]
    def is_defined(self, name: str) -> bool:
        ...

    def add_required(self, name: str) -> None:
        ...

    def add_positional(self, name: str, default: Any | None = ...) -> None:
        ...



def istemplate(obj: object) -> bool:
    """Return true if the object is a template."""
    ...

_TemplateModelT = TypeVar("_TemplateModelT")
def template(*args: str | TemplateTypeVar, **kwargs: str | TemplateTypeVar) -> Callable[[type[_TemplateModelT]], type[_TemplateModelT]]:
    """
    Defines required template type variables if necessary and prepares
    template class definition.

    :return: a wrapper function that will be called with the class instance
    :rtype: Callable[[type], type]
    """
    ...

def get_mangled_name(model_ty: type, annotations: dict[str, Any]) -> str:
    ...

def derive(template_ty: type, *tys_args: _StructLike, partial: bool = ..., name: str | _GreedyType | None = ..., union: bool = ..., **tys_kwargs: _StructLike) -> type:
    """Creates a new struct class based on the given template class.

    :param template_ty: the template class
    :type template_ty: type
    :param partial: whether the resulting class is also a template, defaults to False
    :type partial: bool, optional
    :param name: the new class name, :code:`...` infers the outer variable name, defaults to None
    :type name: str | Ellipsis, optional
    :return: the derived type
    :rtype: type
    """
    ...
